### ISSUE TITLE
package uses old version for urllib3

### ISSUE THREAD

**Issue by talionet** [interpretml/interpret#100]
ERROR: intlgntsys-mls-cdoisrael-start-notebook 0.0.6 has requirement urllib3==1.23, but you'll have urllib3 1.25.7 which is incompatible.

**Comment by interpret-ml** [comment]
Hi @talionet,

Thank you for raising the issue. Is there a chance this is an issue with another library? The only urllib3 dependency should be coming from the ```requests``` library, which we have a very soft dependency on: 
 https://github.com/interpretml/interpret/blob/cb4481f79ea7437b4fe8f6b83342342964047e26/python/interpret-core/requirements.txt#L22

Our best guess is that another library of yours is forcing urllib3 to be pinned to exactly 1.23, which might cause troubles with other dependencies in your environment. Is it possible for you to relax this pin for ```intlgntsys-mls-cdoisrael-start-notebook```?

-IntepretML Team
