### ISSUE TITLE
Does EMB works for multi-label classification?

### ISSUE THREAD

**Issue by hpsong88** [interpretml/interpret#104]
Hello,

I am wondering if EBM works for multi-label classification or fits to OneVsRestClassifier?

Thanks!

**Comment by interpret-ml** [comment]
Hi @hpsong88,

EBM currently supports multiclass classification, but not multi-label classification. For multiclass, EBM doesn't use the OneVsRest method, or any multiclass -> binary reduction techniques. We use boosted decision trees under the hood to train EBM, which naturally handle multiclass learning.

-InterpretML Team
