### ISSUE TITLE
Will it work for any machine learning code model

### ISSUE THREAD

**Issue by Sandy4321** [interpretml/interpret#105]
Will it work for any machine learning code model
Let's say I have my own unique model coded as function
Can I feed this function to your code and get feature importance for each data sample ?

**Comment by interpret-ml** [comment]
Hi @Sandy4321, 

Yes, we do support interpretability for any machine learning model. Take a look at the "blackbox" portion of the package (here's an [example notebook](https://nbviewer.jupyter.org/github/interpretml/interpret/blob/master/examples/python/notebooks/Explaining%20Blackbox%20Classifiers.ipynb)). 

You can use any method from ```interpret.blackbox``` on your code. Here's an example of using LIME:

```python3
from interpret.blackbox import LimeTabular
from interpret import show

#Blackbox explainers need a predict function, and optionally a dataset
lime = LimeTabular(predict_fn=blackbox_model.predict_proba, data=X_train, random_state=1)

#Pick the instances to explain, optionally pass in labels if you have them
lime_local = lime.explain_local(X_test[:5], y_test[:5], name='LIME')

show(lime_local)
```

The ```predict_fn``` argument can be from any machine learning model -- just pass a method that returns probabilities for classification, and real targets for regression. ```explain_local``` will then give you feature importances for each data sample, for the methods that support it. 

Thanks!
-InterpretML Team

**Comment by Sandy4321** [comment]
just pass a method that returns probabilities for classification
So it is not full black box
Since many models do not return probabilities
But return only decision like 1 or 0
What can be done in this case?
