### ISSUE TITLE
Imbalanced dataset

### ISSUE THREAD

**Issue by ciberger** [interpretml/interpret#115]
Hi, 

As I couldn't find a parameter to handle an imbalanced dataset, would you recommend to resample the original dataset as the initial way to tackle the issue? Any other suggestion?

Thanks,
Cristóbal

**Comment by interpret-ml** [comment]
Hi @ciberger, 

Thanks for the question! You're correct, right now, we don't have a parameter to help with class imbalance. However, adding support for weighting instances is on our current backlog.

In general, if the dataset isn't too imbalanced, EBM will do reasonably well without resampling. In the case of severe imbalance, you can definitely try resampling to get a more balanced dataset before training. 

-InterpretML Team

**Comment by lukedex** [comment]
Has there been any update to adding in a sample_weight-ing?
