### ISSUE TITLE
ImportError: cannot import name 'show'

### ISSUE THREAD

**Issue by guomengzhuo** [interpretml/interpret#116]
Dear InterpretML Team,
Hi, I am a new user of both Python and Interpret Package. 
I follow the examples but I got an error at the first step.

'' ImportError: cannot import name 'show' ''

I work on Windows and the latest  verision of Interpret.
Maybe this is a stupid question, but I really need your help.
Thanks

**Comment by interpret-ml** [comment]
Hi @guomengzhuo , 

Just to clarify, this error occurs when you run 

```python3
 from interpret import show
```
right? An import error is surprising. Do you also get an import error when running

```python3
from interpret.glassbox import ExplainableBoostingClassifier
```
? 

It sounds like it could be an installation bug. 

Are you using any virtual environments (ex: conda environments)? 

Our first thought would be to try uninstalling and reinstalling interpret (from the command prompt):

```pip uninstall interpret```
```pip install -U interpret```

Do you mind trying this and seeing if it fixes the problem?

-InterpretML Team

**Comment by guomengzhuo** [comment]
> Hi @guomengzhuo ,
> 
> Just to clarify, this error occurs when you run
> 
> ```python
>  from interpret import show
> ```
> 
> right? An import error is surprising. Do you also get an import error when running
> 
> ```python
> from interpret.glassbox import ExplainableBoostingClassifier
> ```
> 
> ?
> 
> It sounds like it could be an installation bug.
> 
> Are you using any virtual environments (ex: conda environments)?
> 
> Our first thought would be to try uninstalling and reinstalling interpret (from the command prompt):
> 
> `pip uninstall interpret`
> `pip install -U interpret`
> 
> Do you mind trying this and seeing if it fixes the problem?
> 
> -InterpretML Team

Thanks for the reply. I have fixed this problem. 
For other new users, I will post my solutions. 
I used to perform this package on Python 3.5. Although it can be installed,  it seems that it cannot work on Python 3.5 (it has other Attributes, like ext, etc) Maybe it is a demo version :) 
So I try it on Python 3.7. 
Problem fixed.

Thanks for this project and your reply. 

Regards.
