### ISSUE TITLE
Cannot visualize local explainer

### ISSUE THREAD

**Issue by aleksandermajos** [interpretml/interpret#117]
I can get plotly figure in Python using 
'ebm = ExplainableBoostingRegressor(random_state=seed)
ebm.fit(X_df_train, Y_df_train)
ebm_global = ebm.explain_global(name='EBM')
ebm_local = ebm.explain_local(X_df_mini[Nr:Nr+1], Y_df_mini_mean, name='EBM')
plotly_object = ebm_global.visualize()
'
I also can get visualize in Notebook:
'ebm_global = ebm.explain_global(name='EBM')
ebm_local = ebm.explain_local(X_df_mini[Nr:Nr+1], Y_df_mini_mean, name='EBM')
show(ebm_global)
show(ebm_local)'

However:
I spend couple of hours try to get plotly figure from ebm_local  in Python trying:
'ebm = ExplainableBoostingRegressor(random_state=seed)
ebm.fit(X_df_train, Y_df_train)
ebm_local = ebm.explain_local(X_df_mini[Nr:Nr+1], Y_df_mini_mean, name='EBM')
plotly_object = ebm_local.visualize()'

Other words: I really need plotly object from local explainer.Cannot understand is if it has all necessary data to plot itself in Jupyter Notebook why I cannot get plotly object using Python

I will appreciate any help
Aleksander

**Comment by interpret-ml** [comment]
Hi @aleksandermajos, 

You're very close! The .visualize() call for local explanations needs a parameter ```key```, which specifies which local explanation to return. In your example, when you did X_df_mini[Nr:Nr+1], you only passed in a single instance to be explained, so you should be able to simply call:

```python3
ebm_local = ebm.explain_local(X_df_mini[Nr:Nr+1], Y_df_mini_mean, name='EBM')
plotly_object = ebm_local.visualize(key=0)
```

To get the plotly object back out. If you had passed in more instances to ```explain_local``` (for example, X_df_mini[Nr:Nr+20]), passing in different keys would return the plotly objects tied to each individual instance being explained. 

Hope this helps, and let us know if you have any further questions!

-InterpretML Team
