### ISSUE TITLE
There are no docstrings for the models

### ISSUE THREAD

**Issue by drakeeee** [interpretml/interpret#121]
Would you write some docstrings for the models? Docstrings and explanations for the model parameters would make it easier to understand and use them.

**Comment by interpret-ml** [comment]
Hi @drakeeee , 

Thanks for raising this issue! We just added some basic docstrings to each of the classes in the latest release. We'll have more comprehensive documentation coming in the future, but please take a look at [our latest release](https://github.com/interpretml/interpret/releases/tag/v0.1.22) and let us know what you think! 

-InterpretML Team
