### ISSUE TITLE
sorting issue

### ISSUE THREAD

**Issue by Hessa211** [interpretml/interpret#125]
https://github.com/interpretml/interpret/blob/4d6942fd12f1e7c95236368f167690c476ad462f/R/R/ebm.R#L61
Hi,
findInterval gives error due to lack of term sorted increasingly. 
Line 60 doesn't work for indicator variable. Before line 61,   I just added for(col_name in col_names) bin_edges[[col_name]] <- sort(bin_edges[[col_name]]) and it seems work.

Thanks

**Comment by interpret-ml** [comment]
Hi @Hessa211 - Thanks for reporting this to us.  It has been fixed in our latest R release on CRAN ( https://cran.r-project.org/package=interpret ).

-InterpretML team
