### ISSUE TITLE
Is it possible to output the values generating the shape line

### ISSUE THREAD

**Issue by zhongzhixu** [interpretml/interpret#128]
Dear authors,

Thanks for this great work, impressive.

Can I ask if there is a way to output the values that are used to visualize the shape functions and the interaction heat map?

Thanks,
Julien

**Comment by zhongzhixu** [comment]
as well as the confidence interval~

**Comment by interpret-ml** [comment]
Hi Julien, 

Sorry for the delay in getting back to you! Yes, you can get back the raw data behind any visualization using the ```.data()``` method on any explanation object.

For example:

```python3
ebm_global = ebm.explain_global()
explanation_data = ebm_global.data(1) # extracts the data for the visualization of the first feature
```
If you're having trouble finding out what key to pass to the .data() method, try checking ```ebm_global.feature_names``` to see the index of the feature you're interested in looking for (automatically detected interaction terms are normally at the end). The objects returned by .data() are simply python dictionaries, and the "scores" key of that dictionary has all the learned values. 

Please let us know if you have any further questions!

-InterpretML Team

**Comment by zhongzhixu** [comment]
It works! Thank you very much!
