### ISSUE TITLE
Dedicated package for EBM

### ISSUE THREAD

**Issue by MainRo** [interpretml/interpret#129]
Hello,

Thanks for your work, this project is really great. However model explanations and EBMs feel like two independent features implemented in the same package. Would it be possible to move EBM in a dedicated repository/package ? This would allow to use it without installing all the explanation dependencies. Such packages are not needed for deployment.

**Comment by interpret-ml** [comment]
Hi @MainRo,

Thanks for bringing this up. It's on our plate to better split the packages for deployment purposes.

Behind the scenes, we use two packages `interpret` and `interpret-core`. The `interpret` package is a thin wrapper over `interpret-core` with extra tags used to target dependencies.

If you wanted to use EBM without installing other dependencies you can try the following below:

**EBM for purely training and predicting.**
`pip install interpret-core[required,ebm]`

**EBM with visualizations via notebook**
`pip install interpret-core[required,ebm,plotly,dash]`

**Comment by MainRo** [comment]
Thanks for your answer. I saw the interpret/interpret-core packages but did not think about using directly interpret-core. I will try and use this solution until you eventually move EBM in a dedicated package.

**Comment by interpret-ml** [comment]
Closing for now.  The interpret-core method is what we recommend going forward.

-InterpretML
