### ISSUE TITLE
EBM Running very slow

### ISSUE THREAD

**Issue by mayur29** [interpretml/interpret#130]
Hi ,

I am trying to run Interpreation sample notebook given by you on Github for adult dataset . Somehow when i try to fit the model on test dataset , my Macbook Pro is not able to run this Algo. This never happens with any other library .

Do you have any suggestion , how to run this on local ?

Thanks
Mayur Sand

**Comment by mayur29** [comment]
Hi,

I tried running the same code on Kaggle notebook also . There too the CPU stayed at 100% for about 10 mins before I shut it down.

Has anyone else faced this problem ?

Thanks
Mayur Sand

**Comment by interpret-ml** [comment]
Hi @mayur29,

I presume, based on the medium article that you wrote, that you were able to get this to work.  EBMs are currently slower than other boosting algorithms given the round robin nature and low learning rate.  We do have plans to speed it up, perhaps by modifying these aspects, but it's an open question by how much or when.

Thanks for the positive Medium article.  For the benefit of others reading this issue, it can be found [here.]( https://medium.com/@sand.mayur/model-interpretation-with-microsofts-interpret-ml-85aa0ad697ae)

-InterpretML team
