### ISSUE TITLE
Explaining Images with InterpretML using Lime

### ISSUE THREAD

**Issue by SabaMt** [interpretml/interpret#134]
Hi, I was wondering if there is any way to use classes like the LimeImageExplainer or something similar in InterpretML?

**Comment by interpret-ml** [comment]
Hi @SabaMt, 

Right now, we're mostly focused on tabular data inside InterpretML, so we don't currently support methods like LimeImageExplainer. However, it's good to hear that there's demand for image based methods. While it's out of scope for the repository right now, we may support it in the future, so thanks for bringing this up :)!

For the time being, we recommend using [LIME](https://github.com/marcotcr/lime/) or [SHAP](https://github.com/slundberg/shap/) directly for image analysis. If you happen to be using PyTorch models, we also recommend checking out PyTorch's [Captum](https://github.com/pytorch/captum) toolkit. 

Thanks!
-InterpretML Team
