### ISSUE TITLE
Missing visualization functions in interpret package on CRAN for R

### ISSUE THREAD

**Issue by lucazav** [interpretml/interpret#136]
First of all, thank you for your great work about EBMs!
At first sight it seems there are no functions to plot interpretability graphs on the [CRAN package](https://cran.r-project.org/web/packages/interpret/index.html) for R.
Is there a chance to get them also for R users?
Thank you.

**Comment by interpret-ml** [comment]
Hi @lucazav - Our latest R release on CRAN includes the ability to graph EBM models ( https://cran.r-project.org/package=interpret ).  The models have also been improved to the point where they should have similar metrics to models built in python using the default settings, which does not include interactions currently.  There's still plenty of work ahead of us on the R package, but we'll continue to iterate.

-InterpretML team
