### ISSUE TITLE
Colab visualisations

### ISSUE THREAD

**Issue by andreb8** [interpretml/interpret#138]
Show() renders blank outputs in Colab

**Comment by interpret-ml** [comment]
Hi @andreb8 , 

Our intergration with Colab is still experimental -- apologies for any difficulties you might be experiencing until we solidify it. 

That said, I am able to get outputs in Colab with this minimal example: 

`!pip install interpret`

```python3
from interpret.glassbox import ExplainableBoostingRegressor
from sklearn.datasets import load_boston

bos = load_boston()
X, y = load_boston(return_X_y=True)

ebm = ExplainableBoostingRegressor(feature_names=bos.feature_names)
ebm.fit(X, y)
```

```python3
from interpret import show

show(ebm.explain_global())
```

![image](https://user-images.githubusercontent.com/50031429/84079247-4b3b5180-a9a8-11ea-8ac6-8fd5f5cf7a7b.png)

Do you mind sharing an example where the visualization fails? Are there any special settings you are using in your Colab notebook? 

Appreciate the report and the help!

-InterpretML Team

**Comment by interpret-ml** [comment]
Hi @andreb8, 

In our latest release of interpret v0.2.0, we have introduced improved support for cloud environments, especially focused on Colab and Databricks. We hope this new release will fix any lingering errors you may have experienced on Colab. Please give it a try, and feel free to re-open this issue if the problem persists!

-InterpretML Team
