### ISSUE TITLE
Support for pyspark ml models

### ISSUE THREAD

**Issue by prarshah** [interpretml/interpret#140]
Found this extremely useful, wondering if there are any future plans to support PySpark ML models? as SHAP's tree explainer supports it, thanks in advance.

**Comment by interpret-ml** [comment]
Hi @prarshah , 

The blackbox techniques in InterpretML should work on PySpark, although they aren't particularly optimized for it. We are lightly exploring how to add glassbox capabilities (like EBMs) on PySpark or general Spark environments, but have no definitive timelines yet. That said, it's good to hear from you that there is demand for this, so thank you for bringing it up!

-InterpretML Team

**Comment by kishoresurana** [comment]
+1 for support PySpark ML models
