### ISSUE TITLE
Issues reading an excel file (.xlsx)

### ISSUE THREAD

**Issue by czuche** [interpretml/interpret#141]
I am following your example to read my excel data (see the attached excerpt). The problem is that while I am able to read the file, the column names are replaced with "feature_0", "feature_1" etc. This  matters because, I am unable to know exactly which feature is selected. My full file contains > 3000 features and requires feature selection before passing the selected features to the "ExplainableBoostingClassifier(random_state=seed)". Moreover, my attempt to compare my data with other models shows this  error:

from interpret.glassbox import LogisticRegression, ClassificationTree
# We have to transform categorical variables to use Logistic Regression and Decision Tree
X_enc = pd.get_dummies(X, prefix_sep='.')
feature_names = list(X_enc.columns)
X_train_enc, X_test_enc, y_train, y_test = train_test_split(X_enc, y, test_size=0.20, random_state=seed)
lr = LogisticRegression(random_state=seed, feature_names=feature_names, penalty='l1', solver='liblinear')
lr.fit(X_train_enc, y_train)
tree = ClassificationTree()
tree.fit(X_train_enc, y_train) 

**ERROR**

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-13-4cd92298e5a6> in <module>
      2 
      3 # We have to transform categorical variables to use Logistic Regression and Decision Tree
----> 4 X_enc = pd.get_dummies(X, prefix_sep='.')
      5 feature_names = list(X_enc.columns)
      6 X_train_enc, X_test_enc, y_train, y_test = train_test_split(X_enc, y, test_size=0.20, random_state=seed)

~\anaconda3\lib\site-packages\pandas\core\reshape\reshape.py in get_dummies(data, prefix, prefix_sep, dummy_na, columns, sparse, drop_first, dtype)
    932             sparse=sparse,
    933             drop_first=drop_first,
--> 934             dtype=dtype,
    935         )
    936     return result

~\anaconda3\lib\site-packages\pandas\core\reshape\reshape.py in _get_dummies_1d(data, prefix, prefix_sep, dummy_na, sparse, drop_first, dtype)
    949 
    950     # Series avoids inconsistent NaN handling
--> 951     codes, levels = factorize_from_iterable(Series(data))
    952 
    953     if dtype is None:

~\anaconda3\lib\site-packages\pandas\core\series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    303                     data = data.copy()
    304             else:
--> 305                 data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
    306 
    307                 data = SingleBlockManager(data, index, fastpath=True)

~\anaconda3\lib\site-packages\pandas\core\construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure)
    480     elif subarr.ndim > 1:
    481         if isinstance(data, np.ndarray):
--> 482             raise Exception("Data must be 1-dimensional")
    483         else:
    484             subarr = com.asarray_tuplesafe(data, dtype=dtype)

Exception: Data must be 1-dimensional

Any help to solve the above issue will be appreciate.

![Excel file reading problem](https://user-images.githubusercontent.com/50029765/84092385-2acdc000-a9c5-11ea-9ced-83a169f0e50f.jpg)
![Data](https://user-images.githubusercontent.com/50029765/84092431-4c2eac00-a9c5-11ea-8155-6f67711e3f45.jpg)

**Comment by interpret-ml** [comment]
Hi @czuche , 

It sounds like the error you're experiencing might be related to pandas. Pandas read_csv and read_excel methods provide a ```header``` parameter which lets you specify which row of your .xlsx or .csv file contain headers/names for your fields. You can verify that your dataframe correctly inferred the column names by checking the contents of your dataframe's ```.columns``` property. 

After feature selection, you can also pass the feature names directly to EBM at initialization time, through the init parameter:

```python3
from interpret.glassbox import ExplainableBoostingClassifier

ebm = ExplainableBoostingClassifier(random_state = seed, feature_names = ["Sex", "Age", "Race", "Arm", "IMRT"])
ebm.fit(X_train, y_train)   # Assumes that X train has 5 features in the same order as the feature_names init parameter
```
This guarantees that the dropdowns and visualizations will have informative feature names. The package only auto-generates names like ```feature0``` and ```feature1``` when this parameter is not supplied and couldn't be inferred from the dataset.

As for the second example, I'm not quite sure why the get_dummies call fails. It could be that one of your columns was poorly formatted, or maybe Pandas is struggling with the size of the dataset. You can try alternative toolkits for one-hot encoding like [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html), or use a different encoding scheme altogether. The other techniques simply require all numeric inputs. 

Hope this helps!

-InterpretML Team
