### ISSUE TITLE
Mac OS install issue

### ISSUE THREAD

**Issue by JustinLStrong** [interpretml/interpret#143]
Hi there! I am getting this error. Can you help?
Collecting interpret
  Using cached interpret-0.1.22-py3-none-any.whl (1.4 kB)
Collecting interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22
  Using cached interpret_core-0.1.22-py3-none-any.whl (8.3 MB)
Requirement already satisfied: dash-cytoscape>=0.1.1; extra == "dash" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.1.1)
Requirement already satisfied: dash>=1.0.0; extra == "dash" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.12.0)
Requirement already satisfied: dash-table>=4.1.0; extra == "dash" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (4.7.0)
Collecting gevent>=1.3.6; extra == "dash"
  Using cached gevent-20.6.1-cp38-cp38-macosx_10_15_x86_64.whl (1.8 MB)
Requirement already satisfied: requests>=2.19.0; extra == "dash" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2.23.0)
Collecting psutil>=5.6.2; extra == "debug"
  Using cached psutil-5.7.0.tar.gz (449 kB)
Collecting joblib>=0.11; extra == "decisiontree"
  Using cached joblib-0.15.1-py3-none-any.whl (298 kB)
Collecting lime>=0.1.1.33; extra == "lime"
  Using cached lime-0.2.0.0.tar.gz (274 kB)
Requirement already satisfied: ipykernel>=5.1.0; extra == "notebook" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (5.1.3)
Requirement already satisfied: ipython>=7.4.0; extra == "notebook" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (7.11.1)
Requirement already satisfied: plotly>=3.8.1; extra == "plotly" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (4.8.1)
Collecting scikit-learn>=0.18.1; extra == "required"
  Using cached scikit_learn-0.23.1-cp38-cp38-macosx_10_9_x86_64.whl (7.2 MB)
Requirement already satisfied: pandas>=0.19.2; extra == "required" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.25.3)
Collecting scipy>=0.18.1; extra == "required"
  Using cached scipy-1.4.1-cp38-cp38-macosx_10_9_x86_64.whl (28.8 MB)
Requirement already satisfied: numpy>=1.11.1; extra == "required" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.18.1)
Processing ./Library/Caches/pip/wheels/62/ed/f9/a0b98754ffb2191b98324b96cbbeb1bd5d9598b39ab996b429/SALib-1.3.11-py2.py3-none-any.whl
Collecting shap>=0.28.5; extra == "shap"
  Using cached shap-0.35.0.tar.gz (273 kB)
Collecting dill>=0.2.5; extra == "shap"
  Using cached dill-0.3.1.1.tar.gz (151 kB)
Collecting treeinterpreter>=0.2.2; extra == "treeinterpreter"
  Using cached treeinterpreter-0.2.2-py2.py3-none-any.whl (6.2 kB)
Requirement already satisfied: dash-html-components in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from dash-cytoscape>=0.1.1; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.0.3)
Requirement already satisfied: dash_renderer in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from dash-cytoscape>=0.1.1; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.4.1)
Requirement already satisfied: Flask>=1.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.1.2)
Requirement already satisfied: flask-compress in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.5.0)
Requirement already satisfied: dash-core-components==1.10.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.10.0)
Requirement already satisfied: future in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.18.2)
Collecting greenlet>=0.4.16; platform_python_implementation == "CPython"
  Using cached greenlet-0.4.16.tar.gz (60 kB)
Requirement already satisfied: zope.interface in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from gevent>=1.3.6; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (5.1.0)
Requirement already satisfied: zope.event in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from gevent>=1.3.6; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (4.4)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from gevent>=1.3.6; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (47.1.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests>=2.19.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests>=2.19.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests>=2.19.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2020.4.5.2)
Requirement already satisfied: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests>=2.19.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2.9)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from lime>=0.1.1.33; extra == "lime"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (3.1.2)
Collecting tqdm
  Using cached tqdm-4.46.1-py2.py3-none-any.whl (63 kB)
Collecting pillow==5.4.1
  Using cached Pillow-5.4.1.tar.gz (16.0 MB)
Collecting scikit-image>=0.12
  Using cached scikit_image-0.17.2-cp38-cp38-macosx_10_13_x86_64.whl (12.2 MB)
Requirement already satisfied: appnope; platform_system == "Darwin" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipykernel>=5.1.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.1.0)
Requirement already satisfied: jupyter-client in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipykernel>=5.1.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (5.3.4)
Requirement already satisfied: traitlets>=4.1.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipykernel>=5.1.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (4.3.3)
Requirement already satisfied: tornado>=4.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipykernel>=5.1.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (6.0.3)
Requirement already satisfied: pickleshare in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (3.0.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (4.8.0)
Requirement already satisfied: jedi>=0.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.16.0)
Requirement already satisfied: decorator in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (4.4.1)
Requirement already satisfied: backcall in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.1.0)
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2.5.2)
Requirement already satisfied: retrying>=1.3.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from plotly>=3.8.1; extra == "plotly"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.3.3)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from plotly>=3.8.1; extra == "plotly"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.14.0)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas>=0.19.2; extra == "required"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas>=0.19.2; extra == "required"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2.8.1)
Requirement already satisfied: itsdangerous>=0.24 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from Flask>=1.0.2->dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from Flask>=1.0.2->dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from Flask>=1.0.2->dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2.10.3)
Requirement already satisfied: click>=5.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from Flask>=1.0.2->dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (7.1.2)
Requirement already satisfied: brotli in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from flask-compress->dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.0.7)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib->lime>=0.1.1.33; extra == "lime"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (2.4.6)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib->lime>=0.1.1.33; extra == "lime"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib->lime>=0.1.1.33; extra == "lime"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.10.0)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2020.6.3-py3-none-any.whl (133 kB)
Collecting imageio>=2.3.0
  Using cached imageio-2.8.0-py3-none-any.whl (3.3 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (4.3 MB)
Collecting networkx>=2.0
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Requirement already satisfied: pyzmq>=13 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jupyter-client->ipykernel>=5.1.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (18.1.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jupyter-client->ipykernel>=5.1.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (4.6.1)
Requirement already satisfied: ipython-genutils in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from traitlets>=4.1.0->ipykernel>=5.1.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.2.0)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.1.8)
Requirement already satisfied: ptyprocess>=0.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pexpect; sys_platform != "win32"->ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.6.0)
Requirement already satisfied: parso>=0.5.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from jedi>=0.10->ipython>=7.4.0; extra == "notebook"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (0.5.2)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from Jinja2>=2.10.1->Flask>=1.0.2->dash>=1.0.0; extra == "dash"->interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.22->interpret) (1.1.1)
Using legacy setup.py install for psutil, since package 'wheel' is not installed.
Using legacy setup.py install for lime, since package 'wheel' is not installed.
Using legacy setup.py install for shap, since package 'wheel' is not installed.
Using legacy setup.py install for dill, since package 'wheel' is not installed.
Using legacy setup.py install for greenlet, since package 'wheel' is not installed.
Using legacy setup.py install for pillow, since package 'wheel' is not installed.
Installing collected packages: greenlet, gevent, psutil, joblib, scipy, tqdm, pillow, threadpoolctl, scikit-learn, tifffile, imageio, PyWavelets, networkx, scikit-image, lime, SALib, shap, dill, treeinterpreter, interpret-core, interpret

    Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6_/76yn8yhj2bs56n5gw07vr_5r0000gq/T/pip-install-_1f7pix_/greenlet/setup.py'"'"'; __file__='"'"'/private/var/folders/6_/76yn8yhj2bs56n5gw07vr_5r0000gq/T/pip-install-_1f7pix_/greenlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/6_/76yn8yhj2bs56n5gw07vr_5r0000gq/T/pip-record-0wp650wz/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/greenlet
         cwd: /private/var/folders/6_/76yn8yhj2bs56n5gw07vr_5r0000gq/T/pip-install-_1f7pix_/greenlet/
    Complete output (9 lines):
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.macosx-10.9-x86_64-3.8
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c greenlet.c -o build/temp.macosx-10.9-x86_64-3.8/greenlet.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6_/76yn8yhj2bs56n5gw07vr_5r0000gq/T/pip-install-_1f7pix_/greenlet/setup.py'"'"'; __file__='"'"'/private/var/folders/6_/76yn8yhj2bs56n5gw07vr_5r0000gq/T/pip-install-_1f7pix_/greenlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/6_/76yn8yhj2bs56n5gw07vr_5r0000gq/T/pip-record-0wp650wz/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/greenlet Check the logs for full command output.

**Comment by JustinLStrong** [comment]
Solved - needed to update with:
pip install --upgrade azureml-sdk
then call interpret

**Comment by Naviden** [comment]
I have more or less the same problem. The only difference is that I get     
`error: command 'clang' failed with exit status 1`
