### ISSUE TITLE
how to extract the data point of partial dependence plots.

### ISSUE THREAD

**Issue by dengxinlei7** [interpretml/interpret#144]
pdp = PartialDependence(predict_fn=gd.predict, data=X_test)
pdp_global = pdp.explain_global(name='Partial Dependence')
show(pdp_global)
I want to only  plot the main line of partial dependence. The rest background lines are confusing.
How to extract the data point of partial dependence plots and plot the only main line?

**Comment by interpret-ml** [comment]
Hi @dengxinlei7 , 

Thanks for bringing this up, and our apologies for the delay in getting back to you. You can extract the underlying data between any visualization using the ```.data()``` method tied to an explanation object. This method takes in a ```key``` as an input argument, which simply indicates which feature's data you want:

```python3
from interpret.blackbox import PartialDependence

pdp = PartialDependence(predict_fn=blackbox_model.predict, data=X_train, )
pdp_global = pdp.explain_global(name='Partial Dependence')

pdp_data = pdp_global.data(2)  # Gets data for Partial Dependence Plot of feature 2
```

```pdp_data``` is a dictionary which contains info about the main line, density distribution at the bottom, and all the background lines. To simply get the x/y axis values for the main line, you can extract the arrays in the ```names``` and ```scores``` keys:

```python3
x_values = pdp_data['names']
y_values = pdp_data['scores']
```

You can then pass them to any plotting library of your choice. Here is the code to generate a similar style graph in plotly:

```python3
import plotly.express as px

px.line(x = pdp_data['names'], y = pdp_data['scores'], title="Age")
```

which looks like this: 

![image](https://user-images.githubusercontent.com/50031429/88213864-4f08f780-cc27-11ea-9775-31cef3f06dfd.png)


Please let us know if you have any further questions!

-InterpretML Team

**Comment by dengxinlei7** [comment]
Thank you so much! Many thanks for your great work!

**Comment by PawaritL** [comment]
Hi @interpret-ml and @dengxinlei7,
I'm also a bit confused by the different background lines. What do they represent exactly? and what do those background numbers map to? an example would be great! thanks so much in advance

![image](https://user-images.githubusercontent.com/39638268/114793747-5d85d900-9d8b-11eb-837d-ee62526ea518.png)

**Comment by MasemeneMatlakanaBenny** [comment]
Thank you so much for this response.I still find it useful
