### ISSUE TITLE
Export complete dashboard to HTML file

### ISSUE THREAD

**Issue by jackwellsxyz** [interpretml/interpret#145]
Hi, it would be nice if I could export a dashboard (i.e. list of visualizations) to an HTML file, such as in the below example. Looks like the necessary code is in python/interpret-core/provider/visualize.py.

```
from interpret.glassbox import ExplainableBoostingClassifier
from interpret import show, preserve

ebm = ExplainableBoostingClassifier()
ebm.fit(X_train, y_train)
ebm_global = ebm.explain_global(name='EBM')
ebm_local = ebm.explain_local(X_test, y_test)

# Below displays a dashboard inline in a Jupyter lab notebook with a link to expand to another window
# such as (127.0.0.1:7060/12345678/index.html) 
show([ebm_global, ebm_local])

# Below command does not work with a list, only with an individual visualization, and does not 
# display in a dashboard format
preserve([ebm_global, ebm_local], file_name='dashboard.html')
```

**Comment by interpret-ml** [comment]
Hi @jackwellsxyz and @mosew, 

Unfortunately this isn't possible with our current visualization stack. You can export individual explanations to HTML, but it isn't possible to do so for the dashboard. 

Re-writing our dashboard stack is on our backlog, but there's no current timeline for when this will happen. Thanks for letting us know that this would be useful functionality for you!

-InterpretML Team
