### ISSUE TITLE
"Error loading dependecies" in show() method

### ISSUE THREAD

**Issue by nfsrules** [interpretml/interpret#15]
Hi guys, thanks for this great contribution.

Each time I use the method 'show()' I got the following error:
        "Error loading dependencies"

Examples:

ebm_global = ebm.explain_global(name='EBM')
show(ebm_global)  #  "error loading dependencies

I'm using Python 3.7

Thanks in advance,

Nelson

**Comment by interpret-ml** [comment]
Hi @nfsrules, much appreciated!

Interesting, we've seen dependency troubles before relating to dash, but not by this call.

- What version of gevent and plotly are you running? You can see with `pip show gevent plotly`.
- Do you mind showing the full error here (scrubbed is fine)? Alternatively, please send it to interpret@microsoft.com.

**Comment by glende** [comment]
Hi, 
I also got error each time when I called 'show()' : You’ve stumbled upon some vintage web tech
This website runs on older technology and will only work in Internet Explorer. 
Could you please tell me how can I solve this problem?  I am using Python 3.7.3 with jupyter notebook on Microsoft Edge

**Comment by huangwei2013** [comment]
may try run in termial， with command "strace" ahead，may find out what it required

> strace [you command]

**Comment by interpret-ml** [comment]
Hi @glende!

Can you let us know what Microsoft Edge version you are on? You can use the following instructions to find it:
1. Open Microsoft Edge. 
2. Select Settings and more in the upper-right corner, and then select Settings.
3. Look for your version under About this app.

**Comment by glende** [comment]
Hi @interpret-ml ,
sure, the version is: Microsoft Edge 42.17134.1.0

**Comment by kartheekpnsn** [comment]
@interpret-ml, Is this issue still open? I am also facing the same issue.

**Comment by interpret-ml** [comment]
Hi @glende and @kartheekpnsn , 

We're having difficulties reproducing this on our end. Can you tell us if this problem holds on other browsers (Edge-Development/Firefox/Chrome)? 

Also, would you mind telling us the version of gevent/plotly you are using? You can get this information by running the following command: ```pip show gevent plotly```. Thanks for the help in reporting this!

**Comment by kartheekpnsn** [comment]
I have tried it in Firefox (not working), Chrome (not working), IE (**working**), Edge (**working**)

For the command ```pip show gevent plotly``` below is the output.
```
Name: gevent
Version: 1.4.0
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Denis Bilenko
Author-email: denis.bilenko@gmail.com
License: MIT
Location: c:\users\lep5kor\appdata\roaming\python\python36\site-packages
Requires: greenlet, cffi
Required-by: interpret
---
Name: plotly
Version: 3.10.0
Summary: An open-source, interactive graphing library for Python
Home-page: https://plot.ly/python/
Author: Chris P
Author-email: chris@plot.ly
License: MIT
Location: c:\users\lep5kor\appdata\roaming\python\python36\site-packages
Requires: six, retrying, nbformat, requests, decorator, pytz
Required-by: interpret, dash```

**Comment by mikewlange** [comment]
hi @kartheekpnsn ! I think I found it. Sometimes it's staring us right in the face. 

I know I'm stating the obvious, but have you looked into python7 versions and plotly via 3.6's relationship status? They broke up. They don't even follow each other on Instagram anymore. 

>  I am using Python 3.7.3 with jupyter notebook on Microsoft Edge

> Location: c:\users\lep5kor\appdata\roaming\python\python36\site-packages

> c:\users\lep5kor\appdata\roaming\python\python36\site-packages

Compartmentalize an environment and test again and don't mix python versions and bet you'll get it to work. I actually have to get to work so I can't test. But give it a go=. 

And for the record And Dash & Python 3.7 was an issue. Not anymore plotly is compiled with 3.7, so when I see python36 plotly and python 3.7, you can do the math from there. I hope it works!
