### ISSUE TITLE
Binder does not resolve dependencies for example notebooks

### ISSUE THREAD

**Issue by antonkulaga** [interpretml/interpret#150]
When I try to run any example notebooks with binder (for isntance https://hub.gke.mybinder.org/user/interpretml-interpret-508omewl/notebooks/examples/python/notebooks/Explaining%20Blackbox%20Classifiers.ipynb ) Binder does not resolve dependencies.

**Comment by paulbkoch** [comment]
I just merged https://github.com/interpretml/interpret/pull/210 into the code, which might fix this issue.  Will leave this issue open until we have verification.

**Comment by paulbkoch** [comment]
Hi @antonkulaga -- I've updated the notebooks to run seamlessly on mybinder.  We now download all the dependencies within the notebooks, if necessary.  I've also added a badge in our README to the glassbox classification notebook from which the other notebooks are also available.

Thank you for reporting this!
