### ISSUE TITLE
conda package for python 3.8

### ISSUE THREAD

**Issue by antonkulaga** [interpretml/interpret#151]
Could you please publish a conda package for python 3.8?

**Comment by interpret-ml** [comment]
Hi @antonkulaga , 

The latest version of interpret is tested and supported on Python 3.8, and published on PyPi which you can access via pip. 

We haven't considered releasing on conda before. Would you mind elaborating on why this might be useful for you?

Thanks,
-InterpretML Team

**Comment by antonkulaga** [comment]
The main use-case is including interpret-ml as dependency in my conda-recipe. Unlike environment.yaml conda recipe does not allowed pip dependencies

**Comment by mikewlange** [comment]
I may be missing something. You can install pip packages in a conda env. 

Load your env and install a package 
> conda activate your_env
> pip install yada-yada

**Comment by markusweimer** [comment]
+1 on the ask for a `conda-forge` package

We are preparing the next runtime for Azure Synapse, and we use `conda` as our environment manager. We'd very much like to include InterpretML in our default environment.

When installing packages for others to use, it is undesirable to mix `conda` and `pip`. For example, InterpretML depends on `shap` which we already install via `conda`. When we try to install InterpretML  in the pip section of the `environment.yml` file, `pip` dutifully install `shap` again. What's worse, it is compiling that version of `shap` not with the toolchain in the environment, but with the system one.

**Comment by interpret-ml** [comment]
Hi @antonkulaga and @markusweimer, 

Thanks for checking in on this and explaining a bit further for us. We made a first pass of a conda version of the package:

interpret: https://anaconda.org/interpretml/interpret
interpret-core: https://anaconda.org/interpretml/interpret-core

`interpret-core` contains the code but no strict dependencies (only constraints). However, the top level `interpret` brings in all of interpret's dependencies (just like on PyPI). If you're going to take a dependency on `interpret`, make sure `conda-forge` is one of your available channels as some interpret dependencies like lime are only listed on there. 

Right now, our two packages are hosted on our own "interpretml" anaconda channel, and can be installed with: `conda install -c interpretml interpret-core`. We were wondering how important it is to be on `conda-forge`, or is having our own channel acceptable for your use cases?

-InterpretML Team

**Comment by markusweimer** [comment]
First of all: Thank you! This really simplifies our deployments.

I will check with the team on the conda-forge question and will report back here when we have an answer.

**Comment by markusweimer** [comment]
I checked and it doesn't seem to make a difference for us. We will have `conda-forge` in the list of channels above `interpret`, just in case you decide to move the package there.

**Comment by mikewlange** [comment]
Hi!! Not to sound like an ass, but you gotta be able to use pip / Conda packages together or you're really missing the big picture. Understand the environment you're using to make forecasts using machine learning. 

ML, for the most part, is a bottom up technology. Not to mention, the need to learn how to work with Python environments.   

Shit, start a new https://colab.research.google.com/ project an install interpretml - >pip install interpret. Disco. 

Don't rely on the software (and it's distribution) to solve everything to make you look good. Learn it (it's all python) - then integrate your solution. 

I appreciate that @interpret-ml is trying to help with Conda - i guess they are bored, love those folks, but you gotta get it on  - on your own. 

The source is right here, don't ask for more? Make it work! It's bizarrely ironic to ask dev's of an open source ML system that is made to be transparent to do more for you specifically? Right? 

Keep rocking. If you have specific implementation issues after install, post them here. I'll get back to you. But don't ask to integrate this brilliant source code (and UI goodness) for your specific purpose. Learn how to use it!!! 

xoxoxo

**Comment by antonkulaga** [comment]
Micromamba cannot properly work with pip yet

**Comment by Hoeze** [comment]
@interpret-ml Would you mind reconsidering conda support?
Usually, it's as simple as having a conda-smithy repo that pulls PyPI packages and publishes them on conda-forge.

Having no conda support is annoying because pip does not care about proper dependency resolution.
Beside of missing docs, it's non-existent conda packages that prevent me from using software in production.

@mikewlange Telling people "Go find out yourself how to install my software" is not a good habit :wink:

**Comment by markusweimer** [comment]
@Hoeze, there are `conda` packages now that we use. See the response above.

**Comment by paulbkoch** [comment]
We now have a conda-forge package.  Install with:
```
conda install -c conda-forge interpret
```
