### ISSUE TITLE
cannot import TabularExplainer from interpret.ext.blackbox

### ISSUE THREAD

**Issue by arbitor1999** [interpretml/interpret#152]
Help!!!! Just cannot import TabularExplainer from interpret.ext.blackbox. My interpret version is 0.2.1. Not know if that is the reason?
![image](https://user-images.githubusercontent.com/59723783/89726026-8dd0e700-da48-11ea-921f-f0b1dac47544.png)
I copy the code from a Microsoft tutorial...
![image](https://user-images.githubusercontent.com/59723783/89726051-cec8fb80-da48-11ea-8d4e-e7c0a401cf2b.png)

**Comment by interpret-ml** [comment]
Hi @arbitor1999 , 

Looks like Ilya was able to push out a hotfix for this (see: https://github.com/interpretml/interpret-community/issues/298#issuecomment-673719829). Closing for now, but we will continue to track this on the interpret-community issue. 

Thanks,
-InterpretML Team
