### ISSUE TITLE
show(ebm_global) not working on sagemaker notebook

### ISSUE THREAD

**Issue by ms8909** [interpretml/interpret#155]
I am getting an error when I run show(ebm_global) in sagemaker notebook. Please help.

**Comment by interpret-ml** [comment]
Hi @ms8909 , 

Thanks for reporting this. Would you mind running this code at the top of your notebook:

```python3
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

and seeing if visualizations start to work in your SageMaker notebook? 

Thanks, 
-InterpretML Team

**Comment by interpret-ml** [comment]
Hopefully the above resolves your question.  Closing the issue for now, but feel free to reopen if you still have concerns.
