### ISSUE TITLE
Interpreting prediction labels for EBM's classification model

### ISSUE THREAD

**Issue by ShrutiVekariya** [interpretml/interpret#163]
I am using EBM's classification model for my use case. For local explanations, I get labels in the following format: 
  `Predicted(0): 0.951 Actual(0): 0.951`
What does the probability score for Actual represent? Is it a bug or there is some other way to read it?

**Comment by mikewlange** [comment]
At face value, that's a pretty accurate prediction vs. the actual representation. Would have to see your code and data myself to say anything of value to analyze a discrepancy between the two numbers.

**Comment by ShrutiVekariya** [comment]
@mikewlange Thank you for your response!
So it shows same probability values for all the data points when the class is same for actual and predicted. When the class is different, it is in this form
` Predicted(0): 0.783 Actual(1): 0.217`
Shouldn't the probability score for actual always be 1 for the correct class?

**Comment by mikewlange** [comment]
Hi @ShrutiVekariya You make a good point. I just re-read your original question, and do not have an answer. I simply do not know. Best of luck!!

**Comment by interpret-ml** [comment]
Hi @ShrutiVekariya, 

Thanks for bringing this up. We intended for the right side to show the true class and its predicted probability from the model, but this has become too confusing (especially when the model makes a correct prediction). We'll update this string to be more clear in a future release. 

@mikewlange -- It always makes our day to see your name pop up :).

-InterpretML Team

**Comment by mikewlange** [comment]
My friends at @interpret-ml, thanks so much for the kind works, that made my day and you make me smile as well. 

I have a job where i'm not doing much machine learning, I'm developing native mobile apps - go figure lol, so I've really been out of the loop. I miss it! Though I feel it's time to get back in, even if it's in my free time. All the best and keep cranking out your awesomeness of a program. 

Cheers, 
- Mike

**Comment by ShrutiVekariya** [comment]
Hi @interpret-ml, thank you for your response!
