### ISSUE TITLE
Question on kernel.py of SHAP package

### ISSUE THREAD

**Issue by roye10** [interpretml/interpret#165]
First of all, the package is great! I only have a few technical questions with regards to the kernel.py code of the [SHAP package](https://github.com/slundberg/shap)

I am trying to understand how SHAP values are computed by the Kernel SHAP method from the SHAP package. As I understand it, you solve a weighted linear regression to attain SHAP values, using `phi = ((X'WX)^-1)X'Wy`.

At a high level, wha I gather so far - especially looking at lines `296-343`, in combination with the referenced functions:
- nsamples determines how many permutations out of the `M!` possible feature orderings are regarded
- (nsamples X number of background samples (size N))-number of y-values are computed, whereby each N-sized set is the result of a different feature ordering (i.e. different features "switched on/off") for each row of background samples (size N) and the empirical mean is taken for each of the N-sized sets, producing nsamples empirical means
- a diff-in-diff is calculated, to match feature contributions to individual features ( `E[y|X_s] - f_null ) - maskMatrix*( f_x - f_null`)
- then a WLS is solved, providing the SHAP values

Did I understand this correctly?

If so, there are a few things, however, I would like to ask:
- if the feature space is fairly large (say 100+), since nsamples restricts variety of feature permutations computed and since the feature permutations are regarded in a sequential manner, (i.e. first only subsets of size 1, 2, ...), does this not disregard interaction effects between features? Even though this is partially accounted for as I understand by
>"add random samples from what is left of the subset space"

Because even for 47 features onwards, if I understand it correctly, only subsets of size 1 (and its complement) are considered fully.
- why is one variable eliminated later on in the solve function?
> "eliminate one variable with the constraint that all features sum to the output"

- what is the intuition behind multiplying the weight vector by 2?

Thank you very much in advance!

**Comment by interpret-ml** [comment]
Hi @roye10, 

Sorry for the delay in getting back to you! @slundberg would be the best person to answer this question. We see that you opened an issue on the SHAP repo as well (https://github.com/slundberg/shap/issues/1488), which might be a better place to track a response. Happy to leave this issue open in the meanwhile. 

-InterpretML Team

**Comment by roye10** [comment]
Hi InterpretML Team,

no worries, thank you for your reply. That is appreciated, thanks! I'll post an update if I get a response or found a response in anyway.

- roye10

**Comment by roye10** [comment]
Think I found an answer to:
> what is the intuition behind multiplying the weight vector by 2?

weight vector multiplied by 2, in order to regain weight for one subsample (before weight vector multiplied by two, to account for the complement subset and such that weight vector (including complement subset) sum to 1)

**Comment by rodrigovssp** [comment]
Em parâmetros de desenvolvimento
