### ISSUE TITLE
Install problem for master branch

### ISSUE THREAD

**Issue by tmontana** [interpretml/interpret#168]
Hi.  Usually this works for other packages but not for interpret (pip using URL from github):  pip install -U git+https://github.com/interpretml/interpret.git

pip install interpret works but I want the latest version.  How may I get it?  Error below.  Thank you

pip install -U git+https://github.com/interpretml/interpret.git
Collecting git+https://github.com/interpretml/interpret.git
  Cloning https://github.com/interpretml/interpret.git to /tmp/pip-req-build-1hw4p7__
    ERROR: Command errored out with exit status 1:
     command: /anaconda/envs/mlj_ebm/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1hw4p7__/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1hw4p7__/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uss57qfl
         cwd: /tmp/pip-req-build-1hw4p7__/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda/envs/mlj_ebm/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-1hw4p7__/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by interpret-ml** [comment]
Hi @tmontana - good question,

Building interpret from source is somewhat tricky due to both C++ and JavaScript compilations. Try running from the root of the repo: `cd scripts && make install`. You'll need access to a C++ compiler and Node.js.
