### ISSUE TITLE
explain_local not working for Logistic Regression from glassbox

### ISSUE THREAD

**Issue by anindya5** [interpretml/interpret#169]
I was trying the code given in the notebooks here - https://nbviewer.jupyter.org/github/interpretml/interpret/blob/master/examples/python/notebooks/Interpretable%20Classification%20Methods.ipynb

Though they worked fine, in the end, I wanted to see if local explainability works for Logistic Regression as well.

Added the following code snippets:-

` lr_local = lr.explain_local(X_test,y_test,name="Logistic Regression")` and variation ` lr_local = lr.explain_local(X_test,y_test)`

Both result in error:-

ValueError: could not convert string to float: ' Self-emp-not-inc'

Not sure if it's a code issue, or it's a syntax issue or local explanation is not there yet for glass box models

**Comment by interpret-ml** [comment]
Hi @anindya5 , 

Logistic regression does support local explanation, but requires its data to be formatted as numeric datatypes before training and evaluating the model (unlike EBM, which can directly operate on strings). In the Jupyter notebook, we create one-hot encoded versions of the dataset for training and evaluating logistic regression: `X_train_enc` and `X_test_enc`.

If you change your code to the following:

```python3
lr_local = lr.explain_local(X_test_enc, y_test, name="Logistic Regression")
show(lr_local)
```

it should work. Please let us know if you have any further issues!

-InterpretML Team
