### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by FabienNugier** [interpretml/interpret#173]
Using DecisionListClassifier() seem to require a package skrules (skope-rules). Maybe it could be added to the dependecies during install.

**Comment by interpret-ml** [comment]
Hi @FabienNugier,

Good catch! In the past, we used to have skope-rules as a required dependency but kept running into issues that would kill the build. That was a while ago, we'll have a look and see if it can be brought back.

**Comment by paulbkoch** [comment]
skope-rules is again a required dependency of interpret
