### ISSUE TITLE
Explantation dashboard not showing on self-hosted JupyterHub

### ISSUE THREAD

**Issue by rene-rex** [interpretml/interpret#174]
I'm using a self-hosted JupyterHub to work on my notebooks. When I use `show` to render the dashboard, the environment is detected as "non-cloud environment". Hence, it tries to connect to localhost (instead of the server) and no dashboard is shown. Is there any way to override this behavior?

**Comment by interpret-ml** [comment]
Hi @rene-rex,

The quickest override would be this code snippet (place this at the top of your notebook):
```python3
from interpret import set_visualize_provider
from interpret.provider.visualize import InlineProvider, JS_URL
set_visualize_provider(InlineProvider(js_url=JS_URL))  # Treats your local notebook like a cloud notebook.
```

As a heads up, our visualization infrastructure uses a CDN (unpkg.com) to host interpret's backing JavaScript bundle in cloud environments. If you're in a very restrictive environment where you can't make network requests, you can drop the `js_url` argument in the last line and it will use a JS bundle that came with the PyPi package install.

Let us know if you run into any more troubles!

**Comment by rene-rex** [comment]
Works perfectly, thanks!
