### ISSUE TITLE
Shape curves

### ISSUE THREAD

**Issue by lrjball** [interpretml/interpret#175]
How do I get access to the shape curves from an EBM? I can see in the readme that a dash can be generated using `show(ebm.explain_global())` which contains the shape curves, but what is the best way to get hold of the underlying data?
Thanks

**Comment by interpret-ml** [comment]
Hi @lrjball, 

Good question! `explain_global()` produces an Explanation object which contains all the relevant underlying data. You can access this through the `.data()` method on these objects:

```python3
ebm_global = ebm.explain_global()
shape_data = ebm_global.data(2)  # Gets data for Shape Curve of feature 2 -- change this input for different features
```

`shape_data` is just a dictionary which contains all the relevant info used for plotting the shape function. In particular, you can extract the x-axis and y-axis data by using the 'names' and 'scores' keys in the dictionary:

 ```python3
x_values = shape_data['names']
y_values = shape_data['scores']
```

Hope this helps, and let us know if you have any further questions!

-InterpretML Team

**Comment by lrjball** [comment]
Amazing, thank you
