### ISSUE TITLE
inner_bags and outer_bags

### ISSUE THREAD

**Issue by hakeemo** [interpretml/interpret#178]
What is the difference between inner_bags and outer_bags in the EBM model?

**Comment by interpret-ml** [comment]
Hi @hakeemo, 

Good question! The EBM algorithm works by boosting decision trees restricted to a single feature at a time to learn each shape function (for full details, please see our [citations section ](https://github.com/interpretml/interpret#citations) on the readme in the Explainable Boosting section). 

`outer_bags` is like wrapping a bagging process around the core algorithm, where individual EBMs are fit on different subsamples of the dataset. If you're familiar with scikit-learn, it's similar to wrapping the basic EBM estimator inside of a [BaggingClassifier](url). The final shape functions produced are an average of the shape functions learned in each outer bag. We use `outer_bags` for many reasons -- determining the size of error bars on each function, adding smoothness to graphs, and adding diversity to the pair selection process if using automated interactions to help find the best ones. In addition, its important to note that the `n_jobs` parameter currently parallelizes the algorithm at the outer bagging level (each process trains one of the bagged EBMs). 

`inner_bags` on the other hand are subsamples drawn with replacement at the time of growing each individual tree in the boosting process. When the algorithm visits a single feature, it creates `inner_bags` number of samples of the data, grows trees on each sample, and averages them together before creating the final update used in the gradient boosting process. While this process can help with predictive performance and intelligibility, it significantly adds to the training time of the algorithm, so it is currently disabled by default. That said, if you can afford a longer training time, it is worth turning on (ex: setting inner_bags >= 10). 

Hope this helps, and please let us know if you have any questions!

-InterpretML Team

**Comment by hakeemo** [comment]
Thanks for the response. This is helpful
