### ISSUE TITLE
Average global explanation graph for k fold cross validation

### ISSUE THREAD

**Issue by aman63** [interpretml/interpret#182]
All of you have done a really great work! I was trying to find out the average global explanation graph for k fold cross validation. Lets suppose, I have a feature x and I have done 3 fold cross validation. So, I should get 3 different global explanation graph for the correlation between output label and feature x for three cross folds. I was wondering if there is any way to find the average of these 3 graphs for the global explanation of feature x? Thank you very much.

**Comment by interpret-ml** [comment]
Hi @aman63 -- We're happy to hear that you're finding the package useful.  It's possible to combine these models by simply averaging the additive_terms_ fields between them.  This won't generate error bars that are correct though, so we recommend setting all the term_standard_deviations_ to zero for now, which will remove the error bars from the graphs.  In our backlog is the ability to combine these models with error bars, but we're currently discarding the information you'd require to do this, so it will require a change to the package.

Here is where we do the model averaging in Interpret:
https://github.com/interpretml/interpret/blob/fb895549b2002d6cc4844446c7d90a5f68e0d61f/python/interpret-core/interpret/glassbox/ebm/ebm.py#L936

-InterpretML Team

**Comment by aman63** [comment]
Thanks a lot

**Comment by paulbkoch** [comment]
As described in https://github.com/interpretml/interpret/issues/372, we now support the merge_ebms utility which also handles error bars.
