### ISSUE TITLE
Error running package OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by Vptel** [interpretml/interpret#186]
Hi, 

I recently installed interpret on my conda environment on windows 10 and get the following error when training an ebm. 

2020-12-01 16:39:55 EBM lib loading.
2020-12-01 16:39:55 Loading native on win32 | debug = False
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-37-eaecdc43e42c> in <module>
      1 ebm = ExplainableBoostingClassifier()
----> 2 ebm.fit(x_train[['Mortgage_Account_Balance','Num_Deposit']][:10000], y_train[:10000])

c:\dev\.conda\envs\jupyter-lab\lib\site-packages\interpret\glassbox\ebm\ebm.py in fit(self, X, y)
    771             random_state=self.random_state,
    772         )
--> 773         self.preprocessor_.fit(X)
    774         X_orig = X
    775         X = self.preprocessor_.transform(X_orig)

c:\dev\.conda\envs\jupyter-lab\lib\site-packages\interpret\glassbox\ebm\ebm.py in fit(self, X)
    169         self.has_fitted_ = False
    170 
--> 171         native = Native.get_native_singleton()
    172         schema = autogen_schema(
    173             X, feature_names=self.feature_names, feature_types=self.feature_types

c:\dev\.conda\envs\jupyter-lab\lib\site-packages\interpret\glassbox\ebm\internal.py in get_native_singleton(is_debug, log_level)
     35             log.info("EBM lib loading.")
     36             native = Native()
---> 37             native._initialize(is_debug=is_debug, log_level=log_level)
     38             Native._native = native
     39         else:

c:\dev\.conda\envs\jupyter-lab\lib\site-packages\interpret\glassbox\ebm\internal.py in _initialize(self, is_debug, log_level)
     25         self.log_level = log_level
     26 
---> 27         self.lib = ct.cdll.LoadLibrary(Native._get_ebm_lib_path(debug=is_debug))
     28         self._harden_function_signatures()
     29         self._set_logging(level=log_level)

c:\dev\.conda\envs\jupyter-lab\lib\ctypes\__init__.py in LoadLibrary(self, name)
    440 
    441     def LoadLibrary(self, name):
--> 442         return self._dlltype(name)
    443 
    444 cdll = LibraryLoader(CDLL)

c:\dev\.conda\envs\jupyter-lab\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 126] The specified module could not be found

Before downloading the interpret did install the libraries in the requirements.txt.

(jupyter-lab) C:\Windows\system32>conda list
# packages in environment at c:\dev\.conda\envs\jupyter-lab:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py37he774522_1
arrow-cpp                 0.15.1           py37h47fa567_6
async_generator           1.10             py37h28b3542_0
attrs                     20.3.0             pyhd3eb1b0_0
backcall                  0.2.0                      py_0
biopython                 1.78             py37he774522_0
blas                      1.0                         mkl
bleach                    3.2.1                      py_0
boost-cpp                 1.67.0               hfa6e2cd_4
brotli                    1.0.9                ha925a31_2
brotli-python             1.0.9            py37h82bb817_2
brotlipy                  0.7.0           py37h2bbff1b_1003
bzip2                     1.0.8                he774522_0
c-ares                    1.17.1               h2bbff1b_0
ca-certificates           2020.10.14                    0    anaconda
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.14.3           py37hcd4344a_2
chardet                   3.0.4           py37haa95532_1003
click                     7.1.2                      py_0
cloudpickle               1.6.0                      py_0
colorama                  0.4.4                      py_0
colour                    0.1.5                    py37_0
cryptography              3.2.1            py37hcd4344a_1
cycler                    0.10.0                   py37_0
cytoolz                   0.11.0           py37he774522_0
dash                      1.17.0             pyhd8ed1ab_0    conda-forge
dash-core-components      1.13.0             pyhd8ed1ab_1    conda-forge
dash-cytoscape            0.2.0                    pypi_0    pypi
dash-html-components      1.1.1              pyh9f0ad1d_0    conda-forge
dash-renderer             1.8.3              pyhd3eb1b0_0
dash-table                4.11.0             pyhd8ed1ab_0    conda-forge
dask-core                 2.30.0                     py_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
dill                      0.3.2                      py_0    anaconda
double-conversion         3.1.5                ha925a31_1
entrypoints               0.3                      py37_0
fastparquet               0.4.1            py37h2a96729_0
flask                     1.1.2                      py_0
flask-compress            1.8.0              pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
future                    0.18.2                   py37_1
gevent                    20.9.0           py37he774522_0
gflags                    2.2.2                ha925a31_0
glog                      0.4.0                h33f27b4_0
greenlet                  0.4.17           py37he774522_0
grpc-cpp                  1.26.0               h351948d_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2020.2                      254
interpret                 0.2.2                    pypi_0    pypi
interpret-core            0.2.2                    pypi_0    pypi
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.19.0           py37hd4e2768_0
ipython_genutils          0.2.0                    py37_0
itsdangerous              1.1.0                    py37_0
jedi                      0.17.2                   py37_0
jinja2                    2.11.2                     py_0
joblib                    0.14.1                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter_client            6.1.7                      py_0
jupyter_core              4.7.0            py37haa95532_0
jupyterlab                2.2.6                      py_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         1.2.0                      py_0
kiwisolver                1.3.0            py37hd77b12b_0
libboost                  1.67.0               hfd51bdf_4
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.11.2               h7bd577a_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.1.0                h56a325e_0
lime                      0.2.0.1            pyh9f0ad1d_0    conda-forge
llvmlite                  0.34.0           py37h1a82afc_4
lz4-c                     1.8.1.2              h2fa13f4_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.3.2                         0
matplotlib-base           3.3.2            py37hba9282a_0
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.2                      256
mkl-service               2.3.0            py37h2bbff1b_0
mkl_fft                   1.2.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
msys2-conda-epoch         20160418                      1
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.0.8                      py_0
nest-asyncio              1.4.3              pyhd3eb1b0_0
networkx                  2.5                        py_0
notebook                  6.1.4                    py37_0
numba                     0.51.2           py37hf9181ef_1
numpy                     1.19.2           py37hadc3359_0
numpy-base                1.19.2           py37ha3acd2a_0
olefile                   0.46                     py37_0
openssl                   1.1.1h               he774522_0    anaconda
packaging                 20.4                       py_0
pandas                    1.1.3            py37ha925a31_0
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.3            py37haa95532_1
parso                     0.7.0                      py_0
pickleshare               0.7.5                 py37_1001
pillow                    8.0.1            py37h4fa10fc_0
pip                       20.2.4           py37haa95532_0
plotly                    4.12.0             pyhd3eb1b0_0
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.8                      py_0
psutil                    5.7.2            py37he774522_0
pyarrow                   0.15.1           py37h47e9c7a_0
pycparser                 2.20                       py_2
pygments                  2.7.2              pyhd3eb1b0_0
pyopenssl                 19.1.0             pyhd3eb1b0_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.17.3           py37he774522_0
pysocks                   1.7.1                    py37_1
python                    3.7.5                h8c8aaf0_0
python-dateutil           2.8.1                      py_0
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                     py_0
pywavelets                1.1.1            py37he774522_2
pywin32                   227              py37he774522_1
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.2           py37ha925a31_1
qt                        5.9.7            vc14h73c81de_0
re2                       2019.08.01       vc14ha925a31_0
requests                  2.24.0                     py_0
retrying                  1.3.3                    py37_2
salib                     1.3.11                     py_0    conda-forge
scikit-image              0.17.2           py37h1e1f486_0
scikit-learn              0.22.1           py37h6288b17_0
scipy                     1.4.1            py37h9439919_0
seaborn                   0.11.0                     py_0
send2trash                1.5.0                    py37_0
setuptools                50.3.1           py37haa95532_1
shap                      0.36.0           py37h414f9d2_0    conda-forge
sip                       4.19.8           py37h6538335_0
six                       1.15.0           py37haa95532_0
skope-rules               1.0.1                    pypi_0    pypi
slicer                    0.0.3                      py_0    conda-forge
snappy                    1.1.8                h33f27b4_0
sqlite                    3.33.0               h2a8f88b_0
terminado                 0.9.1                    py37_0
testpath                  0.4.4                      py_0
thrift                    0.11.0           py37h6538335_0
thrift-cpp                0.11.0               h1ebf3fd_3
tifffile                  2020.10.1        py37h8c2d366_2
tk                        8.6.10               he774522_0
toolz                     0.11.1                     py_0
tornado                   6.0.4            py37he774522_1
tqdm                      4.51.0             pyhd3eb1b0_0
traitlets                 5.0.5                      py_0
treeinterpreter           0.2.2                    pypi_0    pypi
uriparser                 0.9.3                h33f27b4_1
urllib3                   1.25.11                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.1                      py_0
wheel                     0.35.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zeromq                    4.3.2                ha925a31_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py37_1
zope.event                4.5.0                    py37_0
zope.interface            5.1.2            py37he774522_0
zstd                      1.3.7                h508b16e_0

any thought on what i'm doing wrong?

**Comment by interpret-ml** [comment]
Hi @Vptel --

When you installed interpret, did you get it from github or pypi?  Installing from pypi is easier since the native binaries are included in that installation.  If installing from source on github, you would need to run "make install" as described in issue https://github.com/interpretml/interpret/issues/168

-InterpretML team

**Comment by interpret-ml** [comment]
Hope the above info helped! Closing for now, but please feel free to comment and re-open if this is still an issue. 

-InterpretML Team
