### ISSUE TITLE
Score curve of a numerical and sparse feature exhibits a step-like behaviour 

### ISSUE THREAD

**Issue by Heringer-Epson** [interpretml/interpret#187]
Hi devs,

I am training a EBM model on a relative large dataset (>50 features and 10M rows). While the output score curve is well behaved for most of these features, I have noticed a weird behaviour for a couple of features that are continuous but assume only a few sparse values (see image below). Is this a known/expected effect? Is there a way to fix/improve this curve? Thank you.

<img width="696" alt="score" src="https://user-images.githubusercontent.com/16964426/102640767-fb90cc00-4128-11eb-8b22-d745d1eafe50.png">

**Comment by interpret-ml** [comment]
Hi @Heringer-Epson, 

What an interesting graph! We've noticed this type of pattern before when there are exclusively positive examples in regions of the feature space. While you can edit the models after training, we'd recommend investigating these regions in your data first. For example, you might consider checking datapoints where the feature value is between 6.5 and 9, and calculate the % of positive labels for those datapoints. 

You can use the built-in data exploration utilities in interpret to help with this:

```python3
from interpret import show
from interpret.data import ClassHistogram

hist = ClassHistogram().explain_data(X, y)
show(hist)
```

Sometimes behavior like this on graphs is a result of data leakage introduced through preprocessing or earlier steps in the pipeline. A log odds score of +6 is quite strong, and suggests that the model is very confident about a predicting a positive label in these regions. 

Hope this helps! Please let us know if this helps you resolve the issue. If there's nothing abnormal in your data, then we'd also be happy to investigate further with you. 

-InterpretML Team

**Comment by Heringer-Epson** [comment]
Thank you for your speedy response. I will take some time to investigate the potential issues you have raised and I will update this thread once I am finished.

**Comment by Heringer-Epson** [comment]
Very interesting indeed. As suggested, the data did contain feature values for which all the labels were positive. The issue was actually caused by SMOTE, which was used to alleviate a class imbalance problem in the original dataset. Many of the synthetic data points created by oversampling the minority class had feature values that did not exist before. For all of these new values, the labels were positive, leading to the issue with the score curve. Below is a screenshot of a mock example that illustrates this issue. The score curve was like the one above if SMOTE was used and it was normal if SMOTE was not used.

I have a few follow-up questions in this regard, but I will create a new issue/question for it because this one has been addressed and solved.
<img width="955" alt="smote" src="https://user-images.githubusercontent.com/16964426/102918214-81c44f80-4454-11eb-8d54-9904dad92610.png">
