### ISSUE TITLE
Question: how to produce learning (cost) curves?

### ISSUE THREAD

**Issue by Heringer-Epson** [interpretml/interpret#189]
Hi interpretML team,

My apologies for asking yet another question. I am having a hard time finding how to produce learning curves (training and validation sets) for e.g. a classification EBM model I am training. Could someone kindly point me to an example where this is shown or provide a code snippet. My goal is simply to inspect whether or not the model is overfitting to the training sample.

All the best and happy new year,
Epson

**Comment by interpret-ml** [comment]
Hi @Heringer-Epson --

Our package currently doesn't log real time metrics on training and validation, so you wouldn't be able to produce learning curves with the published package.  This is something on our longer term backlog, but we don't yet have a timeline on when we will solve it.  In the meantime, a simple sanity check might be to evaluate your EBM separately on the training and validation sets and compare the two metrics.  Also, examining your global EBM graphs can indicate overfitting if you notice extreme scores in some regions of the graphs.

-InterpretML

**Comment by Heringer-Epson** [comment]
That makes sense, thank you again. Closing the issue.
