### ISSUE TITLE
Azure synapse notebook compatible?

### ISSUE THREAD

**Issue by cvidden** [interpretml/interpret#200]
Hello, 

I am running interpret (interpret==0.2.4) on an Azure synapse notebook, but the show() command generates the following output with no graphics generated. 

![image](https://user-images.githubusercontent.com/50586750/105941413-017ca580-6023-11eb-96f9-3fbb94602962.png)

Is interpret compatible in this case?

Thanks,
Chad

**Comment by interpret-ml** [comment]
Hi Chad, 

Thanks for bringing this up! If you visit the URL posted in the printed output ("http://127.0.0.1:7001/..."), you should see the visualization output from `show()`, which is hosted on a local port. We normally inject these directly into the notebooks, but it seems like this functionality isn't working on Synapse. 

In the meanwhile, you can try using the InlineProvider to directly embed visualizations in your notebook, which doesn't require spinning up a web server on a separate port. To do this, just put the following at the top of your notebook:

``` python
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

Hopefully this workaround solves your problem! We'll leave this open until we natively resolve the issue in Synapse notebooks. 

Thanks,
-InterpretML Team
