### ISSUE TITLE
User Document for InterpretML

### ISSUE THREAD

**Issue by ncut564227621** [interpretml/interpret#201]
I‘m a new user。if have document of InterpertML it will beiawesome!

**Comment by interpret-ml** [comment]
Hi @ncut564227621, 

Thanks for the suggestion! We currently have docstrings for all of our major methods in the code (ex: https://github.com/interpretml/interpret/blob/develop/python/interpret-core/interpret/glassbox/ebm/ebm.py#L1415), and these should auto-complete in most IDEs to help you pick parameters. 

That said, we agree that more formal documentation would be nice, and while we don't have a concrete roadmap for it, it is on our backlog. We'll leave this open and update this issue when we have made progress.

Thanks!
-InterpretML Team

**Comment by willingc** [comment]
@interpret-ml If you haven't yet seen the [Executable Book Project](https://executablebooks.org/en/latest/), you may find these tools helpful for documentation around the existing notebooks in this repo. You could also autodoc to make the docstrings viewable outside of an IDE. Here's a [gallery of others using the project](https://executablebooks.org/en/latest/gallery.html).

**Comment by interpret-ml** [comment]
Hi @willingc, 

Thank you very much for pointing us towards the Executable Book Project -- this looks fantastic! We've been talking about how to highlight unique ways interpretability can help in standard machine learning scenarios (ex: detecting data leakage, highlighting model bias, showing effects of preprocessing, etc.). The notebook-first documentation format looks like an excellent vehicle for storytelling without depending on nbviewer/Github's Jupyter renderer, and it's great that it can also host general documentation too. Really appreciate the heads up!

-InterpretML Team

**Comment by interpret-ml** [comment]
We've got official documentation now at https://interpret.ml/docs/. The EBM documentation is here: https://interpret.ml/docs/ebm.html# and includes API docs as well. Feel free to check it out and let us know what you think!

-InterpretML Team
