### ISSUE TITLE
There is no sdist published at https://pypi.org/project/interpret/#files 

### ISSUE THREAD

**Issue by shaileshj2803** [interpretml/interpret#219]
Great library and awesome work. we are looking forward to integrate this library but to do the deployment in our platform we need the sdist to be published at pypi. Is it possible to do so easily?

**Comment by interpret-ml** [comment]
We just recently published `interpret` and `interpret-core` (latter is used for when you select the exact dependencies you need for production) on conda. It's at `https://anaconda.org/interpretml/interpret`. Would that suffice?

If you still need sdist specifically, it's possible and we can look into it, just not sure how long it will take to work. It's somewhat tricky as we take full advantage of each C++ compiler per OS as well as JavaScript bundling for the visualization layer.

**Comment by shaileshj2803** [comment]
Have a sdist would be better. If you can put it in a backlog that will really help us.

**Comment by paulbkoch** [comment]
We're now publishing sdists.
