### ISSUE TITLE
I cannot find the documentation

### ISSUE THREAD

**Issue by Hoeze** [interpretml/interpret#221]
Hi, I'm sorry for the stupid question, but where can I find the documentation to this project?
Is there some read-the-docs, etc.?
I just cannot find it :no_mouth:

**Comment by elsharifali** [comment]
Does this help?
https://interpret.ml

**Comment by Hoeze** [comment]
Thanks @elsharifali :+1: 
The links you posted provide some example notebooks but I'm searching explicitly for the API docs :slightly_smiling_face:

**Comment by onacrame** [comment]
Same here.  I believe this has the potential to be a core library in the ML toolbox.  I assume documentation is in the works.  

For me the inference speed is the biggest selling point.  We are building an HPC application that utilises LightGBM for inference.  EBM would be a huge cost savings in terms of computational time.  Still being in an alpha stage with little documentation would be my biggest corporate blocker internally with adoption

**Comment by Hoeze** [comment]
[@interpret-ml](https://github.com/interpretml/interpret/issues/151#issuecomment-857071771) just pointed me here:
https://interpret.ml/docs/

Thanks @interpret-ml!
