### ISSUE TITLE
EBM for Causal Effect

### ISSUE THREAD

**Issue by shaileshj2803** [interpretml/interpret#228]
I am planning to get insights from Data set using EBM. Can I use EBM to compare time periods and find the contributions for change?

**Comment by interpret-ml** [comment]
Hi @shaileshj2803, 

Interesting idea! If we're understanding your question correctly, you'd like to use EBMs to compare multiple time periods' worth of data (ex: previous month data vs. current month). This should be possible if your data can be framed as a Classification or Regression task (i.e. if your data has a well-established "target" feature). In our experience, training separate EBMs on different time periods' worth of data and comparing the learned feature importances has yielded interesting results about data drift. 

This type of analysis most likely wouldn't be considered "Causal", and wouldn't tell you everything about the shift in data distributions (ex: if a useless feature shifted significantly in a way that still doesn't effect predictions, the EBM graphs would likely not highlight these changes). 

A quick way to try this would be to use the dashboard in InterpretML to compare different EBM models:

```python3

from interpret.glassbox import ExplainableBoostingClassifier

# Assume two datasets, prev_month for previous month's data and curr_month for current data
ebm_prev = ExplainableBoostingClassifier()
ebm_prev.fit(prev_month_X, prev_month_y)
ebm_prev_global = ebm_prev.explain_global()

ebm_curr = ExplainableBoostingClassifier()
ebm_curr.fit(curr_month_X, curr_month_y)
ebm_curr_global = ebm_curr.explain_global()

show([ebm_prev_global, ebm_curr_global])
```

In the "global" tab, you'll be able to select individual features and compare the learned shape functions side by side. You can also programmatically compare the learned features by comparing the `.additive_terms_` properties of both EBMs and checking for significant differences. Let us know if you have any further questions!

-InterpretML Team
