### ISSUE TITLE
'ExplainableBoostingClassifier' object has no attribute 'feature_groups_' 

### ISSUE THREAD

**Issue by Vptel** [interpretml/interpret#230]
Hi,

I recently tried to score my model and build the explainable global wrapper but keep getting the error AttributeError: 'ExplainableBoostingClassifier' object has no attribute 'feature_groups_'.

Is anyone able to help me understand this issue?

![image](https://user-images.githubusercontent.com/18105503/117321894-6dbe3f00-ae85-11eb-8c3c-bafc565efd9e.png)

![image](https://user-images.githubusercontent.com/18105503/117321934-74e54d00-ae85-11eb-8062-fc1db3641aaf.png)

**Comment by interpret-ml** [comment]
Hi @Vptel, 

Are you fitting this inside a scikit-learn pipeline? The attribute "feature_groups_" is only created during the `.fit()` call, and `explain_global` in general will only work on fitted models. 

For some reason, it looks like your pipeline hasn't run the fit method on the internal ExplainableBoostingClassifier object. When I access a pipeline through `.steps`, I'm able to extract a fitted estimator and also call `explain_global()` -- here's the code I'm testing with:

```python3

from interpret.glassbox import ExplainableBoostingRegressor
from sklearn.datasets import load_boston
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA # Just for demo -- don't use PCA before EBMs in real code :)

bos = load_boston()
estimators = [('reduce_dim', PCA()), ('clf', ExplainableBoostingRegressor())]
pipe = Pipeline(estimators)
pipe.fit(bos.data, bos.target)

# Extract EBM
ebm = pipe.steps[1][1]
ebm.explain_global() # Works fine
ebm.has_fitted_ # Returns True
```

Any chance you can share some extra sample code with us (around how the pipeline is constructed or being fit)? Being able to reproduce this on our side would help us debug this faster. 

Thanks!
-InterpretML Team

**Comment by Vptel** [comment]
Hi, I've managed to figure it out. My interpretML models were trained on version 0.1.21 but my conda environment was using version 0.2.4 where variable names had changed. I downgraded and got it working. 

Thanks for helping tho!
