### ISSUE TITLE
Opening the Glassboxes

### ISSUE THREAD

**Issue by mrektor** [interpretml/interpret#231]
Hi everybody,

I really like this package, but I was wondering if the details of the glass boxes methods could be inspected more closely.
For example, it would be great to have in some form access to the different shape functions of EBM in a programmatic way, and not just with the plotting interface.

That would be interesting for a variety of reasons, from comparing directly different curves, to automating different kind of analysis.

It is possible to do that? I tried to play a bit with that but is not really obvious to me how to do it...

**Comment by interpret-ml** [comment]
Hi @mrektor, 

Good question! The global explanation objects passed into the `show` function also expose a method for directly accessing the underlying model information.  You can access all the data necessary to generate our plots through the `.data()` method on the Explanation objects:

```python3
ebm_global = ebm.explain_global()
shape_data = ebm_global.data(2)  # Gets data for Shape Curve of feature 2 -- change this input for different features
```

`shape_data` is just a dictionary which contains all the relevant info used for plotting the shape function. In particular, you can extract the x-axis and y-axis data by using the 'names' and 'scores' keys in the dictionary:

 ```python3
x_values = shape_data['names']
y_values = shape_data['scores']
```

Hope this helps, and let us know if you have any further questions!

-InterpretML Team

**Comment by mrektor** [comment]
Thank you! That's what I was looking for!
