### ISSUE TITLE
Is there any plan to update the relevant R library 'interpret' in the near future

### ISSUE THREAD

**Issue by flippercy** [interpretml/interpret#238]
Hi @interpret-ml:

Is there any plan to update the relevant R library 'interpret' in the near future, please? Its main function ebm.classify() misses some key components such as n_jobs.

Best Regards,

**Comment by interpret-ml** [comment]
Hi @flippercy, 

The Python codebase is definitely more up to date and functional at the moment, and we recommend using if possible. That said, we do intend to revamp the R library and eventually bring it to parity with the Python code. We're trying to approach this by moving logic heavy portions of the Python code into shared layers (C++/JavaScript), which will eventually make it simpler to bring the R implementation up to speed. Unfortunately, there's a lot of significant Python code (including joblib for the n_jobs style parallelization) which makes this a relatively slow process. We can't offer hard timelines on updates for the R library at the moment, but we'll update this issue when we make significant progress.

-InterpretML Team

**Comment by flippercy** [comment]
@interpret-ml Thank you for the updates!
