### ISSUE TITLE
How to run pytest locally?

### ISSUE THREAD

**Issue by xiaohk** [interpretml/interpret#241]
Hello, I am wondering how I can run the azure test pipeline locally?

https://github.com/interpretml/interpret/blob/93075fcbe0225709fa72e6ddb89f0e4c875415c6/azure-pipelines.yml#L340-L350

For example, I have made some changes to `ebm.py`, how can I run its corresponding [test scripts](https://github.com/interpretml/interpret/tree/develop/python/interpret-core/interpret/glassbox/ebm/test)? I tried to run `python -m pytest` from `python/interpret-core` (as described in the azure pipeline), but it gives an error `No module named pytest`. Should I install `pytest`?

**Comment by interpret-ml** [comment]
Hi @xiaohk,

The `python -m pytest` looks correct. Try running `pip install interpret[testing]` in your environment. It should install the dependencies needed to run our test suites. If that doesn't work, let us know.

**Comment by xiaohk** [comment]
Got it, thanks!

I installed `interpret` from local files with zsh. Running `pip install -e.\[testing\]` within `interpret/python/interpret-core` works for me! I am now able to run `python -m pytest ./interpret-core/interpret/glassbox/ebm/test`. 👍
