### ISSUE TITLE
speed up ebm training time in databricks enviornment

### ISSUE THREAD

**Issue by SoulEvill** [interpretml/interpret#243]
I love interpret ebm package and it is very easy to use and interpret the data but I do find the training time is really long and not sure if there is any tricks to speed things up. so here is my scenario: 

I am running the ebm binary classification model on the databricks environment with 230 features,  about half-million rows,  and with model parameters - n_estimators = 10 and n_jobs = -1 (it is quite old ebm version) everything else are default parameters. With the most powerful instance I was able to find on databricks - (r5a.24xlarge with 96 Cores and 768GB memory), the training time took more than 8 hours and I am wondering if there is anything I could do to improve the training speed. I am seeing the cpu and memory usage are actually quite low and not sure if parallel training is running properly on databricks. or can we leverage spark to speed things up in this case? 

any help would be really really appreciated!

**Comment by interpret-ml** [comment]
Hi @SoulEvill -- If you can update to the latest version of Interpret, that should give you about a 2x speedup on classification problems.  You'd only get this speed improvement though if you kept your interactions parameter the same.  On older versions of Interpret the interactions parameter was set to 0, but in the latest release we increased it to 10.

In terms of your current setup, we currently bag the GAM generation process, which is controlled by the "outer_bags" parameter.  The outer bags are parallelized, so when that parameter is set to the current default of 8 we can efficiently use 8 real cores.  Most cloud providers have been calling hyperthreads as "cores", so in reality you want to allocate twice the number of cores as your "outer_bags" parameter.  Beyond 16 cores, you currently get no further benefit by adding more.

In terms of future development, there are still a lot of tricks available to us for improving training time, unfortunately all the easy ones have already been implemented and what remains are the most difficult ones.  The next speed improvement should be the transition to using SIMD/AVX512 instructions, which will probably give us close to a 16x speedup.  This change is not imminent, but we are making internal changes that are getting us closer to the goal.  A GPU implementation is also in the works, but again we don't have a timeline yet regarding completion.  Stay tuned.

-InterpretML team

**Comment by SoulEvill** [comment]
thank you for quick reply!! I am so grateful!! I will try to upgrade to latest version and can't wait to see these new version coming out!
