### ISSUE TITLE
Interpretation of scores

### ISSUE THREAD

**Issue by drskd** [interpretml/interpret#250]
Hi,

First of all, thanks a lot with all the work you put into the package. It is really useful to have a precise model with a clear interpretation.

About the interpretation, I have two questions on the ExplainableBoostingRegressor:

- In a global explanation, how is computed the score (or importance I guess) of each feature. I access to it via the following code: 
`ebm_global.data(None)['scores']` . 
Are these the weights that are used when summing each feature function?

- In a global explanation when selecting a specific feature, how is computed the score? I have seen in #21 that it should be interpreted in the unit of the target that we predict. However when I sum up all the values, it does not seem to add up to the correct range of values by far. Again I acces to these information via the following code: 
`ebm_global.data(i)['scores']`

Thanks again for this package, I am looking forward to reading your explanations!

**Comment by interpret-ml** [comment]
Hi @drskd, 

Good questions! In general, you should think of each of the shape functions as look-up tables of contributions for each feature. I'll use the california housing price dataset as a reference for answering your questions. Here's how to train the model:

```python3
from sklearn.datasets import fetch_california_housing
from interpret.glassbox import ExplainableBoostingRegressor

cal = fetch_california_housing()

ebm = ExplainableBoostingRegressor(feature_names=cal.feature_names)
ebm.fit(cal.data, cal.target)
```

Let's take a look at the graph of the first feature, MedInc:

```python3
from interpret import show
show(ebm.explain_global())
```

![image](https://user-images.githubusercontent.com/50031429/121264820-c4080e80-c885-11eb-95e7-1f54fdf90acb.png)

The way to interpret this is that if a new datapoint came in with MedInc = 10, the model adds about +2 to their final prediction. However, for a different datapoint with MedInc = 4, the model would now adds ~+0 to the prediction, and for datapoints that have MedInc = 2, the model adds approx -0.5. 

To make individual predictions, the model uses each feature graph as a look up table, notes the contribution per feature, and sums them together with the learned intercept (found at `ebm.intercept_`) to make a prediction. 

You can see the full breakdown for any individual prediction by using the `explain_local` function. Here's the prediction breakdown for the first sample in the cal housing dataset:

```python3
from interpret import show
show(ebm.explain_local(cal.data[:10], cal.target[:10]))
```
![image](https://user-images.githubusercontent.com/50031429/121265204-67f1ba00-c886-11eb-9898-2b02d5ebd29f.png)

The model prediction is 3.95. We can see that the intercept adds a +2, MedInc adds +1.7, and the Longitude adds about a +0.4. So far, for the top 3 contributing terms, we're at a cumulative prediction of +4.1. If you repeat this process for all the features, you'll arrive exactly at the model prediction of +3.95. 

Finally, to answer your first question: the overall feature importance is calculated as the average absolute contribution a feature makes when predicting across the training dataset. In our example above, we saw that MedInc contributed a +1.7 for this datapoint. If we repeat this process for all datapoints in the training set, `np.mean(np.abs(feature_contribution))`, we'll arrive at the overall feature importance. This can be interpreted as: _what is the average contribution this feature makes to a prediction on the training set?_

Hope this helps, and let us know if you need any further clarification!

-InterpretML Team

**Comment by drskd** [comment]
Thanks for the clarification, all makes sense now. I actually forgot to integrate the intercept when trying to reconstruct the prediction!

All the best,
drskd

**Comment by Jingyan918** [comment]
Hi @interpret-ml,

Thanks for the detailed explanation above.
I am confused because I am now on a classification task but adding every features up does not equal to the PrScore and AcScore generated.
Could you please demonstrate an explanation like the one you did above, but for classification task? Would really appreciate if you can do this.

Thanks.
