### ISSUE TITLE
How to test ebm classifier?

### ISSUE THREAD

**Issue by elcolie** [interpretml/interpret#255]
How to test ebm classification?

**Comment by elcolie** [comment]
Found it
In [page](https://interpret.ml/docs/getting-started.html)
```
ebm_local = ebm.explain_local(X_test[:5], y_test[:5])
show(ebm_local)
```

Then check the prediction with
```
ebm_local.selector
```

Predicted | PrScore | Actual | AcScore | Resid | AbsResid
-- | -- | -- | -- | -- | --
0 | 0.991 | 0 | 0.991 | 0.0 | 0.0
0 | 1.000 | 0 | 1.000 | 0.0 | 0.0
1 | 0.934 | 1 | 0.934 | 0.0 | 0.0
0 | 0.664 | 0 | 0.664 | 0.0 | 0.0
0 | 0.997 | 0 | 0.997 | 0.0 | 0.0

**Comment by Jingyan918** [comment]
Hi there! Could you please explain the results of the output? I am doing classification as well. However, I did not get the idea of the predicted score and actual score. I did realize that when the predicted output is correct, the PrScore is exactly the sum of every features added up, as shown in the local explanation. But when the predicted output is wrong, how did the algorithm generate the PrScore and what does it mean? 

Thanks.

**Comment by Jingyan918** [comment]
Hi there! Could you please explain the results of the output? I am doing classification as well. However, I did not get the idea of the predicted score and actual score. There is an explanation on regression on thread #250 but I did not get the local explanations for classification.

Thanks.
