### ISSUE TITLE
How to get feature name in local_explain()?

### ISSUE THREAD

**Issue by elcolie** [interpretml/interpret#256]
In the document
![image](https://user-images.githubusercontent.com/18206728/123374268-0aad7680-d5b1-11eb-9118-8257c44f3138.png)

In my program
![image](https://user-images.githubusercontent.com/18206728/123374346-2fa1e980-d5b1-11eb-99c1-e49a50782aa9.png)

My `X_test` is `Pandas.DataFrame` with columns
```
Index(['welltest_liquid', 'welltest_gas', 'welltest_lift_gas',
       'prod_press_trend_FLATLINE', 'prod_press_trend_ACTIVE',
       'prod_temp_trend_FLATLINE', 'prod_temp_trend_ACTIVE',
       'dh_gauge_press_trend_FLATLINE', 'dh_gauge_press_trend_ACTIVE',
       'dh_gauge_temp_trend_FLATLINE', 'dh_gauge_temp_trend_ACTIVE',
       'produce_dp_NO_DP', 'produce_dp_HAS_DP', 'inject_dp_NO_DP',
       'inject_dp_HAS_DP'],
      dtype='object')
```

Am I missing something?

**Comment by interpret-ml** [comment]
Hi @elcolie, 

Good question! Did you use this style of dataframe with the column names defined for training the original EBM? If so, you should be able to see the learned feature names by checking the `ebm.feature_names` property. 

If for some reason these aren't being passed in properly, you can manually encode the feature names into an EBM by passing them in as an initialization parameter:

```python3
ebm = ExplainableBoostingClassifier(feature_names=list(X.columns))
ebm.fit(X, y)

ebm_local = ebm.explain_local(X_test, y_test)
```

Let us know if this doesn't work and we can help you debug further!

-InterpretML Team
