### ISSUE TITLE
Timeline for C++ parallelism?

### ISSUE THREAD

**Issue by veyron8800** [interpretml/interpret#258]
Hello InterpretML team,

I was hoping to be able to evaluate using EBMs as an alternative to xgboost. However, I'm working with decently large datasets (ex: training set is ~200 gbs when loaded into a sparse pandas dataframe), and have found that the package in its current state is unable to handle this scale. The implementation of parallelism within python seems to be the main culprit here. I am unable to train a model with more than one job. When I attempt to train with multiple processes, the first error I receive is due to a lack of **disk space** when joblib attempts to pickle the data and set it off to the child processes (and I have more disk space than ram at my disposal). I cannot use up computing resources letting an ebm model train for days only using a single thread, especially when there is no indication of progress through logging during training.

It is my hope that once concurrency is moved to C++, training an EBM model will become feasible at this scale, as the global interpreter lock will no longer be an issue. An update on the progress of that feature would be much appreciated.

Thanks

EDIT:
A parallelism implementation in C++ was referenced in issue #180

**Comment by interpret-ml** [comment]
Hi @veyron8800 -- Thanks for bringing up this detailed issue and investigating the source of the problem.

The bad news is that C++ parallelism is still pretty far off.  The good news is that about 2 weeks ago we started working on a solution that should resolve these memory issues in a different way.  This is something we've been considering a while, and it has been repeatedly put off in favor of other issues, but yes, it's finally happening.  In a few weeks it should appear in our repo, and then be available on pypi whenever we put out a release following that.

The essential issue, as you've pointed out, is that joblib is making copies of the data inside each of the child processes that get created to do parallel work.  We're planning to use shared memory to eliminate all of these copies, except for the 1 necessary one by using a multiprocessing.sharedctypes.RawArray.  Sometime after that we're also planning on compressing the data internally to reduce the memory usage even more.

-InterpretML team

**Comment by interpret-ml** [comment]
Hi @veyron8800 -- The latest code in the develop branch includes substantial reductions in memory usage. It uses approximately 10x less memory now compared to the previous release. Our next pypi release will include these changes.

The parallelism changes are still a long way off and we currently do scale to 8 cores efficiently, so I'm going to close this issue given we already have other issues tracking fine grained parallelism.

-InterpretML team
