### ISSUE TITLE
Unable to run explained widget

### ISSUE THREAD

**Issue by elcolie** [interpretml/interpret#259]
**Step to reproduce:**
1. Setup server
2. On server run jupyter notebook
3. run the [notebook](https://github.com/interpretml/interpret/blob/develop/examples/python/notebooks/Interpretable%20Classification%20Methods.ipynb) from latptop

**Expected result**
Be able to use widget

**As is**
![image](https://user-images.githubusercontent.com/18206728/123910170-47f47880-d9a4-11eb-8813-d34790bd4e01.png)

**Comment by interpret-ml** [comment]
Hi @elcolie, 

This might have to do with a port forwarding issue -- while the Jupyter notebook is hosted on a specific port, our visualizations are hosted on a different one, and your server might be forwarding Jupyter's port but not our visualization servers. You can either set this up manually by specifying which port you want the visualizations hosted on:

```python
from interpret import show, set_show_addr

set_show_addr(("127.0.0.1", 7080))   # takes in a tuple of (ip_addr : str, and port : int)

show(explanation) # Will run on 127.0.0.1/localhost at port 7080
```

and then setting up a port forward with something like: 

```bash
ssh -L local_port:destination_server_ip:remote_port ssh_server_hostname
```


Alternatively, you can just use the InlineProvider which might remove the need for this. For this method, simply run this code at the top of your notebook:

```python
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

Hope this helps!
-InterpretML Team
