### ISSUE TITLE
write_image cropping cut my text

### ISSUE THREAD

**Issue by elcolie** [interpretml/interpret#260]
**Step to reproduce**
1. Have a long label name
2. Run `EBM` local explain 
    ```
    ebm_local = ebm.explain_local(X_test[:5], y_test[:5], name='EBM')
    show(ebm_local)
    ```
**Expected result**
All text are preserve

**As is**
Text is cropped and text is lost
![image](https://user-images.githubusercontent.com/18206728/123919344-0ddca400-d9af-11eb-8a3f-1a3174b5aaaf.png)

**Comment by interpret-ml** [comment]
Hi @elcolie, 

Thanks for reporting this!  On top of the title cropping, the class names also seem to dominate the legend which makes the graph more difficult to understand. Not sure what the best solution is for this -- maybe different legend placement? -- but it's definitely something for us to consider. For now, a temporary fix might be to shorten your class names (e.g. dropping the "WELL_" prefix).

-InterpretML Team

**Comment by elcolie** [comment]
I think so. Thank you.
