### ISSUE TITLE
How are feature importances calculated in EBM?

### ISSUE THREAD

**Issue by shjustinbaek** [interpretml/interpret#263]
first of all, thanks for the impressive project! 
I am having a lot of fun with it

I would love to know how feature importances are calculated in EBM.
I noticed that the scale of feature importance in ebm.feature_importances_ attribute is a lot larger in regression tasks compared to that of classification tasks.

I wonder why that is the case? 
tried looking it up in documentation but could not find any relevant information

Thanks in advance for the help!

**Comment by JoshuaC3** [comment]
https://github.com/interpretml/interpret/issues/250

Read the final paragraph:

> Finally, to answer your first question: the overall feature importance is calculated as the average absolute contribution a feature makes when predicting across the training dataset. In our example above, we saw that MedInc contributed a +1.7 for this datapoint. If we repeat this process for all datapoints in the training set, np.mean(np.abs(feature_contribution)), we'll arrive at the overall feature importance. This can be interpreted as: what is the average contribution this feature makes to a prediction on the training set?

**Comment by shjustinbaek** [comment]
@JoshuaC3 thanks for the reply.
with this explanation it all makes sense now. 
the regression tasks that i tested all had large target values, its kind of natural that feature importance scale becomes large as well.
