### ISSUE TITLE
Understanding what x and y axis mean in ebm.explain_global() plots

### ISSUE THREAD

**Issue by bwang482** [interpretml/interpret#264]
I want to understand and clarify what the x and y axis mean in the plots generated by `ebm.explain_global() `, as I have come across different definitions from different sources.

Using the feature importance plot below as an example, the density graph shows all training instances lie between the feature bin of 0 and 0.4. I know this feature `x_ii` only contains integers so this means all feature values are 0s. Then why its importance plot extends from 0 to 8 in the x-axis (with a large error bar)? 

I also want to clarify the y-axis of the plot above which indicates how much this feature contributes to the final decision of the binary classification by EBM. If I am not mistaken the x-axis is the original feature/input values, i.e. `x_i`. But is the y-axis feature function value i.e. `f(x_i)` or the logit of the feature function value (I have read this from one of the linked blogs here). What is the range of values in the y-axis?
![Screenshot 2021-07-09 at 14 17 19](https://user-images.githubusercontent.com/6764450/125123527-c5b33500-e0c4-11eb-8e07-6a3702274908.png)

Similar question here but with feature interaction plot. I know the feature value on the axis really shouldn't be over 5, why there is importance estimate extending the x-axis to over 20? Is the model extrapolating what the feature or feature interaction importance would be if the feature value is over 5? 
![Screenshot 2021-07-09 at 15 06 21](https://user-images.githubusercontent.com/6764450/125125188-407d4f80-e0c7-11eb-9a8f-ca30b6235f73.png)

Thanks!

**Comment by interpret-ml** [comment]
Hi @bwang482, 

Sorry for our delay in getting back to you! These are great questions. You might also find the extended discussion here: https://github.com/interpretml/interpret/issues/250#issuecomment-857222944 helpful as well.

To answer your questions directly: 

```Using the feature importance plot below as an example, the density graph shows all training instances lie between the feature bin of 0 and 0.4. I know this feature x_ii only contains integers so this means all feature values are 0s. Then why its importance plot extends from 0 to 8 in the x-axis (with a large error bar)?```

By default, the importance plots extend to the min and max of the data provided to the `fit(X, y)` call in EBMs. The densities at the bottom are limited in size, and it can be difficult to see a single samples away from the majority of the datapoints. From the graph, there are probably a small number of samples where feature x_ii is 8.


```I also want to clarify the y-axis of the plot above which indicates how much this feature contributes to the final decision of the binary classification by EBM. If I am not mistaken the x-axis is the original feature/input values, i.e. x_i. But is the y-axis feature function value i.e. f(x_i) or the logit of the feature function value (I have read this from one of the linked blogs here). What is the range of values in the y-axis?```

You're exactly right about the interpretation. In classification, the y-axis values are the feature function value in a log odds scale, just like the coefficients of a logistic regression would be. In regression, the values are directly in the units of the target. 

```Similar question here but with feature interaction plot. I know the feature value on the axis really shouldn't be over 5, why there is importance estimate extending the x-axis to over 20? Is the model extrapolating what the feature or feature interaction importance would be if the feature value is over 5?```

Similar to above, there must be a few samples in high regions of x-axis values, which will then reflect on the graphs. We typically use these graph bounds to find exactly the type of abnormal samples that you're describing -- it's surprising how often we have impossible data end up in our models. 

Hope this helps, and feel free to reply back with any further questions!

-InterpretML Team
