### ISSUE TITLE
I want to run EBM in an arm device. Is it possible?

### ISSUE THREAD

**Issue by lk1983823** [interpretml/interpret#267]
I have a nvidia-xavier and want to run EBM on it. Is there any solution for this requirement? Thanks!

**Comment by paulbkoch** [comment]
Hi @lk1983823 -- 

Unfortunately, our team does not have any near term plans to implement EBMs on processors other than Intel.  Doing so would require compiling the native code to target ARM.  We'd welcome community contributions in this direction however.

-InterpretML team

**Comment by interpret-ml** [comment]
Hi @lk1983823 -- 

Unfortunately, our team does not have any near term plans to implement EBMs on processors other than Intel.  Doing so would require compiling the native code to target ARM.  We'd welcome community contributions in this direction however.

-InterpretML team
