### ISSUE TITLE
Docker container refused to connect

### ISSUE THREAD

**Issue by elcolie** [interpretml/interpret#276]
OSX 11.5.1

Background:
I have single computer here. I forward port to host machine and start running the `EBM`. 

Problem:
refused to connect

Step to reproduce:
1. `docker-compose run --service-ports lab_container /bin/bash`
2. ` jupyter notebook --ip 0.0.0.0 --no-browser --allow-root`
3. Chrome browser go to `localhost:8888`
4. Fit model
5. Run ebm global explain

As is
Got `refused to connect`

Expected result
Be able to use widget

**Comment by interpret-ml** [comment]
Hi @elcolie, 

Sorry for our delay in getting back to this issue. Our visualizations are hosted on a different port by default than the jupyter notebook, so this is probably just a matter of also port forwarding the visualization server. You can force Interpret to use a specific port with the following code: 

```python3
from interpret import show, set_show_addr

set_show_addr(("127.0.0.1", 7080))   # takes in a tuple of (ip_addr : str, and port : int)

show(explanation) # Will run on 127.0.0.1/localhost at port 7080
```

And then forward both 8888 (jupyter notebook) and 7080 (interpret visualizations) to get the `show` function to present outputs.

Alternatively, you can also try to use our InlineProvider by running this code at the top of your notebook:

```python3
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

which might eliminate the need for forwarding the visualization port. Hope this helps!

-InterpretML Team
