### ISSUE TITLE
Unable to open documentation website

### ISSUE THREAD

**Issue by ZhangTP1996** [interpretml/interpret#278]
I cannot open the documentation website: https://interpret.ml/docs/. At first I think this is an internet problem, but none of my friends can open the website. Could anyone please tell me what happens?

**Comment by msplants** [comment]
Hi Zhang,

I just clicked on the URL you linked in your message and it opens for me right now.  Maybe there was a server outage or something for a bit?  Can you try again and let us know if it is working for you now?

Thanks a million,
Jessica

**Comment by interpret-ml** [comment]
Hi @ZhangTP1996 -

The URL works for us as well.  What location are you trying to access it from?

-InterpretML team
