### ISSUE TITLE
PermissionError, opened by another process when running ExplainableBoostingRegressor

### ISSUE THREAD

**Issue by lukedex** [interpretml/interpret#279]
Hello,

Not sure why this error has started occurring as it was working perfectly with a smaller version of the dataset. I have reset my computer and only run this python code (within a jupyter notebook) and still get the error consistently after a few hours of running.

`PermissionError                           Traceback (most recent call last)
<ipython-input-8-c04b0f8ba7b9> in <module>
      5 
      6 ebm = ExplainableBoostingRegressor(interactions=50, inner_bags=8)
----> 7 ebm.fit(X_train[usable_factors], y_train)
      8 
      9 #ebm_global = ebm.explain_global(name='EBM')

C:\ProgramData\Anaconda3\lib\site-packages\interpret\glassbox\ebm\ebm.py in fit(self, X, y, sample_weight)
    995         )
    996 
--> 997         estimators = provider.parallel(BaseCoreEBM.fit_parallel, train_model_args_iter)
    998 
    999         def select_pairs_from_fast(estimators, n_interactions):

C:\ProgramData\Anaconda3\lib\site-packages\interpret\provider\compute.py in parallel(self, compute_fn, compute_args_iter)
     19     def parallel(self, compute_fn, compute_args_iter):
     20         results = Parallel(n_jobs=self.n_jobs, backend='multiprocessing')(
---> 21             delayed(compute_fn)(*args) for args in compute_args_iter
     22         )
     23         # NOTE: Force gc, as Python does not free native memory easy.

C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1025                 self._backend.stop_call()
   1026             if not self._managed_backend:
-> 1027                 self._terminate_backend()
   1028             self._jobs = list()
   1029             self._pickle_cache = None

C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py in _terminate_backend(self)
    732     def _terminate_backend(self):
    733         if self._backend is not None:
--> 734             self._backend.terminate()
    735 
    736     def _dispatch(self, batch):

C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py in terminate(self)
    491     def terminate(self):
    492         """Shutdown the process or thread pool"""
--> 493         super(MultiprocessingBackend, self).terminate()
    494         if self.JOBLIB_SPAWNED_PROCESS in os.environ:
    495             del os.environ[self.JOBLIB_SPAWNED_PROCESS]

C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py in terminate(self)
    242         if self._pool is not None:
    243             self._pool.close()
--> 244             self._pool.terminate()  # terminate does a join()
    245             self._pool = None
    246 

C:\ProgramData\Anaconda3\lib\site-packages\joblib\pool.py in terminate(self)
    327                         warnings.warn("Failed to terminate worker processes in"
    328                                       " multiprocessing pool: %r" % e)
--> 329         delete_folder(self._temp_folder)

C:\ProgramData\Anaconda3\lib\site-packages\joblib\disk.py in delete_folder(folder_path, onerror)
    113             while True:
    114                 try:
--> 115                     shutil.rmtree(folder_path, False, None)
    116                     break
    117                 except (OSError, WindowsError):

C:\ProgramData\Anaconda3\lib\shutil.py in rmtree(path, ignore_errors, onerror)
    514             # can't continue even if onerror hook returns
    515             return
--> 516         return _rmtree_unsafe(path, onerror)
    517 
    518 # Allow introspection of whether or not the hardening against symlink

C:\ProgramData\Anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    398                 os.unlink(fullname)
    399             except OSError:
--> 400                 onerror(os.unlink, fullname, sys.exc_info())
    401     try:
    402         os.rmdir(path)

C:\ProgramData\Anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    396         else:
    397             try:
--> 398                 os.unlink(fullname)
    399             except OSError:
    400                 onerror(os.unlink, fullname, sys.exc_info())

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LUKE~1.DEX\\AppData\\Local\\Temp\\1\\joblib_memmapping_folder_17228_2962031158600\\17228-2962015940552-b2b0d1cb1a3c4644b5a8363f3236af5b.pkl'`

**Comment by interpret-ml** [comment]
Hi @lukedex, 

Thanks for reporting this! Do you mind sharing what versions of `interpret`, `scikit-learn` and `joblib` you have installed on your machine? You can see the version numbers with `pip show interpret scikit-learn joblib`. In addition, it might be helpful to know the size of the dataset you're training on (the tuple produced by `X.shape`) and the amount of memory you have on your machine.

-InterpretML Team

**Comment by lukedex** [comment]
interpet = 0.2.6
scikit-learn = 0.22.1
joblib = 0.14.1

df.shape = (418572, 161)



I've run again today and the folder noted within the error has changed to.. 


'PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LUKE~1.DEX\\AppData\\Local\\Temp\\1\\joblib_memmapping_folder_22232_1804417695240\\22232-1804429923144-688ba9af00cb45c48460d3f658047b4f.pkl'

**Comment by lukedex** [comment]
I'm also getting this error a lot which I've never had before. I recently upgraded to the most recent version on interpretML so that I could use sample_weight.

`ImportError: [joblib] Attempting to do parallel computing without protecting your import on a system that does not support forking. To use parallel-computing in a script, you must protect your main loop using "if __name__ == '__main__'". Please see the joblib documentation on Parallel for more information`

**Comment by lukedex** [comment]
I've updated joblib to it's most recent version and that seems to of fixed the problem. Would you like me to close this issue now?
