### ISSUE TITLE
ebm.predict() on new data just returns intercept value

### ISSUE THREAD

**Issue by bbertoni** [interpretml/interpret#280]
How can I make predictions on new data using ExplainableBoostingRegressor? 

When I use ebm.predict() on the training data, I get back a reasonable set of predictions, but when I use ebm.predict() on new data I seem to always get the intercept value back despite inputting feature vectors that are the same as the training data only with one feature altered.

What am I missing?

**Comment by interpret-ml** [comment]
Hi @bbertoni, 

That's unusual! Do you mind running the following code: 

```python3
from interpret import show

ebm_local = ebm.explain_local(X)
show(ebm_local)
```
on your new sample(s) and see if the explanation has only an intercept?

-InterpretML Team

**Comment by bbertoni** [comment]
The local feature importance is bizzare:
![image](https://user-images.githubusercontent.com/17998962/131741270-14426632-c1a0-47ab-8de8-cfb88b316364.png)
The feature values displayed look correct.
I am inputting the same feature vector as one that was used to train the model, except the value of P59 has been changed from 1 to 0. Here is the feature importance for the training data vector:
![image](https://user-images.githubusercontent.com/17998962/131741088-95061b1c-7ca6-453e-a25d-c8abc84d37e3.png)

**Comment by bbertoni** [comment]
Ah...just figured it out. I had replaced the value of P59 from an integer equal to 0 to a float equal to 1. When I convert to an integer I get reasonable results.
