### ISSUE TITLE
show(ebm_local) doesn't show anything 

### ISSUE THREAD

**Issue by yliyanage** [interpretml/interpret#282]
I am trying to get local explanations. I am getting this user-warning and it is not showing anything on the Jupyter lab cell.

ebm = ExplainableBoostingClassifier()
ebm.fit(Xtrain, Ytrain)
ebm_local = ebm.explain_local(Xtest, Ytest)
show(ebm_local)

--/miniconda3/envs/py3/lib/python3.7/site-packages/interpret/visual/udash.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
--/miniconda3/envs/py3/lib/python3.7/site-packages/interpret/visual/udash.py:6: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
--/miniconda3/envs/py3/lib/python3.7/site-packages/interpret/visual/udash.py:7: UserWarning: 
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table as dt

**Comment by dhops** [comment]
I'm having the same issue. Did you figure it out?

**Comment by dhops** [comment]
If you use the "visualize" function, you can export the visualizations to html

`
for i in range(len(X_test)):
    ebm_local.visualize(i).write_html("graph"+str(i)+".html")
`

**Comment by interpret-ml** [comment]
Hi @yliyanage and @dhops, 

Thanks for reporting this issue! We can reproduce the user warnings with the latest version of Dash and JupyterLab, but the graphs still show up beneath the warnings for us. 

![image](https://user-images.githubusercontent.com/50031429/134567980-9590633e-2914-4669-92dc-25774978f0f6.png)

@dhops has the right idea for an alternative way to print out graphs, but it'd be better if we could figure out why `show` wasn't working for you as intended. Do you mind sharing a few details with us?

- Operating System (e.g. Windows/Linux)
- Browser (e.g. Firefox/Chrome)
- Versions of `dash`, `jupyter`, `jupyterlab`, and `ipykernel`

Thanks!
-InterpretML Team

**Comment by dhops** [comment]
I'm not using a notebook, so that explains my problems I guess :)

**Comment by yliyanage** [comment]
@dhops Thank you for the suggestion! It works, but I still would like to get the table GUI in the cell. 

@interpret-ml 

Here are my configurations. I ma using Jupiter lab. 

- Operating System : Linux
- Browser : Safari,  I tried Firefox too. But it is blank as well. 
- dash : 2.0.0
- jupyter core     : 4.6.3
- jupyter-notebook : 6.0.3
- qtconsole        : 4.7.4
- ipython          : 7.13.0
- ipykernel        : 5.3.0
- jupyter client   : 6.1.3
- jupyter lab      : 3.0.16
- nbconvert        : 5.6.1
- ipywidgets       : 7.5.1
- nbformat         : 5.0.7
- traitlets        : 4.3.3

**Comment by yliyanage** [comment]
In Safari:
<img width="1124" alt="Screen Shot 2021-09-24 at 7 19 57 AM" src="https://user-images.githubusercontent.com/55597857/134666384-4ddff07c-2f28-4893-a61e-37390338ac46.png">

In Firefox:
<img width="1152" alt="Screen Shot 2021-09-24 at 7 18 24 AM" src="https://user-images.githubusercontent.com/55597857/134666520-dc8024f6-9768-4c65-ab7d-0b5fcf0d818b.png">

**Comment by yliyanage** [comment]
@interpret-ml  Thanks for the update! That worked for me!!! 👍
