### ISSUE TITLE
Call for Participants: User Study on EBMs, Interpretability, and Model Editing

### ISSUE THREAD

**Issue by interpret-ml** [interpretml/interpret#283]
Hi Everyone, 

We were asked to share details about this upcoming user study on behalf of @xiaohk and their team, who are interested in building new visualization and editing tools for EBMs and other GAMs. Please check out the details below if you are interested in participating!

-InterpretML Team

---
---

Hello 👋,

We are a Microsoft Research team designing and developing an interactive visualization tool that helps ML engineers easily and responsibly modify the prediction process of ML models.

We are seeking data scientists and researchers who are experienced with InterpretML and the Explainable Boosting Machine (EBM) model to participate in a 1-hr virtual research session. You will be compensated for your time with a $25 Amazon gift card.
The results of this study will help us improve tools for data scientists to build responsible ML models.
If you are interested in participating this study, please sign up using [this form](https://forms.office.com/r/1MXQ3Eabc8).

Thank you in advance!

---
For additional information or concerns about how Microsoft handles your personal information, please see the [Microsoft Privacy Statement](http://go.microsoft.com/fwlink/?LinkId=521839).

For Employees, External Staff and Candidates please use the [Microsoft Global Data Privacy Notice](http://go.microsoft.com/fwlink/?LinkId=518021).

---
Microsoft Corporation 

One Microsoft Way

Redmond, Washington 98052 USA

**Comment by lukedex** [comment]
Just wanted to say that I had my session today and found it extremely interesting and great to have a chat with @xiaohk. The tool itself is very powerful and amazingly put together and you get paid!
