### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by zzstefan** [interpretml/interpret#288]
I have data with 4300 samples,  and each sample has 29000 features.  I used the EBM functional and set the n_job=8. 

The first fold has run for 15 hours and the memory usage keeps growing. Right now each job consumes about 22G RAM.  So how to estimate the overall memory?  Is there any way to reduce the memory usage?

I was using the default parameter setting.

**Comment by interpret-ml** [comment]
Hi @zzstefan -- The latest code in the develop branch includes substantial reductions in memory usage.  It uses approximately 10x less memory now compared to the previous release.  Our next pypi release will include these changes.

-InterpretML team
