### ISSUE TITLE
Question on Multiclass + Interactions

### ISSUE THREAD

**Issue by ajyl** [interpretml/interpret#296]
Hi InterpretML team,

I had a question for the multiclass classification usecase for EBMs. I've noticed that for multiclass usecases, the interaction terms are set to 0. Why is this the case? Does it have to do with how EBMs work (mathematically) or is it mostly because it just hasn't been thoroughly tested and is experimental?
What do you think would happen if I changed the code around to allow for interactions during multiclass classification?

Thank you in advance.

**Comment by interpret-ml** [comment]
Hi @ajyl -- Thanks for offering to help implement this feature.  The main issue with multiclass pairs is that we currently don't know how to visualize them.  Mathematically and implementation-wise, they should be fairly straightforward.

There's some information on this topic in this paper ( https://arxiv.org/pdf/1810.09092.pdf ).  Additionally for pairs there are question about how to best show information for the multiple classes on a 2D screen.  We currently use a heatmap for regression or binary classification, but that doesn't work as well for multiclass.

-InterpretML team

**Comment by ajyl** [comment]
Thank you!

**Comment by yap231995** [comment]
To follow up with this question,
for multiclass with high interaction can it be used or the code will automatically cause interaction =0? As I would want to try it out without any visualization to check if it works on some dataset.
