### ISSUE TITLE
How to measure the significance of the score in PDP? 

### ISSUE THREAD

**Issue by DerrickYifeng** [interpretml/interpret#302]
Hi team, 

Amazing work on the interpretML! The interpretability adds great values to the business application and thanks for all your hard work! 

I have a question regarding to the score in PDP. We only see the avg marginal impact of a feature from the score,  but is there a way in the package to test the statistical significance of such impact? If not, is there any future plan to add this function/reference you can ping me? 

Thanks very much!

**Comment by richcaruana** [comment]
Are you asking about real partial dependence plots (from interpret.blackbox), or are you asking about the feature graphs we train with EBMs (which some people sometimes call partial dependence plots)?

You might also be interested in the discussion about computing p-values for EBM feature graphs: https://github.com/interpretml/interpret/issues/309

-Rich.
