### ISSUE TITLE
How to extract additive model from EBM

### ISSUE THREAD

**Issue by herman-nside** [interpretml/interpret#305]
I would like to extract the additive model itself from the model object in order to perform the prediction "manually". After fitting I can see `model.additive_terms_` as well as `model.feature_names`. But I think I also need the bin intervals in order to do the prediction calculation. Is it possible to obtain those?

**Comment by MainRo** [comment]
The bins intervals are available in the *preprocessor_* object of a trained model. You can see an example where the model parameters are retrieved in the onnx converter:

https://github.com/interpretml/ebm2onnx/blob/master/ebm2onnx/convert.py#L96

**Comment by interpret-ml** [comment]
Thanks @MainRo for answering this.  As MainRo points out, for continuous values ebm.preprocessor_.col_bin_edges_ contains the transition edges from one bin to the next.  You can use np.digitize to determine the bin indexes.  categorical features use the ebm.preprocessor_.col_mapping_ attribute which is a simple dictionary.  One thing that is confusing to people initially is that we reserve the index 0 to indicate missing values, so after calling np.digitize you need to add 1 to find the index in additive_terms_.  The categorical mapping already takes this into account.

-InterpretML team
