### ISSUE TITLE
Confidence interval for global mean absolute score

### ISSUE THREAD

**Issue by pnxenopoulos** [interpretml/interpret#316]
Hi there,

Thank you for this great library. I was wondering, if there is a procedure to produce CIs for mean absolute score. I know we see confidence intervals to see each feature's score at different levels (with an upper and lower bound), but we also can see the mean absolute score when using `.explain_global()`. Is there an accepted procedure for producing a confidence interval in the mean absolute score?

**Comment by zeydabadi** [comment]
That is my question too.
@pnxenopoulos Have you found a solution for this?
