### ISSUE TITLE
Cannot launch interactive visuals

### ISSUE THREAD

**Issue by jonimatix** [interpretml/interpret#317]
Hello,

I am trying to show the results using the show method, but I am getting:

> Internal Server Error caught by udash. See logs if available.

Code:
`ebm = ExplainableBoostingClassifier()
ebm.fit(x_train, y_train)

ebm_global = ebm.explain_global()
show(ebm_global)
`

The IDE I am using is VS Code, but I am also unable to make it work when I use Spyder.

Can you provide any help?

**Comment by interpret-ml** [comment]
Hi @jonimatix, 

Thanks for reporting this! Are you using the IPython window inside of VSCode/Spyder, or just the text editing view? Our default visualizations only work in the IPython/Notebook-style environments to enable interactivity. 

If you're just editing .py files and running scripts from the command line, you can write the images to disk with the following code (and view them in your browser):

```python3
ebm_global = ebm.explain_global()

for key in range(len(ebm_global.selector)):
    fig = ebm_global.visualize(key)
    fig.write_image(f"images/graph_{key}.pdf")
```

You may need to install the `kaleido` python package for the code above to work with: `pip install kaleido`. Hope this helps!

-InterpretML Team

**Comment by jonimatix** [comment]
Thank you @interpret-ml

**Comment by konabuta** [comment]
@interpret-ml Hi team, any roadmap for supporting vscode for iteractive dashboard?
