### ISSUE TITLE
Interaction Features with Merged EBMs

### ISSUE THREAD

**Issue by kspieks** [interpretml/interpret#319]
When running the Merge EBM Models [notebook](https://github.com/interpretml/interpret/blob/38b105d009dad961511fb1c25e7fd00261d09349/examples/python/notebooks/Merging%20EBM%20Models.ipynb), it prints a warning that `Interaction features are not supported.` However, given that many interaction features are common to all of the trained models in this example, is it possible to visualize these interaction features along with the original ones?

Thanks for your help!

**Comment by interpret-ml** [comment]
Hi @kspieks -- You have excellent timing.  As it happens we're currently in the process of updating merge_models to handle interactions.  It should be pushed out in the next few days.

-InterpretML team

**Comment by kspieks** [comment]
Thanks for the update. That's exciting news!

**Comment by interpret-ml** [comment]
Hi @kspieks -- The merge models update has been pushed to the develop branch and you're welcome to try it now.  I will caution you that it's firmly in the experimental category for now, but that should improve over the next few days.

-InterpretML team
