### ISSUE TITLE
Saving and loading model from file

### ISSUE THREAD

**Issue by meriliis** [interpretml/interpret#32]
Hi,
Would it be possible to add functionality to save the model to disk and load a saved model from file?

**Comment by interpret-ml** [comment]
Hi @meriliis, 

This currently should work with ```pickle```: https://docs.python.org/3.7/library/pickle.html

With pickle, you can dump objects to disk, and reload them at a later time. For example, you can pickle dump after training an EBM, and reload it later for predictions. 

We're currently looking into more integrated ways of saving/loading models from disk. 

Thanks!
-InterpretML Team

**Comment by mosew** [comment]
> We're currently looking into more integrated ways of saving/loading models from disk.

Thanks so much for making and maintaining this package! I want to tack an ask onto this feature request, if that's not inappropriate: the ability to easily edit the Dashboard, e.g. add customizable/free-text tabs, add notes and links to existing tabs, etc.

**Comment by interpret-ml** [comment]
Hi @mosew,

No worries, glad it's working for you!
Sure, do you mind opening a separate issue with what you just wrote in terms of feature requests?

Right now we're trying to get out some new features this week, but we'll revisit what you've written and get back either end of this week or early next.
