### ISSUE TITLE
Exception when attempting to apply SHAP to explainable boosting machine

### ISSUE THREAD

**Issue by neilm1** [interpretml/interpret#320]
Hello 

When I am attempting to run shap.Explainer on a trained ExplainableBoosting machine I get an exception

c:\workarea\phd\research_project\envs\project_1\lib\site-packages\shap\explainers\_additive.py in supports_model_with_masker(model, masker)
     84         if safe_isinstance(model, "interpret.glassbox.ExplainableBoostingClassifier"):
     85             if model.interactions is not 0:
---> 86                 raise Exception("Need to add support for interaction effects!")
     87             return True
     88 

Exception: Need to add support for interaction effects!

Is it possible to run SHAP on EBM (I am trying to compare different models and also the EBM feature importance against SHAP.

**Comment by paulbkoch** [comment]
Hi @neilm1 -- You could use the KernelExplainer for this I suppose.  It would be nice to have a model optimized Shap implementation that works on EBMs with interactions, but the better place to implement this would be in the Shap library, so closing this issue here.
