### ISSUE TITLE
Black box - Visualization with local and global explainer

### ISSUE THREAD

**Issue by ritathakor** [interpretml/interpret#321]
Hi

With the Black box explanation technique as follow we have different visualization available.
I would like to clarify about kind of visualization available.

LIME ->  We can use standard visualization of the interpretml.Show(). 
SHAP -> We can use standard visualization of the interpretml.Show(). For global explanation we can use Explainer from 
               interpret.interpret_commnity, with ExplanationDashboard from raiwidgets.
PDP ->    We can use standard visualization of the interpretml.Show(). 
Morris ->We can use standard visualization of the interpretml.Show(). 

Is this my understanding correct?

**Comment by paulbkoch** [comment]
Yes, that looks correct.
