### ISSUE TITLE
Incorporate NAM?

### ISSUE THREAD

**Issue by JHLiu7** [interpretml/interpret#323]
Hi there, just wondering if there's a plan to include the recent neural additive model into this great repo. Thanks.

**Comment by interpret-ml** [comment]
Hi @JHLiu7 -- We do have and are planning to release newer NAM code.  Tentatively it will be released in a separate repo due to the pytorch dependencies.  The code still needs some work though before it's ready for release, and we haven't yet decided on a release date.

-InterpretML team

**Comment by JHLiu7** [comment]
Cool, thanks!
