### ISSUE TITLE
get_params() returns empty dict

### ISSUE THREAD

**Issue by szperajacyzolw** [interpretml/interpret#326]
Hello

I have trained ExplainableBoostingClassifier and get_params() method doesn't work - it returns {}. explain_local and explain_global are working fine. This raises some concerns, as without it I can't edit lookup tables.
Maybe there is another way to obtain properly formatted parameters to further edit them and update the model with set_params()?

interpret version 0.2.7

**Comment by interpret-ml** [comment]
Hi @szperajacyzolw -- get_params only retrieves the __init__ params, so it wouldn't be useful for getting attributes that are generated in the fit function.  The way to edit the model currently is to change the values in the additive_terms_ attirbute.  For an alternative UI solution there's the GAM Changer UI that you might find useful:

https://github.com/interpretml/gam-changer

-InterpretML team

**Comment by szperajacyzolw** [comment]
Thank you very much! It is a game-changer ;)
