### ISSUE TITLE
How to make intercept value(β) equal to zero instead of the sample average value in ExplainableBoostingRegressor?

### ISSUE THREAD

**Issue by HCYuZJU** [interpretml/interpret#328]
First, thank you for all the work you put into the package. It is really useful to own such a precise and interpretable model.

I have a question about the **intercept value** in ExplainableBoostingRegressor: Because intercept is equal to the average of the sample values, we can observe the contribution of each feature from the average value to the predicted value.

However in my problem, I want to find out the "absolute" contribution of each feature from zero to the predicted value. In other words, let intercept value equal to zero(let β=0 in GAM formula).

I'd appreciate it if you could provide a solution to change codes to achieve it.

Thank you!

**Comment by interpret-ml** [comment]
Hi @HCYuZJU -- We don't really recommend you do that.  Let's say you had some features in your model which were generated using random noise.  In that case moving contributions into that feature would make it look like it was contributing something when it was not.  This is an extreme example, but a similar situation will occur with any features in your model that have minimal importance.

If you're still interested in doing this though, the way you'd go about it would be to take the intercept value, divide it by the number of items in the additive_terms_ attribute, then add that number into each of the cells of the additive_terms_ attribute.  Your model should produce identical predictions.

-InterpretML team

**Comment by GaoyangLiu** [comment]
> If you're still interested in doing this though, the way you'd go about it would be to take the intercept value, divide it by the number of items in the additive_terms_ attribute, then add that number into each of the cells of the additive_terms_ attribute. Your model should produce identical predictions.

In my opinion, the underlying assumption is all features contribute equally at the first beginning, or in the training dataset, if I understand correctly.  It seems unreasonable for many cases, where some features are much more important than others. I think intercept values of different features should be different.

For the zero intercept problem, is there any way to get the initial scores of each feature, which are not equal to each other?

**Comment by interpret-ml** [comment]
Hi @GaoyangLiu -- In our setting, and for GAMs in general, the intercept is the base rate and all the feature graphs are centered such that the average of their contribution is zero.  There's a longer discussion of this in issue https://github.com/interpretml/interpret/issues/207

-InterpretML Team
