### ISSUE TITLE
How to get the data used to generate the plots for a global EBM explanation?

### ISSUE THREAD

**Issue by michael-mayo** [interpretml/interpret#331]
I am training EBM classifiers but not using a Jupyter notebook. I want to display the plot data for a specific feature or interaction on the command line. How can I get this data?

**Comment by interpret-ml** [comment]
Hi @michael-mayo -- There is some code posted in this issue https://github.com/interpretml/interpret/issues/325 that would enable you to extract the plot from the global explanation object.  An alternative solution which might work for you would be to pickle either the model or the global explanation which you could then unpickle in a Jupyter capable system.

-InterpretML Team
