### ISSUE TITLE
How to get FAST results - ebm.inter_indices_ removed

### ISSUE THREAD

**Issue by BullAJ** [interpretml/interpret#332]
Hello!

Have the features mentioned here to expose FAST results to the user been implemented in some fashion? The method listed here does not work, and I would like to get the results of FAST directly. I am making a new issue as the other one is quite old.

Thank you!

> Hi @shneezers,
> 
> Thanks for bringing this up! With the way the code is written now, it's not easy to extract the computed FAST scores. FAST currently calculates scores for each possible interaction (N2 - N terms), and does so once per every outer bag. Because there are so many terms calculated, we end up throwing away all but the top "k" terms, where k is the number of interactions specified by the user (see here:
> 
> https://github.com/interpretml/interpret/blob/544644faef91f92355c03295f3f220a2bbc50515/python/interpret-core/interpret/glassbox/ebm/internal.py#L1063
> )
> 
> Each final EBM is an ensemble of bagged "inner EBMs" (defaulted to 16), each of which has estimated their own FAST scores across all interactions, which will be different per bag. To merge these into the final pairwise interactions used in the model, we do a stagewise selection procedure (see here:
> 
> https://github.com/interpretml/interpret/blob/544644faef91f92355c03295f3f220a2bbc50515/python/interpret-core/interpret/glassbox/ebm/ebm.py#L983
> ).
> 
> All this is to say that ultimately, for a default EBM run, we end up with a total of 16 * (N2 - N) FAST scores. Because this is quite a bit to store directly in the model, we ended up calculating these on the fly, and discarding scores/pairs we didn't keep along the way.
> 
> We'd still like to directly expose FAST scores to users, so we've come up with a few ideas:
> 
>     * Expose FAST directly as a function, so users can do this calculation on their own (either before or after fitting an EBM with main effects).
> 
>     * Add parameters to EBM which would enable people to optionally keep FAST scores. These would be defaulted to OFF, but interested users can opt-in to keeping them. We might expose one to store each of the inner EBMs, and then another to have each of those EBMs keep their FAST scores. We could do this for all interaction terms, or just the user specified top K.
> 
>     * Store results of the backward/foreward stagewise selection procedure, which would be a longer ranked list of significant interaction terms.
> 
> 
> Any thoughts on which approach you'd prefer, or perhaps multiple? We're really happy to see interest in FAST and definitely want to make this easier to use.
> 
> -InterpretML Team

_Originally posted by @BullAJ in https://github.com/interpretml/interpret/issues/112#issuecomment-1082326786_

**Comment by interpret-ml** [comment]
Hi @BullAJ,

One of our team members just started coding this and it should be available soon.  We're releasing it as a separate function that can be called to get the interaction strengths.

-InterpretML Team

**Comment by paulbkoch** [comment]
HI @BullAJ -- The interaction strength API is available now.  It's a simple utility function that you can call like this:

```
from interpret.utils import measure_interactions
interaction_strengths = measure_interactions(X, y)
```

We think it will work better if you first train a model that extracts as much benefit from the individual features as possible.  Of course, an EBM with zero interactions would be ideal in this instance, but a linear model or another GAM would work too.  Here's an example using an EBM:

```
from interpret.glassbox import ExplainableBoostingClassifier
from interpret.utils import measure_interactions

ebm = ExplainableBoostingClassifier(interactions=0)
ebm.fit(X, y)
interaction_strengths = measure_interactions(X, y, init_score=ebm)
```
