### ISSUE TITLE
Cannot Import merge_ebms

### ISSUE THREAD

**Issue by AndreiRoibu** [interpretml/interpret#338]
Hello,

When trying to import merge_ebms from the utils package, I am presented with an ImportError. For this, I am using a Jupyter Notebook and the following code sequence, which produces the following error:

```python
from interpret.glassbox.ebm.utils import merge_ebms
from interpret import show
```

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-48-23eb1fb2a102> in <module>
----> 1 from interpret.glassbox.ebm.utils import merge_ebms
      2 from interpret import show

ImportError: cannot import name 'merge_ebms' from 'interpret.glassbox.ebm.utils' (...env/lib/python3.8/site-packages/interpret/glassbox/ebm/utils.py)
```

**Comment by interpret-ml** [comment]
Hi @AndreiRoibu  -- merge_ebms hasn't made it's way to pypi yet, so you would need to build from github currently if you want that functionality.  Here are the instructions for doing so:

https://interpret.ml/docs/installation-guide.html

-InterpretML team

**Comment by paulbkoch** [comment]
merge_ebms is on pypi now
