### ISSUE TITLE
Scores in Y-axis

### ISSUE THREAD

**Issue by Tejamr** [interpretml/interpret#339]
Hi ,

I have applied EBM Global explanations and got visualization as below . Can anyone explain what Score represents along y-axis . Is it same for each and every feature ? If no, what is the criteria behind that? If yes what the numbers represent(0,1,2,3)
![newplot (2)](https://user-images.githubusercontent.com/91931018/167775951-87d351d5-bd0a-46bd-a25c-0547a608e360.png)

**Comment by Harsha-Nori** [comment]
Hi @Tejamr,

We had a detailed discussion on understanding the global functions for each feature here: https://github.com/interpretml/interpret/issues/250, with an explanation on scores in the classification setting here: https://github.com/interpretml/interpret/issues/157#issuecomment-681082687

The broader discussion on those threads might be helpful too!
