### ISSUE TITLE
Problem with merging models method

### ISSUE THREAD

**Issue by lbalec** [interpretml/interpret#343]
I'm using 0.2.7 version of interpret installed by pip

In your example notebook, there's `merge_ebms()` method, but the only method I found is the old one - `merge_models()` from EBMUtils package. I'm 100% sure I'm using the latest version, I even tried to install library on fresh machine and I still have only the old method.

Using the old method with few `ExplainableBoostingClassifier` models, with multiclass problem, I'm getting following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_12601/4104291603.py in <module>
----> 1 merged_ebm = EBMUtils.merge_models(models=[ebm_models[0], ebm_models[1]])

~/.conda/envs/image-processing/lib/python3.7/site-packages/interpret/glassbox/ebm/utils.py in merge_models(models)
    178             ebm.preprocessor_.col_bin_counts_[index] = np.round(np.average(bin_weights, axis=0))
    179 
--> 180             averaged_model = np.average(log_odds_tensors, axis=0 , weights=bin_weights )
    181             model_errors = EBMUtils.weighted_std(np.array(log_odds_tensors), axis=0, weights= np.array(bin_weights) )
    182 

<__array_function__ internals> in average(*args, **kwargs)

~/.conda/envs/image-processing/lib/python3.7/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
    396             if wgt.ndim != 1:
    397                 raise TypeError(
--> 398                     "1D weights expected when shapes of a and weights differ.")
    399             if wgt.shape[0] != a.shape[axis]:
    400                 raise ValueError(

TypeError: 1D weights expected when shapes of a and weights differ.
```

Any help here?

**Comment by interpret-ml** [comment]
Hi @lbalec -- merge_ebms hasn't made its way to PyPI yet, so you would need to clone the repo and build it to use merge_ebms today.  Here are the instructions for doing so:

https://interpret.ml/docs/installation-guide.html

-InterpretML team

**Comment by lbalec** [comment]
Thank you @interpret-ml  for answer. I tried manual installation, but unfortunately getting npm's error. I'll try to figure it out.

What about the numpy's error while merging multiclassification models? Is it something to do with the old version on this method?

**Comment by interpret-ml** [comment]
Hi @lbalec  --  Multiclass is supported in the new merge_ebms.

-InterpretML team
