### ISSUE TITLE
Logistic Regression Source code for Local and Global Explanations

### ISSUE THREAD

**Issue by Tejamr** [interpretml/interpret#344]
Hi ,

Can anyone leave a link here for accessing the Logistic Regression(Explainability) Source code . I am having few doubts also :
1 : How intercept is calculated ? Is it same for each and every problem .If yes, what is the reason ? If no, why and how it is calculated ?
2 : How to calculate each feature contributions towards dependent variable (Overall Importance)?
3 :How to calculate Predicted probability ? While I am summing up all the probabilities from local explanations I am not getting accurate ones ?
Please help me regarding the above doubts . Any link or paper or video will be more beneficiary for me ...
![newplot (4)](https://user-images.githubusercontent.com/91931018/171846743-615d7e9c-15c6-4c85-92c1-b53b16692552.png)
![newplot (5)](https://user-images.githubusercontent.com/91931018/171846747-98a5da12-601f-48ac-9558-b712d27da1c9.png)

**Comment by paulbkoch** [comment]
We use the scikit-learn LogisticRegression implementation to fit the model.  The intercept itself is coming directly from scikit-learn's "intercept_" attribute.  When generating the explanations, the code for that is here for local explanations:

https://github.com/interpretml/interpret/blob/cb1e0ebb71d0cd43644078d2dfcdb7f55865ef9e/python/interpret-core/interpret/glassbox/linear.py#L94

 and here for global explanations:

https://github.com/interpretml/interpret/blob/cb1e0ebb71d0cd43644078d2dfcdb7f55865ef9e/python/interpret-core/interpret/glassbox/linear.py#L183
