### ISSUE TITLE
Errors in Predicted and Prediction Scores(Logistic Regression)

### ISSUE THREAD

**Issue by Tejamr** [interpretml/interpret#345]
Hi @interpret-ml @richcaruana @Harsha-Nori ,

It is very fun using Interpret ML which is defining explanations in a very clean and smooth manner . But I have very few doubts .
I am using Logistic Regression model explanation using Interpret ML .
1 .Getting into the visualisation part it is always showing a probability of greater then 0.5 (predicted Probability) for the whole test data (>0.5).
2 . When the predicted probability is >0.5 the label should be 1(True) where it is 0(False) .
3 . What one should understand by looking into the  Actual and Predicted probabilities and Scores .
4 . Should we have to perform EDA on data before fitting it into the model?
[Find the below images
![Screenshot from 2022-06-09 11-02-32](https://user-images.githubusercontent.com/91931018/172771725-7abeea68-6457-4c56-81d3-6b18d8f4bcfe.png)
![newplot (6)](https://user-images.githubusercontent.com/91931018/172771761-38bf537c-4c6d-455e-9a2d-217ac027b7cf.png)
 for your reference].

**Comment by paulbkoch** [comment]
Thanks @Tejamr.  Glad you're finding the package useful.  You could certainly do EDA before training an EBM, but usually it's easier to just train your EBM first and then do the EDA afterwards based on any oddities you might find in the model.
