### ISSUE TITLE
Code snippet on how to use purify function

### ISSUE THREAD

**Issue by drskd** [interpretml/interpret#347]
Hi InterpretML team, 

I was thinking about making sure the effect of one feature was solely contained in its single feature tree and not dispersed across some interaction terms. 
I came across issue #53 that seems to do exactly what I would like to do.

Following the code, I looked at this function in the research folder of ebm : 
`def purify(mat, densities=None, verbose=False, tol=1e-6, randomize=False):`

Could you provide a small code snippet to use after an ebm has been fitted? 
To what corresponds the `mat` argument in the function signature? I guess this could corresponds to each lookup table that are build with EBMs, but I would like to have the full code/pipeline of extracting it and then reintegrate it in a fitted EBM.

Thanks again for this great initiative combining performance and explainability !

**Comment by drskd** [comment]
Hi @blengerich ,

I noticed your contribution about purifying the effects in the EBM and I am super thankful for that because it looks exactly like something I need.
Could you help me understanding how I should use your function on a fitted EBM?

Thanks !

**Comment by blengerich** [comment]
Hi @drskd, thanks for the ping!

Building on the purification utility code that I had previously added to this repo, I've made a [new repo](https://github.com/blengerich/gam_purification) which has purification code for a couple of different model classes. The EBM-specific utilities are available here: https://github.com/blengerich/gam_purification/blob/main/gam_purification/models/ebm.py

Using this code, we can call

`purify_ebm_laplace(ebm_global, dataset_name, X_train.values, laplace=1, should_transpose=False)`

and it will perform purification under a Laplace-smoothed data distribution and return a dictionary with keys
```
"mains",
"mains_moved",
"pairs",
"pairs_moved",
"intercept"
```

It also includes a demo in [this notebook](https://github.com/blengerich/gam_purification/blob/main/demos/compas.ipynb).

**Comment by drskd** [comment]
Thanks a lot @blengerich, looks perfect !
