### ISSUE TITLE
Next PyPi release

### ISSUE THREAD

**Issue by carMartinez** [interpretml/interpret#361]
Hello. As of writing, the last PyPi relese was on Sept 23 2021. Based on reading some of the Issues threads here, it seems like there have been major improvements since then  e.g. EBM using less memory.

Is there an ETA for another PyPi release?

For context, I work in a cloud environment where it's difficult to compile anything with C++ code (Databricks with Azure machines). Releases via pypi, anaconda, or maven are my only options for not-pure-python python packages.

Thank you.

**Comment by paulbkoch** [comment]
Interpret 0.3.0 is out now on pypi.  Enjoy.
