### ISSUE TITLE
FAST function is not exported 

### ISSUE THREAD

**Issue by ConallTimoney** [interpretml/interpret#363]
I am looking to use FAST for interaction detection. I can see merge request #355 **Exposing FAST** intended to exposure a function to allow users to use FAST interaction detection. However, I can't import the `fast` function in fast.py. I can't see fast.py when I explore the package in my environment. I don't think its being exported correctly or its failing to install correctly on my machine. I am using the latest version of interpretML, as of now v0.2.7. 

Python Version: 3.6.13

OS: macOS Big Sur, 11.6.8

System Specs:
Processor: 2.6 GHz 6-Core Intel Core i7
Memory: 16 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5300M 4 GB, Intel UHD Graphics 630 1536 MB

**Comment by msplants** [comment]
Thanks for your interest in the new FAST API. If you want to try it before the next release, you can install from source. For instructions on how to do so, see our [Installation documentation](https://interpret.ml/docs/installation-guide.html).
