### ISSUE TITLE
EBM ( offset column)

### ISSUE THREAD

**Issue by mtl-tony** [interpretml/interpret#364]
Hello,

I'm really enjoying using your package specifically the EBM as it's been very helpful and has really improved my ability to intrepret my model. For my problem domain however it's some times needed that I offset my response by a certain variable. An example would be h2o gbm below which has that same parameter that allows a response to be offset by certain variables.

https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/offset_column.html

I was wondering if you could point me to where in the code this feature could be added! I was doing the math and it seems to not be a complicated issue to resolve, as making a slight adjustment in the process of when initializing the function during training should solve it.

Thanks

**Comment by paulbkoch** [comment]
Hi @mtl-tony, 

Glad to hear you're enjoying using InterpretML.  Do you need this offset for regression or classification?  For regression it would be simple since we currently only support the identity link function, so you can just subtract the shift from your y before training, and later add it back during prediction.  For classification it's harder.  If you're doing classification and want to make this modification, are you mostly interested in just getting it to work, or are you interested in making a contribution?  Doing this in a clean way would be harder than the hacky solution.

**Comment by mtl-tony** [comment]
Hi.

Yes so my specific problem is actually classification so it's a bit harder to do than the regression case.

I think my goal is to get it to work more than anything so I would start with the hack solution but I'd be willing to contribute as well once I get it to work and clean it up.

In the case of classification where would you recommend in the code I start to perform the modification. I've reviewed the methodology with other models and how it's done so I'm a bit famiar with it attbis point.

Thanks

**Comment by paulbkoch** [comment]
What you need to do is change the initialization scores passed into the booster.  By default we currently start with scores of zero.  This line below is where we pass in the initialization scores into the booster.  Currently, it's set to None, which means they'll all be zero.  You'll want to instead create a numpy array that contains the initialization scores and pass that in instead.

https://github.com/interpretml/interpret/blob/9d8d2d4c2cbf4284ddd147592300ce9666a7ca4a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L454

If you are doing pairs, we then calculate the scores predicted by the mains model and boost on top of those.  You'll want to add your scores to the 'scores_bags' variable, which is a list of numpy arrays.  Each outer bag has different scores, so you'll need to add your init scores to each numpy array in this list:

https://github.com/interpretml/interpret/blob/9d8d2d4c2cbf4284ddd147592300ce9666a7ca4a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L499

When predicting, you can use the existing decision_function and add your scores there before calling softmax, or modify the ebm.py code to do so.

**Comment by paulbkoch** [comment]
When you have it working, I'd test it using a regression problem.  As mentioned above, you should be able to get the exact same results in regression by subtracting from y as you would by using init/offset scores.

**Comment by spyrosUofA** [comment]
Hi @paulbkoch,

Is this also doable on the latest stable release (v0.2.7)? I see the code has evolved quite a bit since then, so I’m not sure where I’d make the changes. 

Thanks!

**Comment by paulbkoch** [comment]
Then you want 'scores_train' and 'scores_val':

https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L545

https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L549

https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L588

https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L632

https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L632

**Comment by spyrosUofA** [comment]
Hi @paulbkoch,  

Thank you for your advice. We were able to implement and validate an offset for the EBM classifier and regressor. We’d love to be able to contribute to this great package, so I’ll create a pull request for this shortly. 

Thanks!

**Comment by paulbkoch** [comment]
Thank you @spyrosUofA, that would be a nice contribution  👍

**Comment by paulbkoch** [comment]
For the benefit of those who come to this issue in the future, these PRs are https://github.com/interpretml/interpret/pull/371 and https://github.com/interpretml/interpret/pull/408
