### ISSUE TITLE
PrScore & AcScore

### ISSUE THREAD

**Issue by Jingyan918** [interpretml/interpret#365]
Hi, 

I would like to seek for a further explanation on thread #163.
I had a hard time understanding what does the prediction meant like the one shown below.
![image](https://user-images.githubusercontent.com/84914815/188909189-94197dbb-773c-4ac0-868e-ff38cfad8cc5.png)
Does it mean that the model thinks that the prediction is 98.9% going to be 0 and it turns out the result happened to be the only 1.1% chance? 
What is the correct way of reading the value above?

Thanks.

**Comment by paulbkoch** [comment]
Hi @Jingyan918 -- Yes, this is correct, and I believe this string has been updated to be less confusing in our latest pypi release (0.3.0).
