### ISSUE TITLE
Lookup Table

### ISSUE THREAD

**Issue by TejasPatil80178** [interpretml/interpret#367]
Hi,

This is not an issue but much more of an question.

The output of the EBM model is essentially a lookup table where we have values in the units of target variable 
(regression) or logodds (classification) is there any way to extract the lookup table as an output?

Thanks in advance!

**Comment by paulbkoch** [comment]
Hi @TejasPatil80178 -- The lookup table is the additive_terms_ attribute of the model (for the code on pypi), however before doing the lookup generally you first need to turn continuous and categorical data into a binned representation.  We use the EBMPreprocessor to handle that step.

Code for EBMPreprocessor is here:
https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L129

During prediction, here is where we do the preprocessor transform:
https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/ebm.py#L1246

And then after preprocessing, the lookup is done via numpy indexing:
https://github.com/interpretml/interpret/blob/ba6ba620936d3c0d21d66418b6d8e3a2834e265a/python/interpret-core/interpret/glassbox/ebm/utils.py#L363
