### ISSUE TITLE
"timeout or by a memory leak"

### ISSUE THREAD

**Issue by alicepiller** [interpretml/interpret#375]
When training the explainable boosting classifier on a large dataset with about 12000 predictors, I got this warning:

/opt/exp_soft/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning

I was running it with access to 270GB of RAM. The ebm produced results though. I was able to make predictions, and view the global and local explanations. When analysing the list of top-ranking predictors, it seemed that the model was only trained on the first ~1000 features in the dataset. The performance of the model is also similar to that of a model trained on the first ~1000 features.

Is there a way I can train the model on the full dataset and avoid this memory leak?

**Comment by paulbkoch** [comment]
Hi @alicepiller -- We've done a lot of work to reduce the memory requirements recently, but these memory improvements have not yet made their way to pypi, so you would need to clone and build from source if you have large datasets that are exceeding the memory space.  The improvements are in the order of 10x less memory.

Our docs describe further how to build from source:
https://interpret.ml/docs/installation-guide.html

**Comment by paulbkoch** [comment]
Hi @alicepiller -- We've put out a new release on pypi (0.3.0) which includes the improvements to memory efficiency.  I'm going to close this issue for now, but please re-open it if you're still having problems on the latest release.
