### ISSUE TITLE
Remove Dash-Table from setup.py 

### ISSUE THREAD

**Issue by rxm7706** [interpretml/interpret#383]
dash-table has been depreciated for 
import dash_table as dt
to
from dash import dash_table as dt

Code has been fixed in version 0.3.0
https://github.com/interpretml/interpret/commit/c10b5f76a6f54ed66750fa054956a178536ce2d4
But setup.py still refers to dash_table
https://github.com/interpretml/interpret/blob/f4a3f08cb95c3c99eb389a2a86e4f76a36af3395/python/interpret-core/setup.py#L87

**Comment by paulbkoch** [comment]
Closing this issue since the related PR has been merged.
