### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by onacrame** [interpretml/interpret#385]
There was some discussion some time ago regarding implementation of missing value handling.  Has that progressed any further?

**Comment by paulbkoch** [comment]
Hi @onacrame -- Our global explanation visualizations do not currently show missing values on the graphs, so we currently discourage their use.  We have enabled them during fitting and prediction, but include a warning to alert the user of the graphing issue. If you have missing values in your data we recommend turning them into an extreme value like -1000 that will show appropriately in the current graphs.  Imputing with the mean can lead to difficult to interpret jumps on the graphs at the mean, so we generally discourage that solution for EBMs.  One of the videos on our README from Rich Caruana shows some examples of this.  Alternatively, you can see where on the graphs the missing value would be placed for mains by looking at ebm.term_score_[term_index][0].  The 0th bin is always the missing value bin.

**Comment by onacrame** [comment]
Understood thanks
