### ISSUE TITLE
Conda installation & dash package imports 

### ISSUE THREAD

**Issue by AhmedKhassiba** [interpretml/interpret#393]
Hello,
I installed interpretML through the conda command:
conda install -c interpretml interpret

and I run the code in: https://github.com/deepfindr/xai-series
Function "show" raises this error :
ModuleNotFoundError: No module named 'dash_html_components'
while pointing out line 5 in udash.py:
--> import dash_html_components as html
Clearly, a matter of dash 2.0.

I found this already corrected in the master branch: 
update dash package imports to resolve dash warnings -- Latest commit [c10b5f7] on Nov 16.
(https://github.com/interpretml/interpret/commit/c10b5f76a6f54ed66750fa054956a178536ce2d4)

But, I do not understand why my installation (through conda command) did not get the corrected version of the package.
(I am clearly new to all this ... )
Is this going to be fixed soon ?

Thank you very much for your help.

**Comment by paulbkoch** [comment]
Hi @AhmedKhassiba -- Thanks for reporting this!  We just published a conda-forge package for v0.3.0, which should fix this issue. It can be installed with:
```
conda install -c conda-forge interpret
```
