### ISSUE TITLE
Typo in external link

### ISSUE THREAD

**Issue by antortjim** [interpretml/interpret#394]
[https://www.fiddler.ai/bloga-gentle-introduction-to-ga2ms-a-white-box-model](https://www.fiddler.ai/bloga-gentle-introduction-to-ga2ms-a-white-box-model) is broken and needs to be replaced by [https://www.fiddler.ai/blog/a-gentle-introduction-to-ga2ms-a-white-box-model](https://www.fiddler.ai/blog/a-gentle-introduction-to-ga2ms-a-white-box-model)

**Comment by paulbkoch** [comment]
Hi @antortjim -- I updated the link.  Thanks!
