### ISSUE TITLE
Access to local feature importances

### ISSUE THREAD

**Issue by Monicar77** [interpretml/interpret#396]
Hi,

I have a 8x8 feature set and I would like to plot local feature importance on my grid. 
Where is the data to plot these bars stored?

![image](https://user-images.githubusercontent.com/15229954/211561425-f7f427ee-d1e2-475d-befc-103b8c58d774.png)

Best!

**Comment by paulbkoch** [comment]
Hi @Monicar77 -- Those get generated for a specific sample by calling explain_local on the ebm object.  An example:

```
ebm = ExplainableBoostingClassifier()
ebm.fit(X_train, y_train)
ebm_local = ebm.explain_local(X_test, y_test)
ebm_local.data(0)["scores"] # get the scores from the 1st sample
ebm_local.data(1)["scores"] # get the scores from the 2nd sample
ebm_local.data(2)["scores"] # get the scores from the 3rd sample
```

**Comment by Adesoji1** [comment]
I clicked the unsubscribe button but it's not working. Kindly rectify

**Comment by paulbkoch** [comment]
Hi @Adesoji1 -- I do not have access to the unsubscribe lists of github, so there is no action that I could take to rectify this myself.  I see you are listed as one of the people watching our repo at:  https://github.com/interpretml/interpret/watchers?page=3

Assuming you chose the original defaults when clicking "watch", that means you would receive notifications whenever any issue is updated in our repo.  The "unsubscribe" link in the github emails however just unsubscribes you from the current github issue, so you would still receive messages about other github issues from our repo.

To fully unsubscribe to all messages, you would need to click "unwatch" on our repo.  Once again, I cannot perform this step for you, so you'll need to do it yourself.
