### ISSUE TITLE
Getting string instead of float as output

### ISSUE THREAD

**Issue by yap231995** [interpretml/interpret#402]
Hi, I have been training a few EBM. 

Only one of them giving me string as the output as strings. 

The EBM that has given me string takes in this as the class label with 254 classes.
`[179. 215.  23. ... 173.   8. 227.]`
Each one of it is a `<class 'numpy.float64'>` values 

But after I train it and used predict, it gives me class of strings: 
`['169.0' '213.0' '100.0' ... '124.0' '125.0' '252.0']`

The following is the `ebm._class_idx_`
`_class_idx_:  {'0.0': 0, '1.0': 1, '10.0': 2, '100.0': 3, '101.0': 4, '102.0': 5, '103.0': 6, '104.0': 7, '105.0': 8, '106.0': 9, '107.0': 10, '108.0': 11, '109.0': 12, '11.0': 13, '110.0': 14, '111.0': 15, '112.0': 16, '113.0': 17, '114.0': 18, '115.0': 19, '116.0': 20, '117.0': 21, '118.0': 22, '119.0': 23, '12.0': 24, '120.0': 25, '121.0': 26, '122.0': 27, '123.0': 28, '124.0': 29, '125.0': 30, '126.0': 31, '127.0': 32, '128.0': 33, '129.0': 34, '13.0': 35, '130.0': 36, '131.0': 37, '132.0': 38, '133.0': 39, '134.0': 40, '135.0': 41, '136.0': 42, '137.0': 43, '138.0': 44, '139.0': 45, '14.0': 46, '140.0': 47, '141.0': 48, '142.0': 49, '143.0': 50, '144.0': 51, '145.0': 52, '146.0': 53, '147.0': 54, '148.0': 55, '149.0': 56, '15.0': 57, '150.0': 58, '151.0': 59, '152.0': 60, '153.0': 61, '154.0': 62, '155.0': 63, '156.0': 64, '157.0': 65, '158.0': 66, '159.0': 67, '16.0': 68, '160.0': 69, '161.0': 70, '162.0': 71, '163.0': 72, '164.0': 73, '165.0': 74, '166.0': 75, '167.0': 76, '168.0': 77, '169.0': 78, '17.0': 79, '170.0': 80, '171.0': 81, '172.0': 82, '173.0': 83, '174.0': 84, '175.0': 85, '176.0': 86, '177.0': 87, '178.0': 88, '179.0': 89, '18.0': 90, '180.0': 91, '181.0': 92, '182.0': 93, '183.0': 94, '184.0': 95, '185.0': 96, '186.0': 97, '187.0': 98, '188.0': 99, '189.0': 100, '19.0': 101, '190.0': 102, '191.0': 103, '192.0': 104, '193.0': 105, '194.0': 106, '195.0': 107, '196.0': 108, '197.0': 109, '198.0': 110, '199.0': 111, '2.0': 112, '20.0': 113, '200.0': 114, '201.0': 115, '202.0': 116, '203.0': 117, '204.0': 118, '205.0': 119, '206.0': 120, '207.0': 121, '208.0': 122, '209.0': 123, '21.0': 124, '210.0': 125, '211.0': 126, '212.0': 127, '213.0': 128, '214.0': 129, '215.0': 130, '216.0': 131, '217.0': 132, '218.0': 133, '219.0': 134, '22.0': 135, '220.0': 136, '221.0': 137, '222.0': 138, '223.0': 139, '224.0': 140, '225.0': 141, '226.0': 142, '227.0': 143, '228.0': 144, '229.0': 145, '23.0': 146, '230.0': 147, '231.0': 148, '232.0': 149, '233.0': 150, '234.0': 151, '235.0': 152, '236.0': 153, '237.0': 154, '238.0': 155, '239.0': 156, '24.0': 157, '240.0': 158, '241.0': 159, '242.0': 160, '243.0': 161, '244.0': 162, '245.0': 163, '246.0': 164, '247.0': 165, '248.0': 166, '249.0': 167, '25.0': 168, '250.0': 169, '251.0': 170, '252.0': 171, '253.0': 172, '254.0': 173, '255.0': 174, '26.0': 175, '27.0': 176, '28.0': 177, '29.0': 178, '3.0': 179, '30.0': 180, '31.0': 181, '32.0': 182, '33.0': 183, '34.0': 184, '35.0': 185, '36.0': 186, '37.0': 187, '38.0': 188, '39.0': 189, '4.0': 190, '40.0': 191, '41.0': 192, '42.0': 193, '43.0': 194, '44.0': 195, '45.0': 196, '46.0': 197, '47.0': 198, '48.0': 199, '49.0': 200, '5.0': 201, '50.0': 202, '51.0': 203, '52.0': 204, '53.0': 205, '54.0': 206, '55.0': 207, '56.0': 208, '57.0': 209, '58.0': 210, '59.0': 211, '6.0': 212, '60.0': 213, '61.0': 214, '62.0': 215, '63.0': 216, '64.0': 217, '65.0': 218, '66.0': 219, '67.0': 220, '68.0': 221, '69.0': 222, '7.0': 223, '70.0': 224, '71.0': 225, '72.0': 226, '73.0': 227, '74.0': 228, '75.0': 229, '76.0': 230, '77.0': 231, '78.0': 232, '79.0': 233, '8.0': 234, '80.0': 235, '81.0': 236, '82.0': 237, '83.0': 238, '84.0': 239, '85.0': 240, '86.0': 241, '87.0': 242, '88.0': 243, '89.0': 244, '9.0': 245, '90.0': 246, '91.0': 247, '92.0': 248, '93.0': 249, '94.0': 250, '95.0': 251, '96.0': 252, '97.0': 253, '98.0': 254, '99.0': 255}` 

Is there a bug inside? Because I have trained like 12 different EBM of the same form but only this ebm gives me this output. 
Thanks

**Comment by paulbkoch** [comment]
Hi @yap231995 -- scikit-learn documentation says that y should be either strings or integers ( https://scikit-learn.org/stable/developers/develop.html#specific-models ) and it leaves ambiguous how other types should be handled.  Treating non-integer inputs as strings is a little more JSON friendly, so for now I've opted to treat anything other than integers and bools as strings.  If this trips up enough people though I could be convinced to modify the behavior.

**Comment by yap231995** [comment]
Thank you so much!! I see, i will shape it into integer then. Thanks alot!
