### ISSUE TITLE
Conda unsatisfiable error MacOS

### ISSUE THREAD

**Issue by behzadk** [interpretml/interpret#411]
Hello!

I'm encountering the following error when I try and install with conda:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==12.5.1=0
  - interpret -> ipykernel[version='>=5.1.0'] -> __osx
  - interpret -> ipykernel[version='>=5.1.0'] -> __win

Your installed version is: 12.5.1
```

I'm using `Python 3.9.16` and `conda 23.1.0`. Installing Interpret with pip works fine

Do you have any suggestions for how to get the conda installation working?

**Comment by behzadk** [comment]
Hi Paul, thanks for the quick reply. Yes, no problem we can use pip for now!

**Comment by paulbkoch** [comment]
Hi @behzadk -- I've created a new conda-forge release (v0.3.1) which should resolve this issue.  I don't have a mac m1 to test it on though so if you have a chance to try this fix, please let me know if it's working.

**Comment by behzadk** [comment]
Hi Paul, thanks for setting this up. All working! 👍
