### ISSUE TITLE
Need guidance for use of EBM model for imbalanced data

### ISSUE THREAD

**Issue by puronjoy** [interpretml/interpret#413]
I am using EBM to implement a binary classifier. The positive class label fraction is less than 0.1% of the entire dataset. What settings should I use? Particularly, should I set sample_weight in inverse proportion of the class fraction? What is the default behavior of the model with sample_weight=None?

**Comment by paulbkoch** [comment]
Hi @puronjoy -- Generally EBMs seem to perform well on imbalanced datasets without reweighting.  Having said that, we haven't tried it on a dataset with that amount of imbalance, so we're curious to know how it compares.  I would say try both and if you find something interesting let us know what you find.

**Comment by puronjoy** [comment]
Using a sample weight of 1/sqrt(R) for negative samples, where R is the ratio of the number of negative samples to the number of positive samples, works in my case to provide the best trade-off between TPR and FPR.
