### ISSUE TITLE
Jointly train two EBM models to predict one target

### ISSUE THREAD

**Issue by anlijuncn** [interpretml/interpret#420]
Dear Interpretml team, 

I have 3 features, let's say `x1`, `x2`, `s`; and one target `Y` I want to predict . You can imagine `x1` and `x2` are true covariates, `s` is the variable we want to regress out. 

In the linear model setting, people would like to have a `Y = intercept + x_1\beta_1 + x_2\beta_2 + s\beta_s + eps`. Then the role of `intercept + x_1\beta_1 + x_2\beta_2` would know. 

I want to apply EBM to capture some non-linear information of `x1` and `x2` corresponding to `Y`. Could I jointly optimize two EBM models such as `Y  = EBM_1(x_1, x_2) + EBM_2(s)`? 

I am curious whether it is possible in EBM package or do you have any better suggestions？

Thanks!

**Comment by paulbkoch** [comment]
Hi @anlijuncn -- I'm not sure that I entirely understand your question.  Is this related to https://github.com/interpretml/interpret/issues/420 where you wanted to zero one feature.

One useful property of EBMs, like other GAMs, is that the feature contributions are zero centered such that the average contribution of each feature is zero.  If you were to zero all features in the model, you'd be left with only the intercept, which should generally be very close to the base score.

If you include all the features x_1, x_2, and s in a single EBM, you'll be jointly optimizing them.  Afterward you could split the one model into two models by making a copy, zeroing s in one of them, and zeroing x1 & x2 in the other.

**Comment by anlijuncn** [comment]
Thanks Paul!
