### ISSUE TITLE
Streamlit Provider

### ISSUE THREAD

**Issue by quocdat-le-insacvl** [interpretml/interpret#423]
Hi **InterpretML teams**, 
Thank you very much for the amazing work. 

I’m trying to integrate Global and Local Explainer into my dashboard Streamlit. 
Unfortunately, function `show()` doesn’t have an option returning `HTML raw`, which can be work with **streamlit** using `streamlit.components.v1.html()`

Here is my resolution : 
```python
set_visualize_provider(InlineProvider(detected_envs = ['streamlit']))
```
In function `render()` of `interpret.visual.inline` : 
```python
elif "streamlit" in detected_envs:
    import streamlit.components.v1 as components
    components.html(HTML(init_js + body_js).data, height=1000, width=1000, scrolling=True)
 ```
![image](https://user-images.githubusercontent.com/71183203/229837995-84707399-9a1c-4da8-a6d3-05506b8b77b9.png)

It works perfectly for me. I don’t know if there’s a cleaner way to do this.
Also, I can make PR if you find it can be useful for other people.
Many thanks!
Dat LQ.

**Comment by paulbkoch** [comment]
Thanks @quocdat-le-insacvl for taking the time to report this, and for the clear steps towards solving it.  We would welcome it as a PR if you would like to submit it.

**Comment by paulbkoch** [comment]
Thanks @quocdat-le-insacvl for submitting the PR that addresses this!
