### ISSUE TITLE
 'ExplainableBoostingRegressor' object has no attribute 'objective'

### ISSUE THREAD

**Issue by fdarke** [interpretml/interpret#434]
Hi,

I have installed interpret by simply running

```
pip install interpret
```

According to the documentation found at https://interpret.ml/docs/ebm.html#api , I should be able to specify different objective functions.
However, when I initialize the model with the following code, I get an error:

```
from interpret.glassbox import ExplainableBoostingRegressor
ebm = ExplainableBoostingRegressor(objective = 'poisson')
```
TypeError: __init__() got an unexpected keyword argument 'objective'

I have also tried
```
from interpret.glassbox import ExplainableBoostingRegressor
ebm = ExplainableBoostingRegressor()
ebm.objective
```
, which yields the error
AttributeError: 'ExplainableBoostingRegressor' object has no attribute 'objective'

**Comment by paulbkoch** [comment]
Hi @fdarke -- Version 0.4.0 is published now on pypi and conda-forge.  Hope you find poisson a useful addition.  :-)
