### ISSUE TITLE
Is it possible to save the models in mlflow?

### ISSUE THREAD

**Issue by WEILMAX** [interpretml/interpret#441]
I am currently using XGB Regressors combined with SHAP values and saving the models in mlflow.
I came across the interpretml package and am very eager to give it a try.
I would like to compare the EBM regressor and compare the results to the XGB model on my data!
But I was wondering if these models could be saved in mlflow as flawlessly as XGB models.

I can't find a mlflow.interpretml repository yet and was wondering if this was planned in the near future?

**Comment by paulbkoch** [comment]
HI @WEILMAX -- I haven't tried mlflow myself, but I've seen an issue from someone who was using EBMs in mflow, so I believe it should work using the default cloudpickle serializer.  Can you give it a try and let us know?
