### ISSUE TITLE
UnboundLocalError: local variable 'highest_idx' referenced before assignment

### ISSUE THREAD

**Issue by schfluri** [interpretml/interpret#446]
Hi,

I am using a feature matrix with 344 features and want to train an EMB as shown below, which leads to the error. It seems that I get this error whenever feature 0 is not included either as a single feature or as an interaction.

```
interactions = [(170, 342), (171, 343)]
exclude = list(range(0,344))
ebm = ExplainableBoostingClassifier(interactions=interactions, exclude = exclude, max_rounds = max_rounds, learning_rate = learning_rate)
```

Thanks for your help.

**Comment by YaminiKhajekar** [comment]
The error you're encountering seems to be related to the exclude parameter you're passing to the ExplainableBoostingClassifier constructor. The exclude parameter is used to specify the indices of features that should be excluded from the model training process. In your case, you are excluding all features by providing list(range(0, 344)), which includes all indices from 0 to 343.

If you want to exclude feature 0 and use all other features, you should remove exclude from the constructor or modify it to exclude only feature 0. Here's an example of how you can modify your code:

i```
nteractions = [(170, 342), (171, 343)]
exclude = [0]  # Exclude feature 0
ebm = ExplainableBoostingClassifier(interactions=interactions, exclude=exclude, max_rounds=max_rounds, learning_rate=learning_rate)
```
By providing exclude = [0], you exclude only feature 0 from the training process, and all other features will be used in the model. This should resolve the error you were encountering when feature 0 was not included.

**Comment by schfluri** [comment]
@ YaminiKhajekar, thanks for your reply!

I might not have described the issue well enough: I do want to exclude all single features and only use the interaction between 170, 342 and 171, 343. Which is when I get the error (see full error message below).

The thing with feature 0 is only an observation I made while trying to debug, which might not be at the core of the issue. I.e. the following two examples, where feature 0 is in the model, do not produce an error.
`interactions = [(0, 342), (171, 343)]; exclude = list(range(0,344))`
`interactions = [(171, 342), (171, 343)]; exclude = list(range(1,344))`

However those examples, where feature 0 is excluded, produce the error:
`interactions = [(171, 342), (171, 343)]; exclude = list(range(0,344))`
`interactions = [(171, 342), (171, 343)]; exclude = [0]`


```UnboundLocalError Traceback (most recent call last)
Cell In[2], line 79
77 # train ebm
78 ebm = ExplainableBoostingClassifier(interactions=interactions, exclude = exclude, max_rounds = max_rounds, max_leaves = max_leaves, learning_rate = learning_rate)
---> 79 ebm.fit(X_train, y_train)
81 y_pred_train = ebm.predict(X_train)
82 print("______________")

File ~/anaconda3/envs/test/lib/python3.9/site-packages/interpret/glassbox/_ebm/_ebm.py:1128, in EBMModel.fit(failed resolving arguments)
1125 breakpoint_iteration = np.array(breakpoint_iteration, np.int64)
1127 remove_unused_higher_bins(term_features, bins)
-> 1128 deduplicate_bins(bins)
1130 bagged_scores = (
1131 np.array([model[idx] for model in models], np.float64)
1132 for idx in range(len(term_features))
1133 )
1135 term_features, bagged_scores = order_terms(term_features, bagged_scores)

File ~/anaconda3/envs/test/lib/python3.9/site-packages/interpret/glassbox/_ebm/_utils.py:314, in deduplicate_bins(bins)
312 highest_key = key
313 highest_idx = level_idx
--> 314 del bin_levels[highest_idx + 1 :]

UnboundLocalError: local variable 'highest_idx' referenced before assignment```

**Comment by paulbkoch** [comment]
Hi @schfluri and @YaminiKhajekar -- Thanks for the nice bug report and discussion.  There was indeed a bug that was being expressed when feature 0 was excluded from the model.  This has been fixed in https://github.com/interpretml/interpret/commit/bd758e549f1f567439c8de453db9d9aeb54c1456 and will be included in our next release.  I've also added a test to check this scenario going forward.

**Comment by paulbkoch** [comment]
And release 0.4.3 is out now with this fix.
