### ISSUE TITLE
Global explanation in multiclass

### ISSUE THREAD

**Issue by Saurid3** [interpretml/interpret#448]
I tried my multiclass data on EBM using Jupiter notebook and obtained the following result when I called Global explanation(see Fig below), Where FN is the feature and 0, 1, 2, and 3 are classes, 0 indicates no danger, 1 indicates slight danger, 2 indicates moderate danger and 3 indicates extreme danger.  
![image](https://github.com/interpretml/interpret/assets/138742578/525b302e-290d-473f-b663-1d5f1b601e98)

So this is how I explained:
When FN is less, the possibility of occurring 3 and 4 is also less. FN lesser than 10 risk of 0 and 1 is more likely to occur; however, when the FN value increases from 10 to more, the risk of 2 and 3 are rising. As the FN escalates more, which is 30 or above, the risk of 3 is very high.

Is this the correct way to describe it? In binary classification, we only have a single curve, which is easily interpreted by observing rising and falling; however, in multiclass, while one class increases, another might decrease. 

The answers will be helpful to all who need clarification about how to explain multiple curves from the same graph.

**Comment by paulbkoch** [comment]
Yes, that sounds reasonable to me.  The risk of #2 goes down after the short rise above 10, and I think you meant #2 and #3 instead of #3 and #4, but I agree with the rest.

**Comment by Saurid3** [comment]
Thank you for pointing this out; my bad; yes, it is 2 and 3 instead of 3 and 4. This algorithm is too good and very helpful in understanding the model's decision. This is the best algorithm I have ever used.

**Comment by paulbkoch** [comment]
Thanks @Saurid3.  Glad to hear you're finding EBMs useful.   👍 

Closing this issue for now.  If you have any other questions, please re-open.
