### ISSUE TITLE
Training EBM on class-imbalanced datasets

### ISSUE THREAD

**Issue by JWKKWJ123** [interpretml/interpret#449]
Hi all,
I trained EBM on some class-imbalanced datasets (for binary classification on diseases, around 200 positive subjects and 600 negative subjects). The predicted results yielded a high AUC score, but highly imbalanced sensitivity and specificity (same as recall and precision). For example, the results showed 95% specificity, and 20% sensitivity, which means the model predicted most subjects as negative.
I would like to ask is there some ways to deal with the class-imbalance? For example, giving different weights to each class when training EBMs.
Many thanks,
Wenjie Kang

**Comment by richcaruana** [comment]
In general EBMs work well with moderate class imbalance and should have no trouble with data that is 10:1 or even 100:1 imbalanced as long as you have adequate sample size for each of the classes.  I think the 95% specificity and 20% sensitivity are just telling you more about the predictability of your problem, than about a class imbalance issue.  EBMs tend to predict well-calibrated probabilities despite modest class imbalance, and therefore a threshold of 0.5 is probably a good place to start for separating predicted positives from predicted negatives, but you can, of course, move the threshold up and down from 0.5 if you prefer to predict more positives or negatives.  Often what we do is look 1st at the AUC, and if it is as good as the AUC of an other model trained with other learning methods or trained with data that has artificially been rebalanced, the it is good to use the original model on the original data and just change threshold to suit your cost function for false positives and false negatives, i.e., the costs you assign to the 4 cells in the contingency table.  

Hope this helps.  Get back to us if you have more questions.

**Comment by JWKKWJ123** [comment]
> In general EBMs work well with moderate class imbalance and should have no trouble with data that is 10:1 or even 100:1 imbalanced as long as you have adequate sample size for each of the classes. I think the 95% specificity and 20% sensitivity are just telling you more about the predictability of your problem, than about a class imbalance issue. EBMs tend to predict well-calibrated probabilities despite modest class imbalance, and therefore a threshold of 0.5 is probably a good place to start for separating predicted positives from predicted negatives, but you can, of course, move the threshold up and down from 0.5 if you prefer to predict more positives or negatives. Often what we do is look 1st at the AUC, and if it is as good as the AUC of an other model trained with other learning methods or trained with data that has artificially been rebalanced, the it is good to use the original model on the original data and just change threshold to suit your cost function for false positives and false negatives, i.e., the costs you assign to the 4 cells in the contingency table.
> 
> Hope this helps. Get back to us if you have more questions.

Thank you so much for your reply! I would like to try to find the optimal threshold in the validation set based on one metric.
