### ISSUE TITLE
Linux/Arm64 platform support

### ISSUE THREAD

**Issue by pbrady32** [interpretml/interpret#451]
Hello,

Our team is doing some development work on M1 Macs using Docker. I believe Docker runs in a Linux virtual machine when installed on ARM-based Macs, so the platform for the created Docker images essentially becomes Linux/Arm64. However, looking through the code it appears that this platform config is not supported. 

https://github.com/interpretml/interpret/blob/e7a1304cc12d1344fa4403f4321ac24e3fd97a47/python/interpret-core/interpret/utils/_native.py#L624

When I install interpret in a Docker container (using Python 3.9.17 as base image layer), the installation completes successfully. However, when I try to actually run models I get the following error:

INFO:interpret.utils._native:EBM lib loading.
INFO:interpret.utils._native:Loading native on Linux | debug = False
ERROR:interpret.utils._native:System Linux, platform aarch64, bitsize 64 not supported for EBM

Thank you!

**Comment by Adesoji1** [comment]
Wow, 😳,I will like to see what I can do to resolve the issue

**Comment by pbrady32** [comment]
Thank you!

**Comment by paulbkoch** [comment]
Hi @Adesoji1 & @pbrady32 -- 

The PyPI installation doesn't currently handle this, but the conda installation should support aarch64, at least that's the theory.  Conda-forge is currently compiling a binary that should do this, but I don't have a mac to test it on, and @pbrady32 you would be the first I've heard of trying it out.

The conda version can be installed with:
```
conda install -c conda-forge interpret
```

@Adesoji1, it would still be great to get this to work on PyPI if you're still interested.  To make it work, the first thing that would need to happen would be to compile a Linux ARM specific shared library.  We do that currently for mac, but not Linux.  Here's the relevant section for macs:
https://github.com/interpretml/interpret/blob/e7a1304cc12d1344fa4403f4321ac24e3fd97a47/build.sh#L698-L753

And it would need to be modified for Linux and inserted here:
https://github.com/interpretml/interpret/blob/e7a1304cc12d1344fa4403f4321ac24e3fd97a47/build.sh#L610

Then the python section that @pbrady32 pointed out would need to be modified to load the new shared library .so file.

**Comment by pbrady32** [comment]
@paulbkoch Thanks so much for the response. I'll give that a shot. 

One other thing I'm thinking of doing is trying to create a "interpret-slim" version to help reduce the size of my Docker images. I basically just need the modeling functionality and can remove all of the visualization pieces. Not sure how much I would be able to remove, but the use case here is that I'm building a container that runs on Google Cloud Run and this serves as an ML project API endpoint.

**Comment by pbrady32** [comment]
@paulbkoch Oh awesome! That will make things a lot easier. I was mainly working off of the getting started guide, so I didn't even see that option. Thanks for pointing that out. 

https://interpret.ml/docs/getting-started.html
