### ISSUE TITLE
[Question] Would it be possible to make a v0.4.3 release?

### ISSUE THREAD

**Issue by cesar-perceiv** [interpretml/interpret#457]
Hello there,

First of all, thank you for all the great work!
Since commit d32ec73, `interpret-core` does not impose restriction on the maximum version number for `numpy` (as `shap` has fixed its issues with `numpy`). Would it be possible to publish a new release of `interpret-core`? It would greatly help with conflicting dependencies on `numpy`!

Thanks!

**Comment by paulbkoch** [comment]
Hi @cesar-perceiv -- Sounds like a good idea.  I need to complete some quality check from other recent changes, and put in one or two minor additional features, but we should be good for a release shortly.  What's the time criticality of this on your end?

**Comment by paulbkoch** [comment]
Hi @cesar-perceiv -- The 0.4.3 release is out!
