### ISSUE TITLE
How to calculate predictive probability for each class from log odds from local explanation

### ISSUE THREAD

**Issue by Saurid3** [interpretml/interpret#461]
![image](https://github.com/interpretml/interpret/assets/138742578/bbb355f1-1d02-4e78-a448-313692c164e8)
Image source: S. Jayasundara, A. Indika and D. Herath, "Interpretable Student Performance Prediction Using Explainable Boosting Machine for Multi-Class Classification," 2022 2nd International Conference on Advanced Research in Computing (ICARC), Belihuloya, Sri Lanka, 2022, pp. 391-396

This is a multiclass classification result for EBM, the left rows represent features and columns represent classes. How to calculate predictive probability for each class from those log odds? As I used this formula but not getting the result (probability = 1 / (1 + exp(-log_odds))), Anybody can help with this how EBM calculates predictive probability for each class in multiclass classification problem?? I'm totally confused in this.

**Comment by paulbkoch** [comment]
Hi @Saurid3 -- For multiclass use the softmax function.  Our documentation contains a complete example of how to calculate the multiclass probabilities from scratch without the interpret package:  https://interpret.ml/docs/ebm-internals-multiclass.html

**Comment by paulbkoch** [comment]
Closing this issue for now.  Feel free to reopen if there are more questions.
