### ISSUE TITLE
This link (Notebook for reproducing table) is not working

### ISSUE THREAD

**Issue by wenlongliaoEE** [interpretml/interpret#464]
Hi. On your homepage (https://github.com/interpretml/interpret), after you introduced "Introducing the Explainable Boosting Machine (EBM)", you showed a computational result of each model on different datasets, including Adult Income,Heart Disease,Heart Disease,Telecom Churn, and Credit Fraud. 
Finally, you gave a link(Notebook for reproducing table) to reproduce these results, but I found that this link is not working. Could you give this link again?

Thanks.

**Comment by paulbkoch** [comment]
Thanks @wenlongliaoEE -- I've corrected the link in our readme.  The notebook can be found at:

https://nbviewer.org/github/interpretml/interpret/blob/main/benchmarks/EBM_Classification_Comparison.ipynb
