### ISSUE TITLE
Booster Object

### ISSUE THREAD

**Issue by alexgcsa** [interpretml/interpret#480]
Hello,

Is there any way to get the Booster object (or sklearn-like model object) from ExplainableBoostingClassifier?

I am currently trying to get the SHAP values based on ExplainableBoostingClassifier, but I can't get it to do this...This is more for the sake of comparing to other methods.

Any version where this is possible?

Thank you.

Best,

Alex

**Comment by paulbkoch** [comment]
Hi @alexgcsa -- The ExplainableBoostingClassifier object is an sklearn-like model itself and you can pass it to SHAP directly.  There's an example of how to do this in Christoph Molnar's new book:

https://github.com/christophM/shap-book/blob/6d0c719823818d97fed79f9e522ba4bd2e5523d9/manuscript/additive.qmd#L45

**Comment by alexgcsa** [comment]
Thank you very much, @paulbkoch :)

It worked fine with this example.

Best,

Alex
