### ISSUE TITLE
how to graph without spinning a local web-server

### ISSUE THREAD

**Issue by jyipks** [interpretml/interpret#52]
Is this API available yet? We cant seem to plot it locally with plotly offline.

Hi @dfrankow, thanks for the issue! We're just about to introduce a few new API changes that should make this easier in our next release. One, we'll let you specify a port in the show method, so that you can pick your own port that you know is open. Second, we'll introduce a new function that doesn't spin up the local web-server, and directly uses plotly to visualize it. For now, here are a few notes: 

visualize() does return a plotly object, and you can use plotly.offline so that you don't need an api key. And yes, if you pass in a key to visualize() , you can get a specific graph back out!

If you run this code at the top of your notebook: 

```
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
```

you can then use "iplot(plotly_figure)" in your notebook to get a direct plotly graph. We'll have a nicer API around this soon!

_Originally posted by @interpret-ml in https://github.com/microsoft/interpret/issues/1#issuecomment-490291898_

**Comment by interpret-ml** [comment]
Hi @jyipks - thanks for the issue,

There's two ways as mentioned. For the first where the web server needs to be spun up but at a specific address there's this:
```python
from interpret import set_show_addr

set_show_addr(('127.0.0.1', 7001))

show(explanation)  # Will run on 127.0.0.1/localhost at port 7001
```

**However if you don't want to spin up the web server at all**, you won't get the dashboard but you can still plot the graphs with the `preserve` method as such:
```python

# Replace show with the preserve.

ebm_global = ebm.explain_global(name='EBM')
# show(ebm_global)

from interpret import preserve
# preserve(ebm_global, 'Age', file_name='global-age-graph.html')
preserve(ebm_global, 'Age')
```

Currently `preserve` is a stop-gap measure, in the future we'll try to have the `show` method handle environments where its either impossible or not agreeable to run a web server.

**Comment by peractio** [comment]
`preserve ` doesn't seem to work for me

I get this:
`preserve(ebm_global, 'AGE')`

```
Traceback (most recent call last):

  File "<ipython-input-7-8853547f25d1>", line 1, in <module>
    preserve(ebm_global, 'AGE')

  File "...\lib\site-packages\interpret\visual\interactive.py", line 196, in preserve
    raise e

  File "...\lib\site-packages\interpret\visual\interactive.py", line 180, in preserve
    key = series[series == selector_key].index[0]

  File "...\lib\site-packages\pandas\core\indexes\base.py", line 4273, in __getitem__
    return getitem(key)

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by peractio** [comment]
Is it possible to retrieve the "Summary" page?

For example:
```
preserve(ebm_global)
```

**Comment by peractio** [comment]
Just a note, preserve also allows locating via the index besides the column name. Especially useful for local interpretations
```
preserve(ebm_local, 0, file_name='example0.html')
```

**Comment by trungngv** [comment]
@interpret-ml  has this issue been fixed yet?

**Comment by interpret-ml** [comment]
Hi @trungngv, 

We do have a better workaround than the preserve method. If you run the following code at the top of your notebook:

```python
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

Interpret will start rendering visualizations directly in Javascript, and embed them directly in the notebook. You can then use the ```show``` method the exact same way as before, but without the strong dependency on an additional web server. Ex:

```python
ebm_global = ebm.explain_global()
show(ebm_global) # Works without a web server if set_visualize_provider() was run earlier
```

Please let us know if this works for you!

-InterpretML Team

**Comment by jyipks** [comment]
I attempted this on version 0.1.19 and I got the following, am I missing something?
ModuleNotFoundError: No module named 'interpret.provider'

**Comment by interpret-ml** [comment]
Hi @jyipks, 

That's interesting. Can you try the following?

```bash
pip uninstall interpret
pip uninstall interpret-core
```

and then run 

```bash
pip install interpret
```

Effectively reinstalling the interpret library. We've seen this in rare cases where upgrading interpret from older versions can cause issues.

**Comment by trungngv** [comment]
@interpret-ml yes, thanks for the for quick fix. This is working for me now except a separate issue related to IOpub data rate, which seems to be due to dash. This stackoverflow question has the fix: 
https://stackoverflow.com/questions/43288550/iopub-data-rate-exceeded-in-jupyter-notebook-when-viewing-image

**Comment by interpret-ml** [comment]
Hi @trungngv --

Great to hear it's working, and it looks like the other issue is resolved per the stackoverflow thread.

-InterpretML team
