### ISSUE TITLE
Lookup Table for single feature and feature interaction terms

### ISSUE THREAD

**Issue by sauvikd** [interpretml/interpret#530]
![Screenshot 2024-04-19 035202](https://github.com/interpretml/interpret/assets/50850346/2c2e1932-0845-4979-8769-d74790bcb3bf)

How can I extract a lookup table for the red-line (score values for the each of the features) and similarly the data for the heatmap.

I had tried downloading the ebm_global.data(1)['scores'], but those are values for each of the bins, from what I understand. Even if I'm able to extract the bin boundary values, I will be able to connect them with the feature values.

**Comment by paulbkoch** [comment]
Hi @sauvikd --

One of the very nice things about EBMs, and GAMs in general, is that the scores are used when calculating the predictions AND what are shown on the graphs.  EBMs have no hidden information.

For graphing though, you also need the "bins" attribute, which for continuous features are the locations on the X-axis where the bin transitions occur.

There's some code which creates graphs here: https://github.com/interpretml/interpret/issues/325

And you might also find our documentation on EBM internals useful: https://interpret.ml/docs/ebm-internals-regression.html

**Comment by sauvikd** [comment]
Thank you so much @paulbkoch for answering my query. It helped me solve my problem.

There's a 2nd part of my query if you can answer my query. Although I can retrieve the individual feature importance plots showing scores using the following piece of code.
`for feature_idx, feature in enumerate(best_ebm_model.term_names_):
        iplot(ebm_global_explainer.visualize(feature_idx))`

How can I separately plot the - EBM Summary Global Importance bar plot, like the one below?
![image](https://github.com/interpretml/interpret/assets/50850346/b52d580b-847c-40b3-8477-fddd165a1936)

**Comment by paulbkoch** [comment]
Hi @sauvikd -- 

We usually recommend the show function:
show(ebm_global_explainer)

But, if you want to use iplot, try this:
iplot(ebm_global_explainer.visualize(None))

**Comment by sauvikd** [comment]
Thanks @paulbkoch, it worked for me.
I was looking to save these images without manually taking a screenshot.

**Comment by paulbkoch** [comment]
Glad to hear this worked @sauvikd.  Closing this issue then.
