### ISSUE TITLE
Exporting EBM as PMML

### ISSUE THREAD

**Issue by lukedex** [interpretml/interpret#536]
Hi all,

Has anyone had success or know of a way to export an EBM as PMML?

I can see external support to output as ONNX or SQL format but I'm struggling to find a way to export as PMML. I've looked at some of the sklearn exporting options as I thought this way be a way forward but have failed on those.

Thanks

**Comment by paulbkoch** [comment]
Hi @lukedex -- I'm not aware of a PMML exporter for EBMs and a search on github for "explainable boosting" PMML yields no results, so if there is one it's very well hidden.

Given the development needs in other areas I probably won't work on this myself in the near term, but I'll leave it in our backlog, and would welcome a PR if anyone would like to contribute such an exporter.

**Comment by vruusmann** [comment]
[SkLearn2PMML](https://github.com/jpmml/sklearn2pmml) versions 0.108.0 and newer support all InterpretML glassbox estimators, including the `ExplainableBoostingClassifier` and `ExplainableBoostingRegressor` estimator classes.

Here's a demo:
``` python
from interpret.glassbox import ExplainableBoostingClassifier
from sklearn2pmml import sklearn2pmml

classifier = ExplainableBoostingClassifier(random_state = 13)
classifier.fit(X, y)

sklearn2pmml(classifier, "EBM.pmml")
```

So, I believe this issue can be closed as "fixed" now.

**Comment by paulbkoch** [comment]
Thank you @vruusmann, that’s great news!

Closing the issue.
