### ISSUE TITLE
Feature Request: Passing Validation Set or Index

### ISSUE THREAD

**Issue by brandongreenwell-8451** [interpretml/interpret#539]
I know you can set the `validation_size` param for early stopping, etc. but it would be nice to be able to pass in an explicit validation set (or maybe even just an index would be easier) to specify the explicit rows to use for validation. Idea is to avoid leakage when you have grouped or time ordered data, etc. Any thoughts?

**Comment by paulbkoch** [comment]
Hi @brandongreenwell-8451 -- This parameter exists!  Check out the "bags" parameter on the fit function:

https://interpret.ml/docs/python/api/ExplainableBoostingClassifier.html#interpret.glassbox.ExplainableBoostingClassifier.fit

**Comment by brandongreenwell-8451** [comment]
Thanks @paulbkoch, I completely missed this!!
