### ISSUE TITLE
Dashboard API

### ISSUE THREAD

**Issue by mosew** [interpretml/interpret#57]
Hi all,

Thanks so much for your work on this package! 

Here I'm requesting a Dashboard API -- maybe just a more transparent interface with the Dash backend so I can customize how the predictions and explanations are served. For example, I want to serve/access individual local explanations as .png's remotely by using some row ID. If this can be done easily on my end, please excuse my bothering you all!

**Comment by mosew** [comment]
Another example of something I'd like to do: omit intercept from local predictions.

**Comment by interpret-ml** [comment]
Hi Mose, 

Nice to hear from you! We're currently working on upgrading our dashboard system, which might make your request a bit easier. This should happen within the next few releases of interpret -- we will update this issue when we make the release!

It is possible to show local prediction plots without the intercept today. 

If you call the standard ```explain_local()``` function:
```python
ebm_local = ebm.explain_local(X_test[:5], y_test[:5])
show(ebm_local)
```
you'll get a graph with intercepts by default.

![image](https://user-images.githubusercontent.com/50031429/64898415-ed0d5800-d63b-11e9-9be7-13c2f6476969.png)

However, you can run this small code snippet to strip intercepts from the explanation objects:

```python
ebm_local = ebm.explain_local(X_test[:5], y_test[:5], name='EBM')
for explanation in ebm_local._internal_obj['specific']:
    del explanation['extra']
show(ebm_local)
```
which will render all local explanations without intercepts.

![image](https://user-images.githubusercontent.com/50031429/64898485-25149b00-d63c-11e9-978f-51f0d595cbcc.png)

Hopefully that helps with your immediate concern!

-InterpretML Team

**Comment by mosew** [comment]
Awesome! Thank you.
