### ISSUE TITLE
Installation from the source

### ISSUE THREAD

**Issue by tatianapolush** [interpretml/interpret#572]
Hello interpret team,

We discovered that you realized a new version with regularization parameters reg_alpha, reg_lambda, and we are looking forward to test it. I followed your guideline from https://interpret.ml/docs/installation-guide.html and cloned the 'develop' branch. It seems that 'make install' works with few warnings, no errors, but these warnings are regarding libebm. Afterwards tests are failed, since it is not possible to find libebm. Could you please guide us how to fix it? 
My OS is Ubuntu, 20.04.5. 

Thank you very much.

**Comment by paulbkoch** [comment]
Hi @tatianapolush -- I should really update that documentation.  To build libebm on linux, simply call build.sh in the root directory of the project.

I've also put out a new release that has the regularization parameters.
