### ISSUE TITLE
Classification init_score

### ISSUE THREAD

**Issue by sadsquirrel369** [interpretml/interpret#583]
How does the init score work for the classifier?

When not passing a model, do you need to pass the result of model.predict_proba(X) ?  or model.predict(X)?

Kind Regards

**Comment by paulbkoch** [comment]
For ExplainableBoostingClassifier, model.predict_proba(X)

**Comment by RustyKobie** [comment]
Cool, so basically I can pass through an array of arrays as the init score?

**Comment by sadsquirrel369** [comment]
Cool, so I can pass an array of arrays as the init score?
