### ISSUE TITLE
SciPy Version Issue 

### ISSUE THREAD

**Issue by oeschsec** [interpretml/interpret#588]
from interpret.glassbox import ExplainableBoostingClassifier

ImportError: cannot import name 'line_search_wolfe2' from 'scipy.optimize.linesearch'

Is it necessary to downgrade scipy to fix this or should this not be an issue? Currently 1.14.1

**Comment by paulbkoch** [comment]
Hi @oeschsec -- To me, it looks like there is an underlying issue in scipy.  My solution has been to remove scipy as a required dependency of interpret.  I'll publish the new package (v0.6.7) in the next hour or so.

**Comment by oeschsec** [comment]
Sounds good - many thanks
