### ISSUE TITLE
Error when calling .fit() on ExplainableBoostingRegressor with sklearn 1.6

### ISSUE THREAD

**Issue by theturpinator** [interpretml/interpret#589]
With the [introdction of tags](https://scikit-learn.org/1.6/developers/develop.html#estimator-tags) in the newest version of sklearn, I'm receiving "'super' object has no attribute '__sklearn_tags__'" when calling .fit() on ExplainableBoostingRegressor.

**Comment by theturpinator** [comment]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/0ad8f36a-dffa-49d8-add5-b9311200702f">

**Comment by paulbkoch** [comment]
This should be fixed with v0.6.8, which is now released.
