### ISSUE TITLE
Azure ML Notebook VM support

### ISSUE THREAD

**Issue by konabuta** [interpretml/interpret#74]
I tried to run interpret on Notebook VM of Azure Machine Learning service. But it says "127.0.0.1 refused to connect". Any workaround on this ?

Regards,
Keita

**Comment by interpret-ml** [comment]
Hi Keita,

What version of interpret are you running on? You can find it by running `pip show interpret` in console.

In interpret 0.1.17+, there's elementary support for cloud environments but we might not have detected Azure ML notebooks correctly.

If upgrading to 0.1.17+ doesn't solve your problem, try putting this at the top of your code.
```python
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

Let us know if you have any more problems/questions!

**Comment by konabuta** [comment]
I upgraded and can run successfully except "Tree visualization" and "Dashboard" that said "_xxx not yet supported in the cloud environment_".  If there's any roadmap information publicity available, please let me know. Thanks.

**Comment by nesty13t** [comment]
> I upgraded and can run successfully except "Tree visualization" and "Dashboard" that said "_xxx not yet supported in the cloud environment_". If there's any roadmap information publicity available, please let me know. Thanks.

Have you solved this problem? I meet same problem, Thanks

**Comment by interpret-ml** [comment]
Hi @nesty13t, 

Unfortunately the libraries we depend on for the Tree Visualization and Dashboard are incompatible with the requirements of some cloud environments. Enabling full support for these two visualizations requires a re-write in a new framework, so we haven't made much progress on it. We're focused on supporting the rest of our visualizations in cloud environments at the moment, and while it is on our backlog to rewrite the tree and dashboard, it most likely won't be supported for the next few months. 

-InterpretML Team

**Comment by rodrigovssp** [comment]
#up


Em sex., 30 de out. de 2020 às 13:43, InterpretML <notifications@github.com>
escreveu:

**Comment by paulbkoch** [comment]
I think given other priorities and the large amount of work required to re-write this, I'll mark the tree and dashboard work as wontfix for cloud environments.
