### ISSUE TITLE
pip install Error (pyscaffold) (Re-Open issue #58)

### ISSUE THREAD

**Issue by MissaouiAhmed** [interpretml/interpret#75]
Python 3.6
hello when i run

pip install  -U interpret
i had the following error
Could not find suitable distribution for Requirement.parse('pyscaffold<3.1a0,>=3.0a0')

so i dowgraded the pyscaffold package version as required

pip install pyscaffold==3.0.0
then i tried to install again
i got

pyscaffold.exceptions.OldSetuptools: Your setuptools version is too old (<30.3.0). Use `pip install -U setuptools` to upgrade.
the probelme is that my setuptools version is 41.2.0

I am using Linux Os 

thanks for help

**Comment by interpret-ml** [comment]
Hi @MissaouiAhmed - thanks for re-opening.

We're actively looking into this, will let you know when we have updates on this.

**Comment by interpret-ml** [comment]
Hi @MissaouiAhmed --

Our recent releases of Interpret should have resolved this issue.  Please reopen if this if it's still a problem.

-InterpretML team
