### ISSUE TITLE
how to add function in c++ and expose it to python?

### ISSUE THREAD

**Issue by chakpongchung** [interpretml/interpret#76]
What is the python binding being used? pybind11 or something else?

**Comment by interpret-ml** [comment]
Hi @chakpongchung --

We use ctypes.  Here's a quick guide for adding a new C++ function.  I'll assume that you're adding this new C++ function into one of the existing .cpp files.  It's probably best to look at how a simple example like the "FreeTraining" function works.  Most of the existing C++ entry points are in one of two files: Training.cpp or InteractionDetection.cpp.

- near the top of your .cpp file, you should include the header "ebmcore.h", if not already included
- write your new C++ entry point function and preface it with "EBMCORE_IMPORT_EXPORT_BODY double EBMCORE_CALLING_CONVENTION".  The "double" part can be replaced with a different return type if you'd prefer.  Here's a simple example:
```
EBMCORE_IMPORT_EXPORT_BODY double EBMCORE_CALLING_CONVENTION func(double val) { return val; }
```
- add your function name to the ebmcore.def file.  This makes the C++ function visible to python in  Windows
- add your function name to the ebmcore_exports.txt file.  This makes the C++ function visible to python in Linux/BSD variants (including mac)
- depending on your OS, run either build.bat or build.sh to compile your new library
- if there were no compilation errors, check in the directory ./python/interpret-core/interpret/lib/ for a newly built library file, which will start with "lib_ebmcore_"
- open the internal.py file and add a function signature in python that matches your C++ function signature.  If these don't match exactly, you'll probably get a segfault when you run it.  Hopefully one of the existing functions in internal.py provides enough of an example to get you going.

-InterpretML team
