### ISSUE TITLE
Do I have to add a lib_ebmcore_*.dll in the file by myself?

### ISSUE THREAD

**Issue by Davidsirui** [interpretml/interpret#77]
Dear Interpretable ML team at MS:

I was trying to run your code, but when I always get a OSError: [WinError 126] said that it cannot find a .dll file. I wonder whether I have to manually generate a .dll file using the core code, or your project can generate a .dll file by itself?

Waiting for you reply and appreciate your work!
Thanks!

**Comment by Davidsirui** [comment]
BTW, I didn't use your api because I just wanna use your implementation of EBM as my backend model. So are there some operations that you have done to generate a .dll file using the C++ core when the user just use your API?

**Comment by interpret-ml** [comment]
Hi @Davidsirui, 

Yes, you can generate a .dll manually through just the build scripts in the directory. However, the .dll doesn't contain the full EBM algorithm. Significant portions of the algorithm are implemented in the higher level Python library, and the core only contains the performance critical code for now. 

> I didn't use your api because I just wanna use your implementation of EBM as my backend model.

Makes sense! Something that might help you is that you can install just EBM -- without any of the other dependencies in Interpret, like visualization, other algorithms, etc. -- through PyPi. We have a lower level library called interpret-core which houses the core algorithms. 

To install just EBM, try this:

```bash
pip install interpret-core[required,ebm]
```

You can then use EBM the same way as usual (initialize, fit, predict, explain_global, etc.):

```python
from interpret.glassbox import ExplainableBoostingClassifier
```

but note that some functionality like graph visualization won't work, as the necessary libraries wouldn't have been installed. We've found this minimal-dependency interface to be helpful for deployment scenarios.

If the lightweight interface isn't sufficient, you can run the [build.bat](https://github.com/microsoft/interpret/blob/master/build.bat) file to generate the .dll. You'll need to have the Visual Studio compiler (the free community edition will be enough). But it's highly recommended to go through the Python interface to get access to the complete algorithm. 

Let us know if you have any further questions!

-InterpretML Team

**Comment by Davidsirui** [comment]
Thanks for the reply! I will try and give you team some feed back! You guys did a really impressive work.
