### ISSUE TITLE
Cited paper to GA2M is wrong?

### ISSUE THREAD

**Issue by OpenJNY** [interpretml/interpret#79]
## Issue

In `README.md`, there's a sentence as bellow:

> <a name="ebm-footnote">*</a> *EBM is a fast implementation of GA<sup>2</sup>M. Details on the algorithm can be found [here](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/KDD2015FinalDraftIntelligibleModels4HealthCare_igt143e-caruanaA.pdf).*

```
<a name="ebm-footnote">*</a> *EBM is a fast implementation of GA<sup>2</sup>M. Details on the algorithm can be found [here](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/KDD2015FinalDraftIntelligibleModels4HealthCare_igt143e-caruanaA.pdf).*
```

In the above sentence, the paper "Intelligible Models for HealthCare: Predicting Pneumonia Risk and Hospital 30-day Readmission" is cited as details about the algorithm.
However, the cited paper just describes applications of GA2M, not about the details, and I think the original paper that actually proposed GA2M in 2013 by Yin Lou, et al. should be linked.

## What to be

Use `http://www.cs.cornell.edu/~yinlou/papers/lou-kdd13.pdf` instead of the current link.

```
<a name="ebm-footnote">*</a> *EBM is a fast implementation of GA<sup>2</sup>M. Details on the algorithm can be found [here](http://www.cs.cornell.edu/~yinlou/papers/lou-kdd13.pdf).*
```

## Ref

- [Accurate intelligible models with pairwise interactions](https://dl.acm.org/citation.cfm?id=2487579)

**Comment by peractio** [comment]
There is actually another paper that seems to be helpful, in KDD '12. The KDD '12 and KDD '13 papers were in the references of the KDD '15 paper referenced in the `README`

Not sure if it'll be clearer to include all those papers, like the description below

Papers were in KDD ’12, ’13, ’15
* For more details on the model: 
    * A review of GAMs. They tested different GAMs and found boosted bagged trees to be the best -- https://www.cs.cornell.edu/~yinlou/papers/lou-kdd12.pdf  
    * On extending GAM to GA2M, thereby increasing performance. They proposed a greedy search algorithm that decreases computing resources required, with little cost to performance -- http://www.cs.cornell.edu/~yinlou/papers/lou-kdd13.pdf
* Paper with results on medical data: 
    * GA2M applied to predict pneumonia risk and hospital readmission -- https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/KDD2015FinalDraftIntelligibleModels4HealthCare_igt143e-caruanaA.pdf

**Comment by interpret-ml** [comment]
Hi @OpenJNY and @peractio , 

Thanks for bringing this up! We're actually in the process of adding a much more comprehensive references section to our README in the coming days -- stay tuned! We'll update this issue once we've added it in. 

-InterpretML Team

**Comment by OpenJNY** [comment]
Hi @peractio, thank you for your wrapping up my lack of survey!
I'm looking forward to the growth of InterpretML😄.

**Comment by interpret-ml** [comment]
Hi @OpenJNY and @peractio , 

Just wanted to follow up on this issue. We have a much more comprehensive citation system on our readme now: https://github.com/interpretml/interpret#citations

That includes a paper about InterpretML, many papers written about EBM/GA2M, and a host of papers about the other methods included in InterpretML. Please check it out and let us know what you think!

-InterpretML Team

**Comment by peractio** [comment]
Yup it's looking good! Much more comprehensive now

Was thinking it may be more convenient to put the paper link beside the paper name and authors, but it's reasonable to make the "how to cite" part for each paper more prominent, as you've done
