### ISSUE TITLE
AttributeError: Can't pickle local object

### ISSUE THREAD

**Issue by enixon44** [interpretml/interpret#87]
I'm getting the following error - what could be causing this?
Running on:
Windows 10
VS Code
Python 3.6.8

ebm.fit(X_train, y_train)...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<FILENAME> in 
----> 1 ebm.fit(X_train, y_train)

~\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\interpret\glassbox\ebm\ebm.py in fit(self, X, y)
    879         )
    880 
--> 881         estimators = provider.parallel(train_model, train_model_args_iter)
    882 
    883         if isinstance(self.interactions, int) and self.interactions > 0:

~\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\interpret\provider\compute.py in parallel(self, compute_fn, compute_args_iter)
     19     def parallel(self, compute_fn, compute_args_iter):
     20         results = Parallel(n_jobs=self.n_jobs)(
---> 21             delayed(compute_fn)(*args) for args in compute_args_iter
     22         )
     23         # NOTE: Force gc, as Python does not free native memory easy.

~\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
    777             # was dispatched. In particular this covers the edge
    778             # case of Parallel used with an exhausted iterator.
--> 779             while self.dispatch_one_batch(iterator):
    780                 self._iterating = True
    781             else:

~\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    618 
    619         with self._lock:
--> 620             tasks = BatchedCalls(itertools.islice(iterator, batch_size))
    621             if len(tasks) == 0:
    622                 # No more tasks available in the iterator: tell caller to stop.

~\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py in __init__(self, iterator_slice)
    125 
    126     def __init__(self, iterator_slice):
--> 127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 

~\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\interpret\provider\compute.py in (.0)
     19     def parallel(self, compute_fn, compute_args_iter):
     20         results = Parallel(n_jobs=self.n_jobs)(
---> 21             delayed(compute_fn)(*args) for args in compute_args_iter
     22         )
     23         # NOTE: Force gc, as Python does not free native memory easy.

~\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\joblib\parallel.py in delayed(function, check_pickle)
    181     # using with multiprocessing:
    182     if check_pickle:
--> 183         pickle.dumps(function)
    184 
    185     def delayed_function(*args, **kwargs):

AttributeError: Can't pickle local object 'BaseEBM.fit..train_model'

**Comment by interpret-ml** [comment]
Hi @enixon44, 

Thank you for reporting this! We've never seen this issue before. Do you mind sharing what version of pickle, joblib, and interpret you have on your machine? You can check these by using "pip show" (ex: ```pip show pickle```) on a terminal.

We'll continue to investigate this on our end too.

-InterpretML Team

**Comment by trungngv** [comment]
I'm also having the same issue on Ubuntu 14.04.5, Python 3.6, interpret 0.1.19, joblib 0.11

**Comment by trungngv** [comment]
Updating to latest versions of scikit-learn, joblib has solved the issue for me.

**Comment by interpret-ml** [comment]
Glad to hear that updating scikit-learn and joblib solved the issue for you @trungngv! 

Thanks for posting your library versions earlier. We'll look into this to see if we can replicate it. It could be a sign that we need to set our scikit-learn / joblib dependencies to more recent versions of those libraries. We'll leave this issue open in the interim in case other people have the same problem.
