### ISSUE TITLE
setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') on Python 3.8

### ISSUE THREAD

**Issue by lucazav** [interpretml/interpret#92]
I'm getting the following error when trying to install interpret on Python 3.8:

> C:\Setup>pip install interpret
> Collecting interpret
>   Using cached https://files.pythonhosted.org/packages/d6/b3/e53fb0ecf09fc4a443a9c7da15a56916544b544c9f134d0496b1152be795/interpret-0.1.19-py3-none-any.whl
> Collecting interpret-core[dash,debug,decisiontree,ebm,lime,linear,notebook,plotly,required,sensitivity,shap,treeinterpreter]>=0.1.19
>   Using cached https://files.pythonhosted.org/packages/b0/c6/1414b77de333f11bc46c6033fcdb7b965513b2e0d3310cae87e5484a64f5/interpret_core-0.1.19-py3-none-any.whl
> Collecting dash>=1.0.0; extra == "dash"
>   Using cached https://files.pythonhosted.org/packages/03/f4/d27b82bc85d2e7834d478ff5598bdfcc1835ec10723c79e0239dadee6dfd/dash-1.6.1.tar.gz
> Collecting dash-cytoscape>=0.1.1; extra == "dash"
>   Downloading https://files.pythonhosted.org/packages/aa/93/d9db22331dcad4a055631372816bf4544a1a1a852fb2fa3a2905c6682198/dash_cytoscape-0.1.1.tar.gz (3.4MB)
>      |████████████████████████████████| 3.4MB 139kB/s
> Collecting dash-table>=4.1.0; extra == "dash"
>   Using cached https://files.pythonhosted.org/packages/17/3b/955732356f7078feb4fbae38a9eb971fa55278cc31310c8ae1f0186f1b10/dash_table-4.5.1.tar.gz
> Collecting gevent>=1.3.6; extra == "dash"
>   Using cached https://files.pythonhosted.org/packages/ed/27/6c49b70808f569b66ec7fac2e78f076e9b204db9cf5768740cff3d5a07ae/gevent-1.4.0.tar.gz
>     ERROR: Command errored out with exit status 1:
>      command: 'c:\users\administrator\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-kr5ld_to\\gevent\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-kr5ld_to\\gevent\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-install-kr5ld_to\gevent\pip-egg-info'
>          cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-kr5ld_to\gevent\
>     Complete output (116 lines):
>     Compiling src/gevent/libev/corecext.pyx because it depends on c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\Cython\Includes\libc\string.pxd.
>     [1/1] Cythonizing src/gevent/libev/corecext.pyx
>     Compiling src/gevent/resolver/cares.pyx because it depends on c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\Cython\Includes\libc\string.pxd.
>     [1/1] Cythonizing src/gevent/resolver/cares.pyx
>     Traceback (most recent call last):
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
>         yield saved
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
>         yield
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
>         _execfile(setup_script, ns)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
>         exec(code, globals, locals)
>       File "C:\Users\ADMINI~1\AppData\Local\Temp\easy_install-32wsvu0n\cffi-1.13.2\setup.py", line 127, in <module>
>         HUB_PRIMITIVES = Extension(name="gevent.__hub_primitives",
>       File "C:\Users\ADMINI~1\AppData\Local\Temp\easy_install-32wsvu0n\cffi-1.13.2\setup.py", line 105, in uses_msvc
>         include_dirs=include_dirs)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 225, in try_compile
>         self._compile(body, headers, include_dirs, lang)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 127, in _compile
>         src = self._gen_temp_sourcefile(body, headers, lang)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 109, in _gen_temp_sourcefile
>         with open(filename, "w") as file:
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 418, in _open
>         self._violation("open", path, mode, *args, **kw)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
>         raise SandboxViolation(operation, args, kw)
>     setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') {}
> 
>     The package setup script has attempted to modify files on your system
>     that are not within the EasyInstall build area, and has been aborted.
> 
>     This package cannot be safely installed by EasyInstall, and may not
>     support alternate installation locations even if you run its setup
>     script by hand.  Please inform the package's author and the EasyInstall
>     maintainers to find out if a fix or workaround is available.
> 
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Administrator\AppData\Local\Temp\pip-install-kr5ld_to\gevent\setup.py", line 427, in <module>
>         run_setup(EXT_MODULES, run_make=_BUILDING)
>       File "C:\Users\Administrator\AppData\Local\Temp\pip-install-kr5ld_to\gevent\setup.py", line 328, in run_setup
>         setup(
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
>         _install_setup_requires(attrs)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
>         dist.fetch_build_eggs(dist.setup_requires)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
>         resolved_dists = pkg_resources.working_set.resolve(
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
>         dist = best[req.key] = env.best_match(
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
>         return self.obtain(req, installer)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
>         return installer(requirement)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
>         return cmd.easy_install(req)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
>         return self.install_item(spec, dist.location, tmpdir, deps)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
>         dists = self.install_eggs(spec, download, tmpdir)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
>         return self.build_and_install(setup_script, setup_base)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
>         self.run_setup(setup_script, setup_base, args)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
>         run_setup(setup_script, args)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
>         raise
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
>         yield
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
>         saved_exc.resume()
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
>         six.reraise(type, exc, self._tb)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
>         raise value.with_traceback(tb)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
>         yield saved
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
>         yield
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
>         _execfile(setup_script, ns)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
>         exec(code, globals, locals)
>       File "C:\Users\ADMINI~1\AppData\Local\Temp\easy_install-32wsvu0n\cffi-1.13.2\setup.py", line 127, in <module>
>         HUB_PRIMITIVES = Extension(name="gevent.__hub_primitives",
>       File "C:\Users\ADMINI~1\AppData\Local\Temp\easy_install-32wsvu0n\cffi-1.13.2\setup.py", line 105, in uses_msvc
>         include_dirs=include_dirs)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 225, in try_compile
>         self._compile(body, headers, include_dirs, lang)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 127, in _compile
>         src = self._gen_temp_sourcefile(body, headers, lang)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 109, in _gen_temp_sourcefile
>         with open(filename, "w") as file:
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 418, in _open
>         self._violation("open", path, mode, *args, **kw)
>       File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
>         raise SandboxViolation(operation, args, kw)
>     setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') {}
> 
>     The package setup script has attempted to modify files on your system
>     that are not within the EasyInstall build area, and has been aborted.
> 
>     This package cannot be safely installed by EasyInstall, and may not
>     support alternate installation locations even if you run its setup
>     script by hand.  Please inform the package's author and the EasyInstall
>     maintainers to find out if a fix or workaround is available.
> 
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by interpret-ml** [comment]
Hi @lucazav, 

Thank you for reporting this! It appears that gevent requires version 1.5+ for Python 3.8 (see: https://github.com/gevent/gevent/issues/1476#issuecomment-551936585), whereas pip pulls in version 1.4. Seems like version 1.5 is on pre-release on PyPi, so you'll have to run the following command first:

```pip install gevent==1.5a2```

and then

```pip install interpret```

I was able to get the installation to work in a fresh environment by following these steps. Leaving this issue open as we continue to look into it, so that people can find the temporary fix, or if there are further issues relating to installation problems on Python 3.8.

-InterpretML Team

**Comment by interpret-ml** [comment]
Hi @lucazav -- We've recently added support for python 3.8.  This shouldn't be an issue anymore, but please reopen if it doesn't work for you.

-InterpretML team
