### ISSUE TITLE
How to change the limits of the colormap?

### ISSUE THREAD

**Issue by hpsong88** [interpretml/interpret#93]
I have a question: how to change the colormap's limits when showing the heatmap of interactions?

Thanks!

**Comment by interpret-ml** [comment]
Hi @hpsong88, 

Thanks for the question! By default, he heatmap's colorscheme is automatically determined to be the max/min value across all graphs. This is logged through the ```scores_range``` key in the explanation object, so you can manipulate it by changing that value. 

For example, when I first generate the interaction, I might see something like this: 

![image](https://user-images.githubusercontent.com/50031429/69685444-3e40bb80-1071-11ea-886b-12118ca0e9d9.png)


I can access the data behind any explanation with the .data() method, which returns a dictionary. Manipulating this dictionary enables us to update the visualization. For example: 

![image](https://user-images.githubusercontent.com/50031429/69685533-94156380-1071-11ea-9574-1d7e4085e23c.png)

After setting the ```scores_range``` to (-0.25, 0.25), I get this updated visualization:

![image](https://user-images.githubusercontent.com/50031429/69685577-c1faa800-1071-11ea-91d0-f5f4b98eb7bb.png)

Let us know if this helps address your question!

-InterpretML Team

**Comment by hpsong88** [comment]
Very helpful! Thank you so much!
