### ISSUE TITLE
cannot choose component to show 

### ISSUE THREAD

**Issue by packermaster** [interpretml/interpret#94]
when I train a ebm model and use explain_global method to show ,but there just a summary graph,whatever I choose the component ,nothing to change。I don not know where has problem?
![image](https://user-images.githubusercontent.com/29559484/69527777-f73ac380-0fa7-11ea-815a-1a6216799d76.png)

**Comment by interpret-ml** [comment]
Hi @packermaster, 

Thank you for reporting this. Sometimes it takes a little while for the graphs to start updating -- does this problem still hold after say 30 seconds? Do you mind sharing what type of environment you're running the script in (ex: Jupyter Notebook, Databricks, etc.)?

If that doesn't work, you can consider using an alternate visualization provider, which will change how we serve the graphs on the backend. Try running this code at the start of your notebook/script:


```python
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

-InterpretML Team
