### ISSUE TITLE
How to export explantion graph to local file or without notebook？

### ISSUE THREAD

**Issue by RockLeeStudio** [interpretml/interpret#95]
```
ebm = ExplainableBoostingClassifier(n_jobs=1)
ebm.fit(X_df, y_df)

ebm_global = ebm.explain_global()
show(ebm_global)
```

Above code didn't show any figure in the Pycharm console... I don't want to use notebook....So, How can I export explanation graph to console or local file?

**Comment by interpret-ml** [comment]
Hi @RockLeeStudio,

A quick note: the integrated visualization experiences might work in Pycharm if you are using the built-in Jupyter notebook support (like here: https://www.jetbrains.com/help/pycharm/jupyter-notebook-support.html). 

But it's totally understandable that you might not want to use Jupyter at all. The show() method is really optimized for notebook experiences, but you can easily export the generated graphs to the filesystem with just a bit of extra code. 

Each explanation comes with many visualizations (ex: one graph for every feature). You can access the visualizations directly by using the ```.visualize()``` method on an explanation object: 

```python
ebm_global = ebm.explain_global()
ebm_global.visualize(20)  # visualizes the 20th feature
```

Each visualization is a plotly object. You can simply use plotly functions, like ```write_image``` or ```write_html``` to export the graphs:

```
ebm_global.visualize(20).write_html("graph20.html")  # can also pass in a full filepath here
```

Simply run this in a loop if you want all of the graphs for each explanation exported at once. HTML exports will preserve all the interactivity, and can be opened/viewed in your browser. For static image exports, like PNG, you can also use Plotly utilities (documentation here: https://plot.ly/python/static-image-export/)

Hope this helps!

-InterpretML Team

**Comment by RockLeeStudio** [comment]
I have tried the method and it also works for ebm.explain_local().
Thanks.
