### ISSUE TITLE
show method while running in AWS EMR

### ISSUE THREAD

**Issue by matheus-asilva** [interpretml/interpret#96]
When running 
`from interpret import show`
`from interpret.perf import ROC`
`blackbox_perf = ROC(blackbox_model.predict_proba).explain_perf(X_test, y_test, name='Blackbox')`
`show(blackbox_perf)`

I have the following error

`RuntimeError: Could not find open port.`
`                Consider calling interpret.set_show_addr(("127.0.0.1", 7001)) first.`.

Even calling the set_show_addr, I can't see the results. How can I handle with that?

**Comment by interpret-ml** [comment]
Hi @matheus-asilva , 

Thanks for reporting this. By default, interpret tries to find an open port to host a local web server for visualizations. It could be that your environment doesn't allow new ports to be opened. We have an alternative visualization backend that should work in situations like this (originally discussed here: https://github.com/interpretml/interpret/issues/52) 

If you run the following code at the top of your notebook:

```python3
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

Interpret will start rendering visualizations in Javascript, and embed them directly in the notebook (without needing to spin up a local server). You can then use the show method the exact same way as before. Ex:

```python3
ebm_global = ebm.explain_global()
show(ebm_global) # Works without a web server if set_visualize_provider() was run earlier
```

Please let us know if this works for you!

-InterpretML Team
