### ISSUE TITLE
Crashing on large data sets

### ISSUE THREAD

**Issue by jamie-murdoch** [interpretml/interpret#99]
I'm trying to train an EBMClassifier on a large dataset (10M samples, 800 features) with no interactions, and am finding that the function crashes during fitting. I have tried training on smaller subsets, and it seems like around 500k is where things break (even a forward call on 500k samples breaks things). 

I'm running on a very large machine in the cloud (40 CPUs, 961 GB), so running out of memory shouldn't be an issue. 

Are there any potential workarounds here, or have I just hit the limits of the current implementation?

**Comment by interpret-ml** [comment]
Hi @jamie-murdoch  --

If you haven't updated to our latest v0.1.20, then you should try that first.  We've been making some memory efficiency improvements, and it should require around 2-3 times less memory, but that probably still won't allow you to process all 10M samples.  So, next try setting n_jobs=1 and see if that works.  If it works at 1, try 2, 3, etc for faster processing.  Currently we spawn processes to work in parallel, but each process uses more memory, so reducing the number of processes might help you.

We're currently working towards a more memory efficient representation of the data by moving most of the data into C++ where it will be further compressed and also shared between processes.  The 2-3 fold reduction in our latest version is a baby step in that direction.  The full update is maybe a month or two out, but it should radically reduce the data size by a factor between 10-1000 times, depending on the composition of your data.

Please let us know if the n_jobs trick works for you.  If there is some other issue at work then we'd like to debug further.

-InterpretML Team

**Comment by jonrossclaytor** [comment]
Hi @interpret-ml team, is there any update on the availability of the change referenced above to improve memory efficiency?

**Comment by interpret-ml** [comment]
Hi @jonrossclaytor,

We're still a few weeks away from putting this out. This will be a relatively big change internally, and it touches a lot of cross language python/C++ constructs. We're aware of a number of groups that are currently being held back by memory size related issues, so this is currently top of stack in terms of priority.

In the meantime, the n_jobs=1 trick should get you pretty far, albeit at the cost of training time.  Alternatively, if you really need this to work today at maximum speed, the cloud providers all have VMs with ridiculous amounts of memory.  The current biggest on Azure (M-series) has 4TB of ram!

-InterpretML team

**Comment by interpret-ml** [comment]
Hi @jamie-murdoch and @jonrossclaytor  -- The latest code in the develop branch finally includes the substantial reductions in memory usage.  It uses approximately 10x less memory now compared to the previous release.  Our next pypi release will include these changes.

-InterpretML team
